### ISSUE TITLE
Usage docs?

### ISSUE THREAD

**Issue by diogobaeder** [marshmallow-code/flask-smorest#1]
Hey guys,

Interesting project you have here; are there any plans on how to actually use it?

Thanks!
Diogo

**Comment by lafrech** [comment]
Hi.

Thank you for your interest and your comment.

Documentation is perhaps the most important lacking feature...

This lib is something we pulled out of our code. We're using it in two applications. We've done an important rework and added pretty comprehensive tests, and I think it should be reasonably stabilized, now. There might be changes considered breaking in the future, but hopefully those should be corner cases.

The ETag and pagination features may be a bit tricky and really deserve documentation. The comments in the code should help. Anyway, they are not mandatory so you may ignore them at first.

To get an idea of how it works, you may take a look at the examples in the tests.

Think `Blueprint`. Separate your application in `Blueprint`s. Each `Blueprint` will be a section in the spec, like Users, Teams, Pets, whatever. Define your `Blueprint`s like in the first example in test_examples.py (`MethodView` are nice for typical CRUD use cases), use the `arguments` and `response` decorators to pass serialization/deserialization `Schema`s and the `route` decorator to register a `MethodView`, then register the `Blueprint`s in the API:

```python
        api = Api(app)
        api.register_blueprint(blueprint)
```

Tell me how it goes if you get the time to give it a try!

**Comment by diogobaeder** [comment]
Hi guys,

Sorry for the very long delay, but I ended up going to a different direction, therefore I have no plans of using this project anymore (if things change I'll let you know, though).

Thanks!
Diogo

**Comment by lafrech** [comment]
Alright. No pb.

Let's keep this open until docs are published.

**Comment by lafrech** [comment]
Done !

https://flask-rest-api.readthedocs.io/
