### ISSUE TITLE
Replacement for Flask-apispec

### ISSUE THREAD

**Issue by paxnovem** [marshmallow-code/flask-smorest#106]
I am a current user of Flask-apispec, and was curious about this projects relationship with it since it has been pulled under the marshmallow org. Flask-apispec and Flask-smorest seem to have a great deal of overlap in terms of project goals. Both appear to be wrappers around webargs, apispec, and marshmallow. It is my understanding that flask-apispec is maintained by @sloria  at this time and it might be worth deprecating flask-apispec since this one is now in the marshmallow-code organization. I bring this up since this seems to be getting a lot more attention than flask-apispec and it might be useful to focus in on one solution if they have such similar goals and api's. 

If flask-apispec were deprecated for this it would make sense to document a migration path from apispec. 

Thank you for all the work on marshmallow and surrounding projects.

**Comment by lafrech** [comment]
Thanks.

Indeed, both libs are wrappers around webargs, apispec, and marshmallow and achieve more or less the same goals. They are redundant.

I can't speak for flask-apispec as I don't use it. AFAIK, the original author doesn't use it anymore, and @sloria maintains it by keeping up with dependencies and reviewing/merging PRs but has no plans to enhance it.

I don't think we can deprecate flask-apispec to point to flask-smorest. If people are happily using flask-apispec in stable production code, there's no urge to switch. And if there are things improve or fix there, anyone can stand out and submit a PR, perhaps even become a co-maintainer.

I can't really document a migration path as I don't know flask-apispec. Hopefully, if its feature set is covered by flask-smorest, the move can be made at no loss, and the documentation and examples here should be enough to help.

If you do try this, you may keep us posted here about the issues you face, or about the easy move if all goes smooth.

**Comment by paxnovem** [comment]
That makes sense, I will definitely update if we make the switch over to smorest, though we would be waiting for the project to mature a bit more to a 1.0 release. I will contribute where I can to help both projects. Thank you for your work and I will help out where I can.
