### ISSUE TITLE
how to use dynamically created schemas?

### ISSUE THREAD

**Issue by fdion** [marshmallow-code/flask-smorest#109]
In marshmallow, it is possible to dynamically generate a schema from a dictionary.

`SomeSchema = ma.Schema.from_dict(the_dict)`

If I use SomeSchema in the decorator:

```
@some_app.response(SomeSchema, 201)
    def get(self):
```

The resulting openapi.json:

```
"Generated": {
        "type": "object",
        "properties": {}
      }
```

I can obviously change the name from Generated (using dunder name), but why are properties empty?

If I declare the Schema in a class, manually, it works as intended, of course.

**Comment by lafrech** [comment]
Interesting.

I'm not familiar with marshmallow's `from_dict` feature.

Could you please send a complete example we could play with?

**Comment by fdion** [comment]
Heh. Turns out I was mistaken how from_dict really worked. What put me on the wrong trail is that I loaded a dictionary with "properties" as the top key and was seeing it in dir(). But that's not how it should be loaded. That's why the properties was showing up {}.

When defining the dictionary with just the basic {"id": ma.fields.Int() etc } then it works.

This can be closed, user error :)
