### ISSUE TITLE
Question: Multiple values for a request parameter possible?

### ISSUE THREAD

**Issue by kettenbach-it** [marshmallow-code/flask-smorest#111]
Is it somehow possible to associate multiple values for a request parameter with "or" and get a union from the API? I'm using flask + sqlalchemy + marshmallow-sqlalchemy

**Comment by lafrech** [comment]
If I understand the question correctly, this is something I do using `DelimitedList` from webargs.

It doesn't work perfectly with apispec (https://github.com/marshmallow-code/apispec/issues/500). We should be able to fix this when webargs 6 is out. Until then, I fix the doc manually.

Once the delimited list is deserialized, I inject it into my databse framework manually.

**Comment by kettenbach-it** [comment]
Thx for the hint!  And yes: this answers my question
