### ISSUE TITLE
Require an up-to-date Flask

### ISSUE THREAD

**Issue by rspeer** [marshmallow-code/flask-smorest#114]
A co-worker tried to run my flask-smorest code, and found that the Swagger documentation wasn't being served; there was instead an error that `/openapi.json` was not found. The issue was that I was on Flask 1.1.1 but he was on 0.12. Updating his environment to Flask 1.1.1 resolved the issue.

I can require `flask >= 1.1` in my own project, but this suggests that flask-smorest itself should depend on a certain minimum version of Flask.

**Comment by lafrech** [comment]
It does

https://github.com/marshmallow-code/flask-smorest/blob/888ffed07725154d353bf7a45066eb015d4db91e/setup.py#L48

Not sure what happened to your colleague.

**Comment by irufus** [comment]
@rspeer how did your coworker go about installing the needed modules? Were you using Pipfile, requirements or ?

**Comment by rspeer** [comment]
Oh, huh. I watched him run `pip install -e .` in my project, whose setup.py requires flask-smorest, before running the server. It seemed to check the dependencies, but it also looks like it installed flask via a _different_ dependency and didn't check its version.

It looked like this:

```
Requirement already satisfied: flask-smorest [...] (0.18.2)
Requirement already satisfied: flask [...] (from OpenNMT) ... (0.12.1)
```

I'd have to keep poking around his computer to figure out exactly what happened here. Now I know it's not a bug in flask-smorest and I'm willing to write it off as "pip is weird sometimes".
