### ISSUE TITLE
Support for other pagination formats

### ISSUE THREAD

**Issue by pmdarrow** [marshmallow-code/flask-smorest#118]
I'm looking at adopting flask-smorest for a Flask API I've already built with webargs and marshmallow (great code quality by the way!). Unfortunately I've already implemented pagination in the body instead of headers and want to maintain backward compatibility. For example:

```
GET https://xyz/posts?offset=50&limit=10

{ 
  "data": [{item 1}, {item 2}, ...],
  "paging": {
    "count": 1088,
    "next": "https://xyz/posts?limit=10&offset=60",
    "previous": "https://xyz/posts?limit=10&offset=40"
  }
}
```

What's the best way of implementing this? Should I just create my own pagination decorator based off yours, or would you consider adding support for this kind of approach?

**Comment by lafrech** [comment]
I try to provide hooks and make things overridable to help customizing.

What you could do is try to do that in your own code by overriding stuff. If you need more hooks to avoid duplicating too much stuff, we can discuss it here.

Depending on how it goes, we'll see if it is reasonable to integrate this feature in the core.

I try to keep responsibilities as separated as I can, each Mixin sticking to its role, but sometimes I have to make exceptions and the Mixins are not perfectly independent. There are hooks in ResponseMixin allowing to nest the response in a "data" sub-structure. You might have to use those hooks to cram the pagination metadata in the response, which kind of smells, in terms of responsibility separation. Maybe you'll come up with a better design.

**Comment by lafrech** [comment]
@pmdarrow, I just submitted a PR that adds needed hooks and a test showing how to do it in custom code.

Do you think you could have a look at it and maybe give it a try?

**Comment by lafrech** [comment]
#153 allows user to customize pagination and provides an example.

Closing. Please comment if your use case is not met.
