### ISSUE TITLE
Pluck registers new schema

### ISSUE THREAD

**Issue by mcclurem** [marshmallow-code/flask-smorest#121]
I have a model of objects that includes a "Project" and a Project contains many "Design".
When I serialize the Design object it has a pointer back to the schema object that I just want to be serialized as just the name of the schema. Code example below showing the line that "works" and the line that "doesn't work"

```python
class ProjectSchema(ma.ModelSchema):
    class Meta:
        model = models.Project
    name = ma.String(required=True)
    designs = ma.Mapping(values=ma.Nested(DesignSchema(only=['name','id'])))

class DesignSchema(ma.ModelSchema):
    class Meta:
        model = models.Design
    # This creates a second schema called Project1 in the APISpec
    project = ma.Pluck('ProjectSchema', 'name', many=False)
    # This works 
    project = ma.String(attribute='project.name')
```

This feels a bit wrong. I would expect that since pluck can resolve that ProjectSchema.name is a scalar field type, it should be able to represent this as a simple string instead of generating a new schema. I'm guessing this is because the Pluck field derives from the Nested class. Is this a feature request that needs to be pushed upstream or is it something to be fixed in smorest?
If it's in smorest and you can give me a hint at where I might be hunting I can take a stab at it

**Comment by lafrech** [comment]
Hi.

Glad you're willing to help on `Pluck` support.

Please see https://github.com/marshmallow-code/apispec/issues/459.

(I think the refactor I'm mentioning in there was done in the meantime.)

**Comment by lafrech** [comment]
Closing as it is an apispec issue (https://github.com/marshmallow-code/apispec/issues/459).
