### ISSUE TITLE
Exception after upgrading to version 0.19.0 and 0.19.1

### ISSUE THREAD

**Issue by ghost** [marshmallow-code/flask-smorest#129]
Hi,

Python beginner here after updating to version 0.19.0 and 0.19.1 i get the following error when trying to run the Flask server. I don't know much else than to include the traceback.
```
Traceback (most recent call last):
  File "/Users/xyz/project1/api.py", line 65, in <module>
    api.register_blueprint(blueprint.bp)
  File "/Users/xyz/project1/python-helpers/python/flask_smorest/__init__.py", line 89, in register_blueprint
    blp.register_views_in_doc(self._app, self.spec)
  File "/Users/xyz/project1/python-helpers/python/flask_smorest/blueprint.py", line 189, in register_views_in_doc
    method=method_l
  File "/Users/xyz/project1/python-helpers/python/flask_smorest/response.py", line 172, in _prepare_response_doc
    doc = deepupdate(doc, operation)
  File "/Users/xyz/project1/python-helpers/python/flask_smorest/utils.py", line 18, in deepupdate
    original[key] = deepupdate(original.get(key, {}), value)
  File "/Users/xyz/project1/python-helpers/python/flask_smorest/utils.py", line 18, in deepupdate
    original[key] = deepupdate(original.get(key, {}), value)
  File "/Users/xyz/project1/python-helpers/python/flask_smorest/utils.py", line 20, in deepupdate
    original[key] = value
TypeError: 'str' object does not support item assignment
```
I am using Python version 3.7.6 and I really like your library

**Comment by lafrech** [comment]
Hi. Thanks for reporting.

Do you think you could provide a sample code to reproduce?

Or perhaps add a `print()` somewhere to see what gets in `deepupdate`? For instance in

flask_smorest/response.py", line 172, in _prepare_response_doc

```py
    print(doc)
    print(operation)
    doc = deepupdate(doc, operation)
```

**Comment by ghost** [comment]
How's this? I am using marshmallow 3.5.0 as well

```
{'responses': {422: 'Unprocessable Entity'}, 'requestBody': {'required': True, 'content': {'application/json': {'schema': <FieldRequestSchema(many=True)>}}}}
{'responses': {422: {'description': 'Validation Error', 'content': {'application/json': {'schema': <MarshmallowErrorSchema(many=False)>}}}, 'default': 'Default Error'}}
```

edit:

It seems it's the 
```python
@bp.arguments(InputRequestSchema)
@bp.response(MarshmallowErrorSchema, code=422, description='Validation Error')
def post(*args):
    pass
```

**Comment by lafrech** [comment]
Thanks.

This is an old issue in deepupdate function that had never be unveiled before.

Fix incoming.

**Comment by lafrech** [comment]
I'm not sure what you're trying to achieve, but you shouldn't have to do that.

The point of the 0.19 release is to auto-document error responses when possible. 422 errors are automatically documented already.

If you need to generate 422 errors inside your view function, just call `abort(422, errors={optional error structure})` and you're done. No need for you to declare an error schema.

Hopefully, this issue should be fixed and you should be able to see the errors described in the doc.

If you need a different error schema you may have to override stuff in the error handler.

**Comment by ghost** [comment]
Thanks, i'll look into that. 

Can confirm 0.19.2 works again for my case.
