### ISSUE TITLE
Response code `default` added to all paths

### ISSUE THREAD

**Issue by ghost** [marshmallow-code/flask-smorest#131]
Hi.

Using version _0.19.2_ and your supplied quickstart example generates unexpected responses to the openapi definition. If we're looking at the first path `/pets` get i would expect a response code `422` to be generated because of the `@bp.arguments` decorator, but I get an additional `default` response code which is not expected. This is unexpected additional `default` response code is generated for all paths.

```json
{
   "paths": {
      "/pets/": {
         "get": {
            "parameters": [
               {
                  "in": "query",
                  "name": "name",
                  "required": false,
                  "schema": {
                     "type": "string"
                  }
               }
            ],
            "responses": {
               "200": {
                  "description": "OK",
                  "content": {
                     "application/json": {
                        "schema": {
                           "type": "array",
                           "items": {
                              "$ref": "#/components/schemas/Pet"
                           }
                        }
                     }
                  }
               },
               "422": {
                  "$ref": "#/components/responses/Unprocessable Entity"
               },
               "default": {
                  "$ref": "#/components/responses/Default Error"
               }
            },
            "summary": "List pets",
            "tags": [
               "pets"
            ]
         },
         "post": {}
      }
   }
}
```

**Comment by lafrech** [comment]
This is intended.

https://swagger.io/specification/#responsesObject
https://swagger.io/docs/specification/describing-responses/

This is added by the `@response` decorator.

The point is to tell the client that there may be other errors and such errors conform to `"Default Error"` definition.

I didn't find a way to factorize this at the top level as "default response for all paths/methods".

Is there an issue with this?

**Comment by lafrech** [comment]
Closing this. Please comment if this is an issue and I'll reopen.
