### ISSUE TITLE
Documenting path parameters in blueprint url_prefix

### ISSUE THREAD

**Issue by pmdarrow** [marshmallow-code/flask-smorest#139]
How do I document path parameters that appear in `url_prefix` in a Blueprint? Example:

```
blueprint = Blueprint(
    'Media',
    __name__,
    url_prefix='/brands/<int:brand_id>/media',
)

@blueprint.route(...)
...
```

I've read through https://github.com/marshmallow-code/flask-smorest/issues/23 but it only seems to apply to `@blueprint.route()`, not `Blueprint()`.

**Comment by lafrech** [comment]
I never thought about this. I didn't even know it was possible.

It may require a specific development.

Please keep us posted if you make any progress on this.

**Comment by lafrech** [comment]
Note that `url_prefix` can also be passed in `register_blueprint` so we should add a `parameters` argument to both `Blueprint` and `register_blueprint`.

**Comment by travipross** [comment]
I also have encountered this scenario and am interested in any workarounds or future updates to support this.

**Comment by kaos** [comment]
how about
```python
class MyBlueprint (Blueprint):
    def __init__(self, *args, prefix_parameters=None, **kwargs):
        super().__init__(*args, **kwargs)
        self._prefix_parameters = prefix_parameters

    def route(self, *args, parameters=None, **kwargs):
        if self._prefix_parameters is not None:
            parameters = self._prefix_parameters + (parameters or [])

        return super().route(*args, parameters=parameters, **kwargs)


# Usage:

blueprint = MyBlueprint(
    'Media',
    __name__,
    url_prefix='/brands/<int:brand_id>/media',
    prefix_parameters=[
        {...}
    ]
)

@blueprint.route(...)
...
```

**Comment by lafrech** [comment]
I just sent a PR for this. Sorry about the delay. It was less complicated than I expected.

`url_prefix` can be specified both at `Blueprint` init and when calling `register_blueprint`.

I was not totally comfortable with overriding `Blueprint.__init__` and I figured it was enough to just add `parameters` to `register_blueprint`. The downside I see is that it requires the user to pass that parameter on each call to `register_blueprint`, which could lead to code duplication in the unlikely case of a `Blueprint` being registered several times with the same `url_prefix` (I don't think this could happen until perhaps we support nested blueprints). It probably also adds a bit of complexity for apps where all blueprints are registered in a loop, as they must manage this special case. I assume codes with such advanced patterns can easily handle the added complexity.

I'm happy with this resolution and I shall merge #313 pretty soon.
