### ISSUE TITLE
Drop Python 3.5

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/flask-smorest#141]
https://github.com/pallets/flask/releases/tag/1.1.2

> Flask 1.1.x is the last version to support Python 2.7 and Python 3.5.

**Comment by sloria** [comment]
Should we do the same in webargs?

**Comment by lafrech** [comment]
We will need to do it to support next Flask versions but I don't know when those will be out.

Let's say Flask offers us a nice excuse to do it.

**Comment by lafrech** [comment]
Actually we don't _need_ to do it to support next Flask version. We can still support 3.5 on older versions. It just won't make sense once everyone moves to latest. And the tests will be more complicated to parametrize.

The point is I don't feel the need to support versions Flask itself doesn't even support.

This is even more true with flask-smorest as it is not 1.0 yet. I'd like to dust the dependencies before shipping 1.0.

**Comment by lafrech** [comment]
Python 3.5 EOL : 13 Sep 2020.

https://endoflife.date/python
