### ISSUE TITLE
Accessing arguments in response schema

### ISSUE THREAD

**Issue by pmdarrow** [marshmallow-code/flask-smorest#144]
I'd like to conditionally return some data in a response based on the arguments the user passes in. E.g. 

```
GET /foo?include=optional_field_1,optional_field_2

Response:
{
  "optional_field_1": "baz",
  "optional_field_2": "qux"
}
```

Prior to adopting flask-smorest, I would use [schema.context](https://marshmallow.readthedocs.io/en/stable/why.html#context-aware-serialization) for this and conditionally manipulate the response in a pre_dump handler. I don't think this is possible now with flask-smorest. I could simply do it in the view function, but as I want this logic on create, read, update and list endpoints for this collection, it would be nice to keep in a single location - the pre_dump handler. 

Any thoughts about this?

**Comment by lafrech** [comment]
This would be a new feature.

I don't think this can be done in a way generic enough to be part of the core, but I'd be happy to make it easy to achieve.

Right now, you could do it by overriding all `@response` decorator to modify the code in the wrapper to check the args for `include` and use this when dumping with the schema.

A more common approach (I guess), is to pass the fields list to the DB query to not only apply it on dump but also when querying the DB. There is no built-in way to do this is flask-smorest either. flask-restplus provides such a mechanism using a header: https://flask-restplus.readthedocs.io/en/stable/mask.html.

**Comment by pmdarrow** [comment]
Ah yeah, you're probably right - it would be more idiomatic to wrap this logic up in a method on the model. I'll take that approach for now. I appreciate your response!

**Comment by lafrech** [comment]
I think the use case is the same as #234. Let's discuss the feature there.
