### ISSUE TITLE
Cannot use @paginate and query arguments at the same time

### ISSUE THREAD

**Issue by pipozzz** [marshmallow-code/flask-smorest#145]
Hello, 

I cannot use pagination and arguments in location='query'

It force using schema for arguments where are missing fields like `page` `page_size`

```python
    @ads.arguments(schema=ArgsSchema, location='query')
    @ads.response(schema=Schema(many=True))
    @ads.paginate(CursorPage)
    def get(self, args):
        pass
```

and I'm getting this

```
{
  "code": 422,
  "errors": {
    "query": {
      "page": [
        "Unknown field."
      ],
      "page_size": [
        "Unknown field."
      ]
    }
  },
  "status": "Unprocessable Entity"
}```


Do you have some suggestion how to resolve this issue ?

Thanks in advance.

**Comment by lafrech** [comment]
Yes you can.

See https://flask-smorest.readthedocs.io/en/latest/arguments.html#multiple-arguments-schemas.

We could make this a warning in the docs to give it more visibility.

**Comment by pipozzz** [comment]
Thanks, it helped , I didn't notice it, maybe you should add an example also with pagination and arguments checking

**Comment by pipozzz** [comment]
I think we can close this issue, thanks

**Comment by kaos** [comment]
It would indeed be helpful to have this snippet, also in the docs for pagination, so you get the hint, regardless of which order you add things to your endpoint.

> This also applies when using both query arguments and pagination decorator, as the pagination feature uses query arguments for pagination parameters.
