### ISSUE TITLE
Parameter Docs Not Shared Across Endpoint with Multiple Methods

### ISSUE THREAD

**Issue by DrChrisLevy** [marshmallow-code/flask-smorest#147]
First off, thanks for the awesome library. I hope this description make sense. Let me know if I can add anything to make it more understandable.

Here is a code snippet with an endpoint that supports `methods=['GET', 'POST']`.

```
from marshmallow import Schema, fields
from flask_smorest import Blueprint


blueprint = Blueprint(
    'Test Endpoint',
    __name__,
    url_prefix='/',
    description='Endpoints for testing.',
)


class BaseSchema(Schema):
    # Make all schemas operate in strict mode. This is default behavior in the next version of
    # Marshmallow: https://github.com/marshmallow-code/marshmallow/pull/711
    def __init__(self, strict=True, **kwargs):
        super().__init__(strict=strict, **kwargs)


class TestInputSchema(BaseSchema):
    id2 = fields.Int(description='id1 desc.')


class TestResponseSchema(BaseSchema):
    id1 = fields.Int(description='id1 desc.')
    id2 = fields.Int(description='id2 desc.')


@blueprint.route(
    '/test/<int:id1>',
    methods=['GET', 'POST'],
    parameters=[{'name': 'id1', 'in': 'path', 'description': 'Some id1.'}],
)
@blueprint.arguments(TestInputSchema, location='query', as_kwargs=True)
@blueprint.response(TestResponseSchema, code=HTTPStatus.OK)
def test_endpoint(id2, id1):
    """Test
    Test description.
    """
    return {'id1': id1, 'id2:': id2}
```

When the above endpoint and blueprint is used in my flask app it all breaks down. With this stack trace when it tries to register the blueprint.

```
File "/usr/local/lib/python3.6/site-packages/flask_smorest/__init__.py", line 89, in register_blueprint
    blp.register_views_in_doc(self._app, self.spec)
  File "/usr/local/lib/python3.6/site-packages/flask_smorest/blueprint.py", line 201, in register_views_in_doc
    spec.path(rule=rule, operations=doc, parameters=parameters)
  File "/usr/local/lib/python3.6/site-packages/apispec/core.py", line 284, in path
    self.clean_operations(operations)
  File "/usr/local/lib/python3.6/site-packages/apispec/core.py", line 367, in clean_operations
    operation["parameters"] = self.clean_parameters(operation["parameters"])
  File "/usr/local/lib/python3.6/site-packages/apispec/core.py", line 326, in clean_parameters
    "Missing keys {} for parameter".format(missing_attrs)
apispec.exceptions.InvalidParameterError: Missing keys ['name', 'in'] for parameter
```

If I change to  ` methods=['GET'] ` or `methods=['POST']` it works fine. Or if I split it into two separate methods (duplicating the code) and use `methods=['GET']` in one method and `methods=['POST']` in the other it also works. I think flask-smorest is having trouble telling the parameters to apply to both methods.

**Comment by lafrech** [comment]
Thanks for reporting.

Could be related to the same function applying once for each method and mutating the doc dict. Just trying to guess. I thought those were covered by the numerous deepcopies everywhere, but I may have missed one somewhere.

If you have time to investigate this, great. I'll try to look into it when I get the time. Thanks for the repro case.

**Comment by lafrech** [comment]
Exactly.

The same doc structure is copied (not deepcopied) in both responses but the parameters are mutated in apispec's marshmallow plugin.

We can either fix it in apispec by deepcopying `parameter` at https://github.com/marshmallow-code/apispec/blob/38b4288d3f2371f9050a33c1e4c9b3aa754213fd/src/apispec/ext/marshmallow/schema_resolver.py#L71.

Or in flask-smorest by deepcopying the doc structure at https://github.com/marshmallow-code/flask-smorest/blob/master/flask_smorest/blueprint.py#L146.

Generally, I try to fix stuff as upstream as possible, but I'm not sure it is reasonable to expect apispec to manage every such case, as it would require deep-copies everywhere.

`APISpec.path` already deepcopies its inputs We can arguably say that flask-smorest should be responsible for sending "flat" structures (no duplicated part inside).

Therefore, I'm leaning towards solving this in flask-smorest.

**Comment by lafrech** [comment]
apispec heavily relies on mutation so it would be complicated to modify it to fix any issue that may occur when sending an input containing duplications. See https://github.com/marshmallow-code/apispec/issues/561.

I fixed it in flask-smorest by deepcopying the doc info for each method.
