### ISSUE TITLE
Path params not documented well.

### ISSUE THREAD

**Issue by Tang8330** [marshmallow-code/flask-smorest#150]
![image](https://user-images.githubusercontent.com/4412200/82403421-a4e8d580-9a13-11ea-9fe0-578cba1886c2.png)

AFAIK [this](https://github.com/marshmallow-code/flask-smorest/blob/master/tests/test_examples.py#L41) is the only way to inject a variable into the path.
I'd like to inject a variable in the path for the functions rather than on the class.

**Comment by lafrech** [comment]
You mean you tried to pass a schema with location `path` and it didn't yield the output you expected?

I'm not sure how passing args with location `path` is supported. I think I checked before writing the docs, but I always felt it was redundant with Flask path parameter injection. Unless you have specific validators, I suppose. I shall try to add specific tests, if they don't exist already, I can't remember.

Can you please elaborate on

- what you did (your code)
- what you expected (code behaviour and generated spec)
- what you got (code behaviour and generated spec)
- why you want this at func level (specific validator for only one func in the view ?)

?
