### ISSUE TITLE
Include source distribution

### ISSUE THREAD

**Issue by twosigmajab** [marshmallow-code/flask-smorest#16]
According to https://pypi.org/project/flask-rest-api/#files this library currently only provides wheels to PyPI. Best practice is to upload source distributions as well. Fixing should just be a matter of running `python setup.py sdist upload`.

Thanks for maintaining flask-rest-api, hope to try it soon! (Would have tried it already if not for this issue, which makes it harder for me to use it on some internal infrastructure.)

**Comment by lafrech** [comment]
Thanks for the feedback.

The distribution process is still manual. I just pushed a sdist. I'll push both from now on.

Enjoy!

Just out of curiosity, what do you need that for?

**Comment by lafrech** [comment]
I got pawned by https://stackoverflow.com/a/14159430/4653485. Templates were not included in the source package.

I deleted the broken archive. I'll have to include a MANIFEST.in to build a correct archive.

**Comment by twosigmajab** [comment]
Thanks for looking at this so quickly. I'm using an internal tool that can only consume source distributions from PyPI. I can work around this manually but thought I'd report this since it's best practice. In case this is helpful: https://packaging.python.org/guides/distributing-packages-using-setuptools/
Thanks again!

**Comment by lafrech** [comment]
I added a `MANIFEST.in` file to include all needed files in the source distribution.

I also modified `.travis.yml` to deploy `sdist` and `bdist_wheel` to PyPI on tag publication. I got this `.travis.yml` throught trial and error, so anyone knowledgeable, please suggest improvements.

[0.9.2 release](https://pypi.org/project/flask-rest-api/#files) has both `sdist` and `bdist_wheel`.

**Comment by twosigmajab** [comment]
Thanks, fix confirmed!
