### ISSUE TITLE
webargs 6.0 breaks error messages

### ISSUE THREAD

**Issue by brandon-braner** [marshmallow-code/flask-smorest#161]
When upgrading to webargs 6.0 or greater there is a breaking change that nests errors under the location. This is caused by webargs.core.py::_on_validation_error. It looks like this could be fixed for backwards compatibility by using webargs.core.py::error_handler decorator to replace errors.message = error.message.json

Example: If your location is json the errors will now be 
`{
  "code": code,
  "errors": {
    "json": {
     .... errors
`
vs
`{
  "code": code,
  "errors": {
   .... errors
`

**Comment by lafrech** [comment]
This is expected behaviour.

I shall update the CHANGELOG here to point users to webargs docs / upgrading guide.

**Comment by lafrech** [comment]
I completed the CHANGELOG.

Please read [webargs upgrading guide](https://webargs.readthedocs.io/en/latest/upgrading.html) for more.
