### ISSUE TITLE
Document ETag header

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/flask-smorest#162]
When using etag decorator, etag related errors are documented, but the etag header is not.

**Comment by lafrech** [comment]
https://github.com/marshmallow-code/apispec/pull/637 might help.

**Comment by lafrech** [comment]
It's easy to define header components.

However, it would be nice if those headers were defined only if the ETag feature is used. Like in #208.

Unfortunately, we don't really know if it is used.

We decided to enable the feature by default because it is a no-op if the decorated is not used and if the decorator is used, we assume it is the best default. The `ETAG_DISABLED` config flag allows to use the same code base without the feature (for tests, for instance).

If a user doesn't use the feature, nothing tells us the feature is unused, except the fact that the decorator is never used, which is tricky to check.

Possible solutions:

- Make the feature opt-in. Not ideal. Won't support the case where the feature is opted in from config but the decorator is never used (e.g. because it is only used in a view that is (conditionally) not imported).

- Add a mechanism to conditionally add headers if they are actually referenced. Could be extended to all components.

The latter sounds like a better choice but it is not easy to achieve. It goes far beyond the scope of this issue: provide a mechanism to register components that are added to the spec only if they are actually referenced. Let's discuss it in #236.

**Comment by TimDiekmann** [comment]
I just stumbled over this issue while reading the 1.0 Milestone. I had the same issue, that the ETag header is not documented and came up with this solution:

```py
class Blueprint(flask_smorest.Blueprint):
    def _prepare_etag_doc(self, doc, doc_info, *, app, method, **kwargs):
        doc = super()._prepare_etag_doc(doc, doc_info, app=app, method=method, **kwargs)
        if (
                doc_info.get('etag', False) and
                not app.config.get('ETAG_DISABLED', False)
        ):
            # Extend OpenAPI Docs to include `If-Match` header
            if method.upper() in self.METHODS_NEEDING_CHECK_ETAG:
                doc.setdefault("parameters", []).append({
                    'name': 'If-Match',
                    'in': 'header',
                    'required': True,
                    'description': 'Tag to check against',
                    'schema': {'type': 'string'},
                })
            # Extend OpenAPI Docs to include `If-None-Match` header
            if method.upper() in self.METHODS_CHECKING_NOT_MODIFIED:
                doc.setdefault("parameters", []).append({
                    'name': 'If-None-Match',
                    'in': 'header',
                    'description': 'Tag to check against',
                    'schema': {'type': 'string'},
                })
            # Extend OpenAPI Docs to include `ETag` header
            if method.upper() in self.METHODS_ALLOWING_SET_ETAG:
                success_status_code = doc_info.get('success_status_code')
                if success_status_code is not None:
                    doc['responses'][success_status_code].setdefault('headers', {})['ETag'] = {
                        'description': 'Tag for the returned entry',
                        'schema': {'type': 'string'}
                    }
        return doc
```

`doc_info['etag']` is set when the `@etag` decorator is used, so only then the headers are generated.

**Comment by lafrech** [comment]
Yes. This is the way to go.

The only thing that bothers me is the duplication. I wanted to define those headers as spec components but for the reason stated above, this requires an important work in apispec that I'm not done with yet.

But this is optimization. Meanwhile, the spec is more correct with duplicated headers, so your code is welcome.

Would you like to submit a PR with unit tests?

Thanks.
