### ISSUE TITLE
Consider allow setting up OpenAPI title, not from app name

### ISSUE THREAD

**Issue by playpauseandstop** [marshmallow-code/flask-smorest#164]
Hi,

Thanks a lot for this library, I’ve switched to it recently from [flask-apispec](https://pypi.org/project/flask-apispec/) and really pleased of its api, proper OpenAPI 3 support, and overall developer experience. One more time, thanks a lot!

And I have one thing, that I’d like to discuss. Currently flask-smorest setting up `info.title` of OpenAPI 3 schema as Flask app name, but I’m not sure this is proper assumption. From my practice OAS 3 title is more likely human friendly string such as “Product API”, not an import name such as “product_api”.

With that in mind, would it be better to allow developer setup `API_TITLE` via app config as done for `API_VERSION`?

If you against that change, it still able to setup the title via `api.spec.title` assignment, but in that case I’d like to fix title context var for redoc or swagger ui templates, to reuse the value from the spec, instead of app name.

I would be glad to provide a PR for both suggestions if you’ll agree with proposed changes 

Thanks

**Comment by lafrech** [comment]
Hi. Thanks for the nice feedback. I appreciate.

I do set a human title when instantiating the app:

```py
    app = Flask('Human friendly app name that appears in spec')
```

Example: https://github.com/sigopti/pyodhean-server/blob/master/pyodhean_server/app.py

It is hardcoded in my code, but I could use an envvar or a config param to change it. I don't have a strong objection to add this config option but I'm curious about the use case.

**Comment by playpauseandstop** [comment]
Wow.

I must say I’m surprised with your code. Surprised in a good way. To be honest, I’ve not used Flask at all for last 5 or 6 years, so my knowledge about the topic is a bit limited at a moment, but I never know that first parameter to `Flask` instance can be a human friendly name. I always thought about it as import name. I’ve searched [docs](https://flask.palletsprojects.com/en/1.1.x/api/#application-object) and couldn’t find example similar to what you have used as docs rather explain necessity to have first argument as valid import name, so thanks a lot for sharing that snippet with me.

With that in mind, I even don’t know whether my initial request is valid or not now, but as you don’t have anything against I still would like to provide support for `API_TITLE` config var. I will be able to come up with PR in couple of next days.

Thanks

**Comment by lafrech** [comment]
I'm afraid you're right and I've been misusing this parameter all along.

https://flask.palletsprojects.com/en/1.1.x/api/#application-object
https://stackoverflow.com/questions/31768371/how-to-understand-the-first-parameter-in-flask-instance-init

I guess I never went into trouble because I'm not using templates and static files in my APIs.

We need to add an `API_TITLE` config parameter indeed. PR absolutely welcome.

For the tests, you can modify `test_api_gets_apispec_parameters_from_app`.

-------------------------------------------------------------------------

We'll have to stop using app.name as title as it makes no sense.

We could make `API_TITLE` and `API_VERSION` mandatory. Version currently defaults to 1, which is totally arbitrary, and I can't think of a default that would make sense for title.

We also need to stop passing a human friendly name in init in the tests / examples / docs.

This should be done in another PR. It will be a breaking change.

Don't think like you have to do this. The first PR is nice already.

Thank you for your help.

**Comment by playpauseandstop** [comment]
Thanks for detailed response. I will try to provide the `API_TITLE` PR soon

**Comment by azzamsa** [comment]
I have the same issue. Patching the `title` in html templates is easy, but not appending `description`.

Other project had ability to pass "description" to swagger docs (e.g flasger, restplus).

IMHO, we can do the same by extending our simple `swagger-ui.html` template.

----

``` python
app = Flask(__name__)
api = Api(app, version='1.0', title='TodoMVC API',
    description='A simple TodoMVC API',
)
```

Customizable `description` like this would be very useful.

**Comment by playpauseandstop** [comment]
@azzamsa 

It is already possible to pass anything, such as description and other valid kwargs, to ApiSpec via `spec_kwargs`: https://flask-smorest.readthedocs.io/en/latest/api_reference.html#flask_smorest.Api

But current issue about the fact, that at a moment it is not able to pass custom title kwarg to ApiSpec, as it being overwritten by `self._app.name`: https://github.com/marshmallow-code/flask-smorest/blob/4b27aecf52b105657b0c8d4632712c642ec9ce7e/flask_smorest/spec/__init__.py#L151

**Comment by azzamsa** [comment]
I try to pass `description` as `api = Api(app, spec_kwargs={"description": "<p>foo</p>"})`.

it's appeared in `/api/openapi.json` but not in swagger-ui body, such this:

![image](https://user-images.githubusercontent.com/17734314/85698867-40512280-b705-11ea-923a-9a1f73c453be.png)

with the project I mentioned above, I can pass `description` to `Api` and it will appear such the image above.


---

this project https://github.com/fecgov/openFEC is using flask-apispec, and extending the swagger html https://github.com/fecgov/openFEC/blob/develop/webservices/templates/swagger-ui.html.

Maybe I will take this approach.

**Comment by playpauseandstop** [comment]
There is no such kwarg as description in `ApiSpec` and in OpenAPI 3 Schema itself. 

All you need to pass it under `info` dict,

```py
api = Api(
    app, 
    spec_kwargs={
        "info": {"description": "foo"}
    },
)
```

In total `spec_kwargs` is `options` passed on instatiating `ApiSpec` instance, https://apispec.readthedocs.io/en/latest/api_core.html#apispec.APISpec

Also you should pass description as Markdown and it will be rendered to HTML by Swagger UI or Redoc, https://spec.openapis.org/oas/v3.0.3#info-object

**Comment by azzamsa** [comment]
@playpauseandstop Wow, *TIL*. I've fight extending the templates for couple last hours.

Saved the day, thank you. I should read the [spec](https://spec.openapis.org/oas/v3.0.3#info-object) in the first place.

**Comment by lafrech** [comment]
@playpauseandstop, thanks for your work on this.

I just sent a PR (#169) based on yours (#165).

The plan is to merge it and issue a major release (v0.23).

Feedback welcome.

**Comment by playpauseandstop** [comment]
@lafrech 

Thanks for your update, #169 LGTM, closing my PR in favour of more complete implementation
