### ISSUE TITLE
Multiple Success Status Codes

### ISSUE THREAD

**Issue by benjamin-t-frost** [marshmallow-code/flask-smorest#166]
I think it would be super helpful to be able to document multiple successful status codes.

For example, 200 & 201 for a PUT request. 

I know in #44 you said that flask-smorest assumes that there will be only one successful status, but +1 requests for the feature ~

**Comment by lafrech** [comment]
The idea is that there is only one "normal" path, where `response` dumps the output with the schema and adds the code.

Calling the other response "error responses" is a bit improper. In practice, it can be a 304, for instance. Not really an error. More of an alternate response. #44 aims a documenting those alternate responses.

Please elaborate on your use case. Are you saying your view function may return the same information in the "normal" case, sometimes with 200, sometimes with 201?

**Comment by lafrech** [comment]
@benjamin-t-frost, please see the discussion in #163.

I'm wondering how `response` would discriminate your 200 and 201 responses. Does you view func add the status code to its return value?

**Comment by lafrech** [comment]
0.29.0 adds `Blueprint.alt_response` allowing to document alternative responses. Not sure it answers the need but closing anyway as is has been stale for a while. Feel free to comment if this is still an issue.

**Comment by BorjaEst** [comment]
Acording here:
[REST Api tutorial](https://www.restapitutorial.com/lessons/httpmethods.html) the method PUT might return 201 when new element is created or 204 when an existing is updated.

Therefore the correct way to handle this in the api would be:
```py
@blp.route('/<uuid:id>')
class Site(MethodView):
    @blp.arguments(schemas.SitesCreateArgs)
    @blp.response(201, schemas.Site)
    @blp.response(204)
    def put(self, args, id):
        """Updates (or creates) site."""
        site = models.Site.get_by_id(id)
        if site:
            site.update(**args) # <- No return value, no abort, 204 shoud be assumed
        else:
            return models.Site.create(id=id, **args) # <- return value, 201 should be assumed
```
Of course, currently **flask_smorest==0.29.0** is not possible.

Now the question would be how to differentiate between 200 and 201. 
Well I cannot think of an use case there.

**Comment by lafrech** [comment]
> REST Api tutorial the method PUT might return 201 when new element is created or 204 when an existing is updated.

More precisely

- 200: resource modified and sent back
- 204: resource modified and not sent back
- 201: resource created

I don't use PUT to create resources and I consistently send (or not) the content back in an app, so I never needed to allow both.

Current implementation is not blocking, just not as practical as one might wish.

Define a main case and use `response` for that. For the other cases, use `alt_response` and ensure the view func returns a response object.

Returning an empty response is easy, so I'd pick this for the "manual" case.

Now, if you want to manage both 200 and 201 with resource sent back, one of the case implies manual serialization, which is not ideal. I don't have a simple solution to this. Again, this has never been an issue to me, I use POST on the collection to create an item.

I'm not sure there's a theoretical solution to this.

Guessing the status code depending on the return value is something I'd rather not engage in. It might work with empty response vs. non-empty one, but there could be corner cases. And it is hard to generalize.
