### ISSUE TITLE
Best approach to pass context to Schema from MethodView

### ISSUE THREAD

**Issue by jamescw** [marshmallow-code/flask-smorest#168]
Hi there,

Firstly, just wanted to say this is an excellent framework, it was exactly what I was looking for (decorators to produce the spec) and I'm finding it a joy to use.

I had a scenario recently where I needed to pass some context to a Schema from the view handling the request, as documented in the Marshmallow docs [here](https://marshmallow.readthedocs.io/en/stable/custom_fields.html#adding-context-to-method-and-function-fields)

Since I usually define the schema as part of the response decorator, I couldn't think of a good way to pass the variable to Schema without creating the schema object in the view and dumping the object explicitly as per the below example:

```
@blp.route('/<string:upn>')
class UserByUPN(MethodView):

    @blp.etag
    @blp.arguments(AppArgsSchema, location='query')
    @blp.response()
    def get(self, args, upn=None):
        """Get User by UPN"""
        app_code = args.pop('app_code', None)
        user = User.query.filter_by(
            UserPrincipalName=upn
        ).first_or_404(
            description='User with UPN {} not found'.format(upn)
        )
        return UserSchema(context={'app_code': app_code}).dump(user)
```
While this works it means I am evaluating the collection and executing the DB request in the view and cannot chain an SQL pager easily without also implementing this in the view.

Any advice on how I should pass a local variable to a schema class without explicitly doing so in the view?

**Comment by lafrech** [comment]
Thanks for the kind words. Always nice to hear people find this lib useful. If you have projects using it that are visible somewhere, I'd be happy to know.

I'm not familiar with this marshmallow feature. I never used it. From the doc you point to, the context doesn't have to be passed at schema init.

Here's a draft for a solution that might work. It is absolutely untested, but hopefully it will put your on the right tracks.

Bascially, override `response` in a `Blueprint` like this:

```py
class MyBlueprint:
    def response(self, schema, *args, **kwargs):
        if isinstance(schema, type):
            schema = schema()

        decorator_orig = super().response(schema, *args, **kwargs)

        def decorator(func):

            func = decorator_orig(func)

            @wraps(func)
            def wrapper(*args, **kwargs):

                app_code = args.pop('app_code', None)
                schema.context = {'app_code': app_code}
                return func(*args, **kwargs))

            return wrapper

        return decorator
```

**Comment by lafrech** [comment]
Closing this for now.

Feel free to comment if you're still stuck there.
