### ISSUE TITLE
No support for passing options while registering blueprint

### ISSUE THREAD

**Issue by dryobates** [marshmallow-code/flask-smorest#17]
Problem: register_blueprint method in Api does not takes "options" argument and so it is impossible to pass options to blueprint.

Current Api.register_blueprint without options support:
https://github.com/Nobatek/flask-rest-api/blob/master/flask_rest_api/__init__.py#L62

Flask's register_blueprint documentation with mentioned "options": http://flask.pocoo.org/docs/1.0/api/?highlight=blueprint#flask.Flask.register_blueprint

Blueprint register documentation:
http://flask.pocoo.org/docs/1.0/api/?highlight=blueprint#flask.Blueprint.register

It would be helpful to be able to use "options".

**Comment by lafrech** [comment]
Good point. Fixed in master.

Thanks for reporting.

**Comment by lafrech** [comment]
Released in 0.9.2.
