### ISSUE TITLE
Ordering of URL arguments

### ISSUE THREAD

**Issue by AbdealiLoKo** [marshmallow-code/flask-smorest#181]
I'm not too clear on how I'm supposed to handle URL arguments with smorest.

I tried this:
```python
@blp.route('/<int:id>')
class Pet(MethodView):

    @blp.arguments(PetQueryArgsSchema, location='query')
    @blp.response(PetSchema)
    def get(self, id, args):
        return Pet.get(filters=args)
```
And it seems to give me the error: `TypeError: get() got multiple values for argument 'id'`
Which seems to indicate that my URL kwargs are not the first args that are defined ?
I see the docs describing that `blp.arguments` follows the order theya re defined in - https://flask-smorest.readthedocs.io/en/latest/arguments.html#arguments-injection
I didn't understand how it plays with my URL arguments.

What is the recommended way of defining them ?
`def get(self, args, id):`
or:
`def get(self, args, id=None):`
or:
`def get(self, args, *, id=None):`
or something else ?

Also, if I use the `as_kwargs=True` - what would be the recommended way to change the function signature ?

**Comment by lafrech** [comment]
`id` can't be `None`. It is positional and passed as last argument. It would be neater for the resource function signature if it was the first argument, but this logic lies in flask/werkzeug code and I don't think we can do much about it.

I'd write

```py
    def get(self, args, id):
```

When using `as_kwargs=True`, I'd write:

```py
    def get(self, id, **kwargs):
```

**Comment by AbdealiLoKo** [comment]
Thanks for the reply @lafrech 

The patterns I have in my current code (using flask-apispec's `@use_kwargs`) are the following:
 - `def get(self, id, **kwargs)`
 - `def get(self, id, with_extra_info=True, **kwargs)`
 - `def get(self, id, name, with_extra_info=True)`

When using `@use_kwargs` it was not respecting:
 - `default=` in my field - so, I use `with_extra_info=True` instead
 - `required=` in my fields - so, I use `name` (i.e. a arg) instead, so that it throws an error if the name was not provided.

I now realize that smorest handles both these cases using the marshmallow Schema directly. So, I don't need these workarounds.
Makes sense, and it is a lot clearner.

With arguments - I agree that it would be nicer to use `get(self, id, args)` instead of `get(self, args, id)`

**Comment by lafrech** [comment]
Good. Glad to see people can migrate from flask-apispec without too much trouble.

Can this be closed?

**Comment by AbdealiLoKo** [comment]
Yep, thanks
