### ISSUE TITLE
Disable automatic json response

### ISSUE THREAD

**Issue by ericsouza** [marshmallow-code/flask-smorest#184]
Hi. Is there any way to disable automatic json response of abort? 

I'm trying to use flask default abort to show my users that there is some missing parameters, but when I use something like:
```python
return abort(400, Response(jsonify({"code": 400, "message": "missing parameters"})))
```
I get this:
```javascript
{
  "code": 400,
  "status": "Bad Request"
}
```

And many thanks for this great extension!

**Comment by lafrech** [comment]
Hi.

You can write

```py
abort(400, message="missing parameters")  # typically string describing issue
```

or

```py
abort(400, errors={ ... dict of errors ... })  # typically dict of marshmallow validation errors
```

(You may use both `message` and `errors` in the same call.)

Would any of these fit your need?

**Comment by ericsouza** [comment]
I actually have to use abort from Flask because it can not depends on flask-smorest for this (archichecture requirements). 

Also this would be useful in applications where I have both API and visual interfaces.

**Comment by lafrech** [comment]
What about


```py
    return jsonify({"code": 400, "message": "missing parameters"}), 400
```

?

(When using `abort`, you shouldn't need to `return abort`, `abort` is enough.)

**Comment by ericsouza** [comment]
Many thanks!! It did the job.

But is there any plan of adding a setting to disable automatic json format in http exceptions? It would be nice for things like 404 error when users try to request a view endpoint that doesn't exist.

**Comment by lafrech** [comment]
I think this question overlaps with #174 (and #51).

It is not about disabling json response but ensuring it is only in API blueprints and not in other views. And about how to deal with the 404 case.

Let's close this and discuss it there.
