### ISSUE TITLE
How to add message parameters from abort methods to openapi doc?

### ISSUE THREAD

**Issue by hraffiest** [marshmallow-code/flask-smorest#185]
Hi! Thanks for answers. How can I add info about my abort methods to openapi doc that generated by smorest?
For example:
`abort(401, message='This is not ur profile!')`

**Comment by lafrech** [comment]
IIUC, your question is related to the discussion in #163.

**Comment by lafrech** [comment]
0.29.0 adds `Blueprint.alt_response` allowing to document alternative responses.

It is manual. It does not introspect abort calls.
