### ISSUE TITLE
Why can't I have multiple response codes in apispec?

### ISSUE THREAD

**Issue by estein9825** [marshmallow-code/flask-smorest#186]
Perhaps I'm doing this wrong, but even though my route has multiple `@blp.response` values and the actual calls return the correct information, but specs only show the top response and none of the error responses.

I have this:
```
    @blp.response(code=204, description="success")
    @blp.response(code=404, description="Failed updating shovel statuses")
    @blp.response(code=409, description="Database is empty or some shovel statuses requesting updates are missing.")
    @blp.response(code=500, description="Internal server error")
    def put(self, shovels):
```
And this is what I see swagger:

![image](https://user-images.githubusercontent.com/41277488/93821950-424b5480-fc14-11ea-82aa-c35f88de77fa.png)

Similarly, if I have a response(description='fine by me') above the 204 code, then I get the 200 error instead and don't see the 204 at all. I have a few cases where depending on the type of data requested, I would either return a 200 error or a 204 error, so I would like this type of granularity as well.

Again, am I doing something wrong? I'm using the latest version of flask-smorest: 0.24.1

I'm hoping I don't have to mess with @doc, but I will if someone can explain how I use it for multiple routes and functions.

Thanks

**Comment by estein9825** [comment]
I realize this duplicates other tickets. so I'm going to close it.

**Comment by BorjaEst** [comment]
> I realize this duplicates other tickets. so I'm going to close it.

Could you reference the "other tickets"?
I am interested on this property.

See #166
