### ISSUE TITLE
Add documentation for returning response bodies that do not match response schemas 

### ISSUE THREAD

**Issue by jeverick** [marshmallow-code/flask-smorest#198]
I recently learned that `flask_smorest.Blueprint.response` doesn't always enforce the schema. I'm told that this isn't a bug, but rather a workaround for documenting things that smorest doesn't yet support? 

I think it would be valuable to document this behaviour to avoid confusion and to ensure people don't mistakenly opt-out of the response serialization/validation on their responses.

Here's a fake example of what I mean:

```py
from flask import jsonify
from flask_smorest import Blueprint
from marshmallow import fields, Schema


# I have a schema as follows:
class MySchema(Schema):
    foo: fields.Str()


# and a route which should return a response serialized as my schema above
@Blueprint.route('/foo', methods=['GET'])
@Blueprint.response(MySchema)
def do_a_thing():
    # but I'm actually able to return something else that does not match the schema:
    return jsonify({'bar': 'baz'}, 200)
```

**Comment by lafrech** [comment]
> I recently learned that flask_smorest.Blueprint.response doesn't always enforce the schema. I'm told that this isn't a bug, but rather a workaround for documenting things that smorest doesn't yet support?

Sort of. Or the other way around.

flask-smorest allows returning a `Response` object, but in this case it can't do its serialization job. However, the user may (should) specify a schema describing the response, for documentation purpose.

Indeed this should be written in the docs.

**Comment by lafrech** [comment]
Docs updated.
