### ISSUE TITLE
[RFC] Make code argument first positional in @response

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/flask-smorest#199]
I opened #193 2 months ago but didn't get much feedback so I figured I'd open an RFC issue for more visibility.

Currently, status code defaults to 200, which is also Flask default.

```py
    def response(
            self, schema=None, *, code=200, description=None,
            example=None, examples=None, headers=None
    ):
```

The proposal is to make code mandatory and first positional arg.

```py
    def response(
            self, code, schema=None, *, description=None,
            example=None, examples=None, headers=None
    ):
```

The first motivation for this was to make the signature coherent with the long-awaited upcoming `alt_response` decorator (#159).

Obviously, this change breaks everyone's code, but it is at worst a tedious find'n replace, no feature broken.

Pros

- In line with alt_response decorator.
- Nicer visually to have all the codes and schemas aligned.
- No real reason to have 200 as default, apart from alignment with Flask. In my typical REST API resource, only 3 endpoints out of 5 return a 200.
- Make it explicit to the user that a code will be added to the response and which one.

Cons

- Need to specify 200 more than half of the time while it could be the default.
- Need to change existing codebases.

I'm leaning towards moving on with this, but I can allow a little bit more time for feedback before I do so. It is not so much about counting :+1: and :-1: than letting users express specific concerns I might have overlooked.

**Comment by lindycoder** [comment]
I'm okay if the contract changes, it's an easy search and replace.

BUT... Here's an idea, just a suggestion really:

I really like the flexibility this project and flask offers when returning values from a view using the `unpack_tuple_response`. Maybe this could inspire `@response` decorator.

## What if...
...the 2 first args were either code+Schema or only schema AND you can call response several time updating the doc/behaviour as it goes?

Defaults to 200
```
@api.response(Schema)
def endpoint()
```
uses 201
```
@api.response(201, Schema)
def endpoint()
```
First defaults to 200 second is for 404s could be based on werkzeug exceptions as you mentioned somewehre or match the returned code in the view
```
@api.response(Schema)
@api.response(400, SchemaFor400)
def endpoint()
```
Those would fail with a conflict exception
```
@api.response(Schema)
@api.response(OtherSchema)
def endpoint()

@api.response(Schema)
@api.response(200, OtherSchema)
def endpoint()

@api.response(200, Schema)
@api.response(OtherSchema)
def endpoint()
```

That would obviously require the decorator to get *args,**kwargs, thus obscuring the contract... but the usage *might* be fun and intuitive if properly document in the decorator's pydoc  (Always the first place i go for doc personally)

**Comment by lafrech** [comment]
> I'm okay if the contract changes, it's an easy search and replace.

Thanks. That's what I think but it's always nice to get user feedback.

> ...the 2 first args were either code+Schema or only schema

Regarding the multiple signature, I'm not sure the added flexibility (status code + schema or just schema) is worth the complication. At this point, I'd rather be explicit about the status code.

> you can call response several time updating the doc/behaviour as it goes?

This is not that easy for the reasons explained in https://github.com/marshmallow-code/flask-smorest/pull/163#issuecomment-651388788.

Since `response` will try to dump content with the schema (if a schema is provided), you can't call it twice unless you are sure that any alternative response will return an exception or a `Response` object AND the "normal" response is the decorator closest to the view function. This is a really ugly API and I'd rather have a distinct decorator for the "documentation only" case.

**Comment by Anti-Distinctlyminty** [comment]
As a new user, my instinct was that the `@response` decorator could be used multiple times to document possible responses in the openapi spec. flask-apispec has the `@marshal` decorator which performed a similar role, both documenting the response and dumping the content with a schema.
This may be my naivety showing, but isn't a lot of the complications arising from wanting to both document the response _and_ dump the result of the view function with the same decorator?

**Comment by lafrech** [comment]
Yes absolutely. But one of the primary goals of flask-smorest is to auto-document things. The main use case is using the decorator to dump the response and not worrying about the docs because it is automatic. Having to document the "normal" response with another decorator would require a lot of duplication.

**Comment by Anti-Distinctlyminty** [comment]
Yes, that was my instinct. In which case my vote is to just go ahead with this and `@alt_response`. The change is breaking, but minimal effort to fix, and I would greatly appreciate the ability to properly document all responses.

**Comment by lafrech** [comment]
Done.
