### ISSUE TITLE
Hide auto-added 422 response status schemas

### ISSUE THREAD

**Issue by SlimBeji** [marshmallow-code/flask-smorest#201]
Hello,

Thank you for your great work.

I have a small question/issue that I want to report. For a given endpoint when I use this line:
```
@my_blueprint.arguments(podcast_query_params_schema, location="path", as_kwargs=True)
```
In APISpec, it automatically adds the 422 response status. I found this in my case to be redundant because the response schemas is exactly the same as the default error response. So in redoc, I ended up with two identical schemas for the same endpoint:
- 422 unprocessable entity
- default Default error response

Is there a way to hide the 422 response as the exact same information can be found in in the default error response.

After quickly checking https://github.com/marshmallow-code/flask-smorest/blob/master/flask_smorest/arguments.py, I think adding a keyword argument like hide_422_shcemas to the ```arguments``` decorator and nesting 
```
docs.setdefault('responses', {})[
                error_status_code
            ] = http.HTTPStatus(error_status_code).name
```
in an if statement might solve the issue.

**Comment by lafrech** [comment]
With #209 merged, 0.28.0 allows to opt-out of the feature adding default error response.

I don't think it is an issue to define 422 even if it conforms to the default response. In fact, by default, all responses conform to the same schema, but I still think it is nice to mention them explicitly, not so much for the structure (since it is always the same) but to inform the client those errors are to be expected.

**Comment by lafrech** [comment]
Closing this for now. Feel free to comment if current behaviour is not satisifying.

**Comment by arabnejad** [comment]
Hi @lafrech 
is there anyway to hide `422` globally  for all routes as we can do it for `DEFAULT_ERROR_RESPONSE_NAME` ?

**Comment by lafrech** [comment]
No, there is no such parameter. It could be achieved in user code if someone really wants to do it, but I don't get the point. What's wrong with documenting this 422 response?

**Comment by arabnejad** [comment]
Hi @lafrech 
in my opinion, the documentation should be aligned with developer definitions, so if I did not provide a response body for a 422 error, it should not be appeared in the documentation side :grin:
I could fixed this, but it would be better we don't have a such default assumption here (as you did it before for default error response and added an option to disable it)  just a suggestion

**Comment by lafrech** [comment]
The rationale here is that flask-smorest does provide a default 422 error management so unless you modified that by overriding stuff, your API returns the default error payload defined in flask-smorest and documenting it as such in every resource expecting parameters is the right thing to do IMHO.
