### ISSUE TITLE
Unreferenced responses appear in resulting OpenApi JSON

### ISSUE THREAD

**Issue by lindycoder** [marshmallow-code/flask-smorest#206]
Hello!

I'm moving here from flask-rest-api and when rendering the my open api JSON file using the endpoint, i now have a LOT of responses... all possible ones if I believe the code.
All my endpoints are only referencing
```
#/responses/UNPROCESSABLE_ENTITY
#/responses/DEFAULT_ERROR
```
Added by flask-smorest it self.

Why would there be more than those 2 response in my /openapi.json output?

My versions, currently rendering with OPENAPI_VERSION=2.0
```
flask-smorest==0.26.0
apispec==4.0.0
marshmallow==3.10.0
``` 

Thank you!

**Comment by lafrech** [comment]
Yeah, this is known behaviour. Not really intended, but I couldn't come up with a simple way to have responses added on-the-fly.

Having unreferenced components doesn't hurt. AFAIK, it does not make the spec invalid. But I admit it sucks, especially when one wants to create a minimal example spec.

I won't consider it a bug, but if someone has an idea, I'm all ears.

**Comment by lindycoder** [comment]
I agree it doesn't hurt, but not as pretty :)

You can mark this as an enhancement, i'll check if I can make a proposition.

Thank you for your fast response!
