### ISSUE TITLE
Error handler for 404?

### ISSUE THREAD

**Issue by terabyte128** [marshmallow-code/flask-smorest#207]
Is there a way to tell flask-smorest to generate a 404 response in the OpenAPI spec, for example, if the ID in the URL is not found?

e.g., GET /thing/<thing_id>

where thing_id doesn't exist, the generated documentation should specifically have a 404 response.

**Comment by lafrech** [comment]
If I understand correctly what you want to achieve, this should be possible once #159 is merged.

**Comment by lafrech** [comment]
0.29.0 adds `Blueprint.alt_response` allowing to document alternative responses.

The process is manual, there is no auto-documentation of 404 errors.
