### ISSUE TITLE
Enhancement: Disable adding default_error to all responses

### ISSUE THREAD

**Issue by lindycoder** [marshmallow-code/flask-smorest#209]
Hello! :)

So right now as soon as a `@blp.response()` is specified, a `default` response is added to cover all uncovered responses code.

The personal issue i have with this is that i may not be documenting all responses, such as unexpected 500s and if they happens, there's no way they will respect the default schema, which is not at all enforced anyway.

So I would rather not have this ambiguous claim that my responses respect this schema.

On a related note, if an endpoint only has `@blp.arguments()` and no `@blp.response()`, the default is not added, which in this case is probably a bug if the default is always expected to be there.

I suggest a flag to make adding default error response optional.

This may relate to #201

What do you think?

**Comment by SlimBeji** [comment]
yes, this would also solve #201
