### ISSUE TITLE
TimeDelta fields not generating useful documentation

### ISSUE THREAD

**Issue by camercu** [marshmallow-code/flask-smorest#216]
Documentation for `marshmallow.fields.TimeDelta` is not capturing anything about the field type except the description. Under the hood, Marshmallow treats it as an `int` that gets converted to a `datetime.timedelta` on deserialization.

Here is the line from the schema declaration:
```py
    uptime = fields.TimeDelta(precision="minutes", required=False, metadata={"description":"running time"})
```

Example output of "uptime" field (type TimeDelta) from openapi.json generated by flask-smorest:
```json
{
  "uptime": {
    "description": "running time"
  }
}
```

And here is a screen grab of the Swagger UI:
![Capture](https://user-images.githubusercontent.com/6279092/105771793-21cb3800-5f2f-11eb-8b77-e5ad9a2f03ae.PNG)

I think it should be treated as an number, with the precision string spelled out in the documentation. Is there a way to add this?

**Comment by lafrech** [comment]
I transfered this to apispec (https://github.com/marshmallow-code/apispec/issues/631) but it looks like the transfer was only half-successful.

Anyway, discussions about this should happen there.

**Comment by lafrech** [comment]
Support for `TimeDelta` was added to apispec 4.6.0.
