### ISSUE TITLE
Configuring behaviour for unknown fields

### ISSUE THREAD

**Issue by pmdarrow** [marshmallow-code/flask-smorest#218]
I've been upgrading my project to the latest dependences (webargs 7, marshmallow 3, etc.). One of the issues I'm running into is that I want to maintain marshmallow 2.x behaviour when it comes to unknown fields (i.e. `EXCLUDE`). None of the settings shown in https://marshmallow.readthedocs.io/en/stable/quickstart.html#handling-unknown-fields are respected because webargs overrides them with its own defaults apparently. It would nice to be able to configure this setting globally as we want to maintain API backward compatibility and don't see any need to introduce the new webargs default which is `RAISE`.

Do you think flask-smorest could expose a way to configure this globally?

**Comment by lafrech** [comment]
I updated the docs about this just recently: https://flask-smorest.readthedocs.io/en/latest/arguments.html#dealing-with-unknown-arguments.

Please try to

- use a base schema class with `unknown = ma.EXCLUDE`
- set `DEFAULT_UNKNOWN_BY_LOCATION = None` in the parser (see docs) to inhibit webargs and use schema-defined behaviour

**Comment by pmdarrow** [comment]
I ended up doing the latter:

```py
from flask_smorest import Blueprint as SmorestBlueprint
from webargs.flaskparser import FlaskParser
from marshmallow import EXCLUDE

class Blueprint(SmorestBlueprint):
    ARGUMENTS_PARSER = FlaskParser(unknown=EXCLUDE)
```

But using a base class with `class Meta: unknown = ma.EXCLUDE` doesn't work unfortunately. Webargs overrides this by passing in `unknown` explicitly.

**Comment by pmdarrow** [comment]
Ah, your solution might be a bit nicer - I'll probably roll with this one!

```py
import marshmallow as ma
from webargs.flaskparser import FlaskParser

FlaskParser.DEFAULT_UNKNOWN_BY_LOCATION["json"] = ma.EXCLUDE
```

**Comment by lafrech** [comment]
You must also set a base schema class with `EXCLUDE` because the value set by webargs doesn't propagate to nested schemas.

Long story: https://github.com/marshmallow-code/webargs/issues/580.

I should provide useful examples in the docs. Like how to get ma3 + webargs 6 behaviour, or ma2 behaviour.

**Comment by pmdarrow** [comment]
Once I knew what was going on (webargs clobbering my settings) it was any easy fix, but I was just so confused why my marshmallow settings weren't working. I think the docs you added are enough!
