### ISSUE TITLE
Fail to register blueprint

### ISSUE THREAD

**Issue by ChenHaolinOlym** [marshmallow-code/flask-smorest#224]
I want to use init_app to initialize the application and I want to put all my api part of code into a separate .py file.
So I do something below:
interface.py:
```
from flask_smorest import Api
api = Api()
blp=Blueprint()
# Some settings
api.register_blueprint(blp)
```
\_\_init\_\_.py
```
from .interface import api
def create_app():
    app=Flask(__name__)
    api.init_app(app)
```
I would get an error:
AttributeError: 'NoneType' object has no attribute 'register_blueprint'
This is because I register blueprint before I init_app
I really want to organize my code like this so can flask-smorest support this?

**Comment by lafrech** [comment]
Blueprints must be registered after app init (because the process depends on app parameters like OpenAPI version for the docs).

```py
from flask_smorest import Api
api = Api()
blp=Blueprint()
# Some settings
def register_blueprints():
    api.register_blueprint(blp)
```

```py
from .interface import api, register_blueprints
def create_app():
    app=Flask(__name__)
    api.init_app(app)
    register_blueprints()
```

**Comment by ChenHaolinOlym** [comment]
Thanks for your help
