### ISSUE TITLE
Docs: inaccurate claim on schema field ordering

### ISSUE THREAD

**Issue by mjpieters** [marshmallow-code/flask-smorest#228]
The [documentation](https://flask-smorest.readthedocs.io/en/latest/openapi.html#enforce-order-in-openapi-specification-file) states you don't need to set `ordered = True` on a schema when using CPython 3.6+. Unfortunately that's currently not true, as the Marshmallow [`Schema._init_fields()` implementation](https://github.com/marshmallow-code/marshmallow/blob/324766619c885965c9f850c4034efe1855d28b3c/src/marshmallow/schema.py#L947-L1020) relies on _sets_, not dictionaries, to select fields. The [default set implementation used](https://github.com/marshmallow-code/marshmallow/blob/324766619c885965c9f850c4034efe1855d28b3c/src/marshmallow/schema.py#L417-L419) is the Python stdlib `set` type, which does not preserve insertion order.

This is why the following example, on Python 3.9, lists fields in a different order from that used by the schema class:

```python
>>> import sys
>>> from marshmallow import Schema, fields
>>> class FooSchema(Schema):
...     bar = fields.String()
...     spam = fields.Int()
...     ham = fields.Boolean()
...
>>> sys.version_info
sys.version_info(major=3, minor=9, micro=0, releaselevel='final', serial=0)
>>> list(FooSchema().fields)
['spam', 'ham', 'bar']
```

which makes the claim in the docs that *passing ordered Meta attribute is not necessary when using a Python version for which dictionaries are always ordered (>= 3.7 or CPython 3.6)* incorrect. 

I've taken to create a custom base class that sets `set_class` to `OrderedSet`:

```python
>>> from marshmallow.orderedset import OrderedSet
>>> class OrderedBaseSchema(Schema):
...     set_class = OrderedSet
...
>>> class FooSchemaOrdered(OrderedBaseSchema):
...     bar = fields.String()
...     spam = fields.Int()
...     ham = fields.Boolean()
...
>>> list(FooSchemaOrdered().fields)
['bar', 'spam', 'ham']
```

This is sufficient to retain field ordering for Python versions with the new insertion-order-preserving dict implementation.

**Comment by lafrech** [comment]
Wow. First of all, as a SO user, I must say that I'm honored to get an issue from @mjpieters himself.

Thanks for the report. Sorry you went through this. I did realize this while working on umongo (see https://github.com/Scille/umongo/issues/55#issuecomment-740060173) but I totally forgot about that note in the docs.

I agree about removing the note.

As you found out, when using Python 3.7+, making a schema ordered is just about using an `OrderedSet` as set class.

As I wrote in the comment linked above, I'm wondering if we should make all schemas ordered by default in marshmallow 4 when dropping Python < 3.7, assuming the penalty introduced by the ordered set would be minimal. I don't know enough about performance to tell if the impact would be negligible. Also, `OrderedDict` still exist for a reason so perhaps it makes sense to use them in this context even if normal `dict`s preserve order.

**Comment by mjpieters** [comment]
:-) I'd say that a discussion on making schemas ordered by default belongs in the Marshmallow repo ;-)

But, without having given it too much thought I think there are two different use-cases to consider:

- Schema introspection
- Deserialisation

For Flask-Smorest's OpenAPI generator, you care about order preservation only when introspecting the schema, and for that use-case the stdlib dict is more than sufficient. But for deserialisation, you _may_ care about receiving OrderedDict instances instead of dict objects, because the latter support more operations (such as reordering and order-sensitive equality testing).

I need ordered field introspection a lot more often than ordered deserialisation, to be honest, and I'd love to see Marshmallow make introspection a first-class use case, and _then_ perhaps consider preserving field definition order by default￼￼ as a priority. But do keep the option to deserialise to OrderedDict, that use-case doesn't go away even if you only support 3.7 and up.

**Comment by lafrech** [comment]
> I'd say that a discussion on making schemas ordered by default belongs in the Marshmallow repo

Yes, absolutely. I've been meaning to discuss it there but figured this would only be for marshmallow 4. Now I'm thinking perhaps we could change the set class in a 3.x release.

I opened an RFC in marshmallow repo: https://github.com/marshmallow-code/marshmallow/issues/1744.
