### ISSUE TITLE
[Question] Additional section in documentation

### ISSUE THREAD

**Issue by TitaniumHocker** [marshmallow-code/flask-smorest#230]
**Wazzup!**

First of all, thank you guys for maintaining this awesome software.
I think this package is the best choice for creating well-validated and auto-documented web API using Flask.

Right now I'm working on application that uses [flask-security](https://github.com/Flask-Middleware/flask-security/) and I want to add additional section to documentation with information about authentication. I don't want full api documentation, just simple paragraph this some instructions and links to flask-security documentation.

So, is there any "easy" way to add something like that to documentation?

**Comment by lafrech** [comment]
Thanks for the kind words.

If you don't want to document authentication using `securitySchemes`, you may set a long text in the info -> description section.

The spec says it should be a short description of the API (https://swagger.io/specification/#infoObject) but nothing prevents you from making it longer.

Pass

```py
spec_kwargs={
    'info': {
        'description': """Put your long description here"""
    }
}
```

Here's a real-life example:

- code: https://github.com/HumanBrainProject/cortical-voluba/blob/8e397f95c49a2b9b64c5f03a394a8823ac2ae5a9/cortical_voluba/__init__.py#L191
- API doc: https://cortical-voluba.apps-dev.hbp.eu/redoc

**Comment by TitaniumHocker** [comment]
Thank you for help, I think I'll use both of them.
