### ISSUE TITLE
304 wrongly documented as following ErrorSchema

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/flask-smorest#233]
Automatic doc says 304 comes with a JSON payload. This is not true.

From https://httpstatuses.com/304:

> A 304 response cannot contain a message-body; it is always terminated by the first empty line after the header fields.

Flask/werkzeug respect that and 304 responses have an empty body.

Autodoc should be fixed.

We should clarify first which codes are concerned. There could be more than just 304 concerned.

Also, when `NotModified` is raised, we go through the error handler. This is useless since the payload is trashed. I don't think we should worry about that.

**Comment by lafrech** [comment]
From a quick test, among all the status code from `HTTPStatus`, the ones for which the payload is missing are 100, 101, 102, 204 and 304. For all of these codes, the payload should be documented as empty in the spec (if documented at all).

This happens in Werkzeug, in `response.get_app_iter`:

https://github.com/pallets/werkzeug/blob/84b2b88a22d609283ae1d7abc03f71e20ebedf40/src/werkzeug/wrappers/response.py#L569-L596

```py
        if (
            environ["REQUEST_METHOD"] == "HEAD"
            or 100 <= status < 200
            or status in (204, 304)
        ):
            iterable: t.Iterable[bytes] = ()
```

We can't import the list from there (there's no `EMPTY_RESPONSE_STATUS_CODES` constant), so we'll have to duplicate it here.

(Also, current 304 implementation lacks headers that must be generated according to the spec: https://httpstatuses.com/304.)

**Comment by TimDiekmann** [comment]
Locally I fixed this by simply overwriting `ResponseReferencesPlugin::_available_responses`:

```python
class ResponseReferencesPlugin(flask_smorest.spec.plugins.ResponseReferencesPlugin):
    def _available_responses(self):
        specs = super()._available_responses()
        del specs['NOT_MODIFIED']['schema']
        return specs
```

Maybe you want to add this (and the other codes) to the Plugin?
