### ISSUE TITLE
Documentation: Wrong decorator mentinoned for alternate responses

### ISSUE THREAD

**Issue by neumantm** [marshmallow-code/flask-smorest#235]
In the documentation under [Documenting Alternative Responses](https://flask-smorest.readthedocs.io/en/latest/response.html#documenting-alternative-responses) in the first sentence of the second paragraph the `Blueprint.response` is mentioned, when I think the `Blueprint.alt_response` should actually be mentioned.

See also https://github.com/marshmallow-code/flask-smorest/pull/159/files#r580418828

**Comment by lafrech** [comment]
Thanks.

Fixed in master.
