### ISSUE TITLE
Kwargs typing in docstrings

### ISSUE THREAD

**Issue by sethkaufee** [marshmallow-code/flask-smorest#240]
Very minor but `kwargs` shouldn't be typed as a `dict` in docstrings or with the typing module.

**Comment by lafrech** [comment]
I think I already investigated this and I can't remember what came out of it.

What should it be?

I can't be the type of the values since they may have different types.

Should I just put nothing for a type?

**Comment by sethkaufee** [comment]
Sorry I closed the issue in accident! 

Either nothing or use a union of all the possible types. [PEP’s example](https://www.python.org/dev/peps/pep-0484/#arbitrary-argument-lists-and-default-argument-values) shows lists of args/kwargs. Python 3.10 is suppose to be adding `ParamSpec` to make this a little more straightforward.

**Comment by lafrech** [comment]
Fixed in 2c803a5.

Thanks for reporting.
