### ISSUE TITLE
Flask 2 / Werkzeug 2 support

### ISSUE THREAD

**Issue by AbdealiLoKo** [marshmallow-code/flask-smorest#244]
https://pypi.org/project/Flask/2.0.0/
https://pypi.org/project/Werkzeug/2.0.0/

Smorest is locking the version to `<2` - would be good to check if it can be upgraded as these have been released now

**Comment by lafrech** [comment]
#243

**Comment by AbdealiLoKo** [comment]
Ah - thanks. I only checked Issues and not PRs :(

**Comment by lafrech** [comment]
Closed by #243.
