### ISSUE TITLE
Route parameter openapi generation is incompatible with 3.0

### ISSUE THREAD

**Issue by zedrdave** [marshmallow-code/flask-smorest#25]
When using a parameter in a route: `@bp.route('/<string:foo_id>')`

The openapi.json generated is not compatible with openapi 3.0:

```
"parameters": [
          {
            "in": "path",
            "name": "foo_id",
            "required": true,
            "type": "string"
          }
        ]
```

should be:

```
"parameters": [
          {
            "in": "path",
            "name": "bar_id",
            "required": true,
            "schema": {
                 "type": "string"
            }
          }
        ]
```

I am not sure if this is a flask-rest-api issue, or something to fix in a dependency… But I would be happy to take  stab at a PR, if pointed in the right direction (I couldn't figure where in `blueprint.py` that part of the doc was generated).

**Comment by lafrech** [comment]
Hi. Thanks for reporting. I pushed the fix for this 2 hours ago: https://github.com/Nobatek/flask-rest-api/commit/655e3f0970e8bedb7e78620aa5fd94cac225c73e.

Would you like to try that before I release?

**Comment by zedrdave** [comment]
Ha. What a coincidence! Sorry I wasn't around yesterday: I'll be happy to try it from github now, or confirm it works from the release.

**Comment by lafrech** [comment]
Fix released !
