### ISSUE TITLE
Api response enveloping

### ISSUE THREAD

**Issue by euseand** [marshmallow-code/flask-smorest#250]
Is there any obvious way to envelope the response data and make changes visible in docs?

**Comment by lafrech** [comment]
Not sure we can call this obvious, but IIUC, this example illustrates (and tests) what you want to achieve:

https://github.com/marshmallow-code/flask-smorest/blob/59a3a3be8f192a04f5dd2497b482d1bb06cec664/tests/test_examples.py#L421-L474

**Comment by euseand** [comment]
Thank you, it's quite enough for my needs.
