### ISSUE TITLE
Example of serializing a SQLAlchemy query result consisting of several Model objects

### ISSUE THREAD

**Issue by Amitg1** [marshmallow-code/flask-smorest#251]
Hi,

How do i implement this:
https://github.com/marshmallow-code/marshmallow-sqlalchemy/issues/56
using smorest?

Thanks!

**Comment by lafrech** [comment]
Not sure exactly what the question is.

Does this example app help: https://github.com/lafrech/flask-smorest-sqlalchemy-example ?
