### ISSUE TITLE
How to Pass Nested Schema/Object

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [marshmallow-code/flask-smorest#253]
If I have a schema containing another nested nested like so

```python
class AOVSchema(Schema):
    type = fields.String()
    name = fields.String()

class OutputSchema(Schema):
   aovs = fields.Nested(AOVSchema, descriptions="The aovs to output", many=True)
```

And I use the generated OpenAPI docs to perform a PUT request, 
![image](https://user-images.githubusercontent.com/1378483/121751844-40f9e900-cb0f-11eb-850b-6c07e80e5087.png)

I always end up with something like 
```{
  "code": 422,
  "status": "Unprocessable Entity",
  "errors": {
    "query": {
      "aovs": [
        "Invalid type."
      ]
    }
  }
}```

No matter what I try, I can never successfully send parameters to a nested parameter. My usual method is to then just treat the field as a string and do `simplejson.loads()`, but it feels to have to do it that way,

How do I properly submit information to a nested field?

**Comment by ddorian** [comment]
What about using:

```
   aovs = fields.List(fields.Nested(AOVSchema), descriptions="The aovs to output")
```

**Comment by Anti-Distinctlyminty** [comment]
Practically the same result
```
{
  "code": 422,
  "status": "Unprocessable Entity",
  "errors": {
    "query": {
      "aovs": {
        "0": {
          "_schema": [
            "Invalid input type."
          ]
        }
      }
    }
  }
}```

**Comment by lafrech** [comment]
Nesting stuff in query args is not obvious.

Try this custom parser: https://webargs.readthedocs.io/en/latest/advanced.html#custom-parsers.

**Comment by Anti-Distinctlyminty** [comment]
Any chance of an example? I'm really not sure how the `webargs.FlaskParser` can be used in my situation.

**Comment by zedrdave** [comment]
Any chance we could add support for this in flask-smorest? At least for first level nesting…

**Comment by lafrech** [comment]
For the record, the custom parser I mentioned above can be used like this:

```py
# Copied from webargs advanced usage custom parsers
# https://webargs.readthedocs.io/en/latest/advanced.html#custom-parsers
def _structure_dict(dict_):
    def structure_dict_pair(r, key, value):
        match = re.match(r'(\w+)\.(.*)', key)
        if match:
            if r.get(match.group(1)) is None:
                r[match.group(1)] = {}
            structure_dict_pair(r[match.group(1)], match.group(2), value)
        else:
            r[key] = value
    ret = {}
    for key, val in dict_.items():
        structure_dict_pair(ret, key, val)
    return ret


class CustomFlaskParser(webargs.flaskparser.FlaskParser):
    """Parses nested query args

    This parser handles nested query args. It expects nested levels
    delimited by a period and then deserializes the query args into a
    nested dict.

    For example, the URL query params `?name.first=John&name.last=Boone`
    will yield the following dict:

        {
            'name': {
                'first': 'John',
                'last': 'Boone',
            }
        }
    """
    def load_querystring(self, req, schema):
        return _structure_dict(req.args)


class Blueprint(flask_smorest.Blueprint):

    ARGUMENTS_PARSER = CustomFlaskParser()
```

-------------------------------------------------------------------------

I pointed you there because it deals with nested query args.

Now, I'm realizing it does not answer your need but you didn't provide any example of the query args you're expecting.

The thing is, as far as I know, there is no standard about passing nested stuff as query arguments. See [this SO answer by a Flask developer](https://stackoverflow.com/a/29036848/4653485) for instance. The custom parser above assumes dotted syntax.

**Comment by lafrech** [comment]
It's unclear to me what flask-smorest could do because there is no standard about passing nested query args.

Feel free to comment with more details and we can reopen.
