### ISSUE TITLE
Allow alt_response to specify the response is a "success" response

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/flask-smorest#256]
From https://github.com/marshmallow-code/flask-smorest/pull/254#discussion_r651548438.

> The ETag header is correctly documented only if `@blp.response` is used because otherwise there's no way to tell which status code corresponds to the "normal" path.
>
> If the user doesn't use `@blp.response`, because he creates the response manually, the ETag header can't be auto-documented.
> 
> This is a case where the user should use `@blp.alt_response`. Perhaps I could make this clearer in the docs: `@blp.alt_response` is not only for responses that are not the "normal flow" (like exceptions,...) but also responses that are returned as `Response` object thus requiring no serialization work from flask-smorest. Anyway, we could add an argument to allow the user to specify that an "alt_response" is in fact a "success" one.
> 
> Thinking of it, there may be several "success" responses. The point is that we exit the view function without exception and go through the decorator wrappers. Perhaps the whole "success" thing should be redesigned. At least we could change it to be a list of "successful status codes", meaning "non aborted responses". And perhaps the argument to `@blp.alt_response` could be `aborted` or `exception`, defaulting to `True`.
> 
> I need to think this through. Feedback about the feature and argument name ideas welcome.

**Comment by TimDiekmann** [comment]
As `alt_response` does not require serialization work, an ETag can't be created with the `@etag` decorator, but the user could set it, right? Instead of marking the alt response as a success, may it would be useful to add a field to the documentation meta `document_etag` (or `doc_etag_header` or similar) which then will be used for generating the respectively headers. `alt_response` could then take a parameter `document_etag=False` and `response` could take `document_etag=True`.

**Comment by lafrech** [comment]
> As alt_response does not require serialization work, an ETag can't be created with the @etag decorator, but the user could set it, right?

Yes, in any case, the user can always set the ETag manually.

> Instead of marking the alt response as a success, may it would be useful to add a field to the documentation meta document_etag...

We could do that but the flag/tag/info I have in mind would be more generic and could be helpful for other features (pagination, for instance). Practically, it would mean: this response happens when we get out of the view function without breaking the flow with an exception/abort. So any decorator that does stuff after the function (ETag, pagination, any custom decorator) would know it should document that response code as well.

Hence the "success" flag. It is not properly document yet. In fact, the procedure to document custom decorators is not properly documented. Currently, users must copy existing decorators. It should be possible to provide a better API, here. [FlaskAPI](https://github.com/greyli/apiflask/blob/d88f90c10658ce6e3f8a527c2c1c1e4a4a914c62/src/apiflask/decorators.py#L51) and flask-apispec use the term "annotate". This might refer to a design pattern I don't know about. Anyway, we could expose a method rather than let users access an underscored attribute in their subclass.
