### ISSUE TITLE
Simplest app with Swagger UI

### ISSUE THREAD

**Issue by mekanix** [marshmallow-code/flask-smorest#26]
I can't make my app have the Swagger route. This is the simplest app with PeeWee I came up with:

```py
import marshmallow as ma
from flask import Flask
from flask.views import MethodView
from flask_rest_api import Api, Blueprint
from peewee import TextField
from playhouse.flask_utils import FlaskDB


class Config:
    DATABASE = {
        'name': 'database.db',
        'engine': 'SqliteDatabase',
    }
    OPENAPI_URL_PREFIX = '/doc'
    OPENAPI_REDOC_PATH = '/redoc'
    OPENAPI_SWAGGER_UI_PATH = '/swagger'
    OPENAPI_SWAGGER_URL = '/swagger'
    API_SPEC_OPTIONS = {'x-internal-id': '2'}


class MyDB(FlaskDB):
    def connect_db(self):
        if self.database.is_closed():
            super(MyDB, self).connect_db()


app = Flask('My API')
app.config.from_object(Config)
api = Api(app)
db = MyDB(app)


class Pet(db.Model):
    name = TextField(unique=True)


db.database.create_tables([Pet])

pet = Pet(name='cici')
try:
    pet.save()
except:
    pass


#  @api.definition('Pet')
class PetSchema(ma.Schema):
    class Meta:
        strict = True
        ordered = True

    id = ma.fields.Int(dump_only=True)
    name = ma.fields.String()


blp = Blueprint(
    'pets',
    'pets',
    url_prefix='/pets',
    description='Operations on pets'
)


@blp.route('/')
class Pets(MethodView):
    @blp.response(PetSchema(many=True))
    def get(self):
        """List pets"""
        return Pet.select()


api.register_blueprint(blp)

if __name__ == '__main__':
    app.run()

```
These are the routes:
```
flask routes
Endpoint                Methods  Rule
----------------------  -------  -----------------------
api-docs.openapi_json   GET      /doc/openapi.json
api-docs.openapi_redoc  GET      /doc/redoc
pets.Pets               GET      /pets/
static                  GET      /static/<path:filename>
```
How can I enable Swagger UI?

**Comment by lafrech** [comment]
My bad, I made a typo in the docs. Sorry about that.

It should read `OPENAPI_SWAGGER_UI_URL`, not `OPENAPI_SWAGGER_URL`.

I just fixed it in master.

Note that this should be an URL to a directory containing Swagger UI scripts. You should use this if you want to use a specific host, or host those files locally, rather than use a CDN.

**Comment by mekanix** [comment]
Just changing the var name didn't produce any difference. As I'm sure I'm not the only one confused by how to get Swagger UI, can you provide some simple example in the docs, please?

**Comment by lafrech** [comment]
There was an issue in the code when using `OPENAPI_SWAGGER_UI_URL`. It is fixed in master.

Note that this parameter is meant to pass an URL to a directory where the Swagger UI scripts can be found. The value you're passing is wrong because it does not end with a `/` and I suspect you don't really mean to use a relative URL. If you do, then that's fine. But you still need the trailing slash. You can check what is produced in the generated html when accessing the doc page at the path you provided.

I don't have time right now to add complete examples to the docs, but here's a sample with the docs working:

```py
import marshmallow as ma
from flask import Flask
from flask.views import MethodView
from flask_rest_api import Api, Blueprint


class Config:
    OPENAPI_URL_PREFIX = '/doc'
    OPENAPI_REDOC_PATH = '/redoc'
    OPENAPI_SWAGGER_UI_PATH = '/swagger'
    # The following is equivalent to OPENAPI_SWAGGER_UI_VERSION = '3.19.5'
    OPENAPI_SWAGGER_UI_URL = 'https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/3.19.5/'


app = Flask('My API')
app.config.from_object(Config)
api = Api(app)


@api.definition('Pet')
class PetSchema(ma.Schema):
    class Meta:
        strict = True
        ordered = True

    id = ma.fields.Int(dump_only=True)
    name = ma.fields.String()


blp = Blueprint(
    'pets',
    'pets',
    url_prefix='/pets',
    description='Operations on pets'
)


@blp.route('/')
class Pets(MethodView):
    @blp.response(PetSchema(many=True))
    def get(self):
        """List pets"""
        # TODO
        # return Pet.select()


api.register_blueprint(blp)

if __name__ == '__main__':
    app.run()
```

**Comment by lafrech** [comment]
Fix released !

I hope the example above helps. Please comment if you're still stuck with this.

**Comment by maglfmn** [comment]
@lafrech In your [example above](https://github.com/Nobatek/flask-rest-api/issues/26#issuecomment-440032096), what is the URL that you'll request in your browser? I too am having a bit of difficulty understanding where to put the `.doc(..)` decorator and how I can then access the Swagger UI.

**Comment by lafrech** [comment]
In the example above:

```
/doc/openapi.json  # Raw json spec
/doc/redoc  # Redoc page
/doc/swagger  # Swagger page
```

Thinking of it, the naming mixes `PATH` and `URL` in a not so consistent way.

The @doc decorator is unrelated. It is meant to pass additional doc, everything that can't be inferred from the doc, either because flask-rest-api can't guess it, or because it is lacking the feature to do so.

**Comment by irufus** [comment]
@lafrech ~I only get 404s when specifying a path for swagger.~

Nevermind.  Could you update your reference docs to say:

> Defines the base path for both the JSON file, Redoc and Swagger UIs. If None, the documentation is not served and the following parameters are ignored.

And give examples in the Swagger and ReDoc sections that show what the full path could be once set in config.

**Comment by lafrech** [comment]
Let's reopen to

- [ ] improve docs
- [ ] add full examples

**Comment by Dridou** [comment]
I also had some problems to get swagger with smorest, but here is some tips that I can provide.

- `OPENAPI_URL_PREFIX` is the prefix of your url path
then you need to configure your `OPENAPI_SWAGGER_UI_PATH` which will be your final endpoint

- `OPENAPI_SWAGGER_UI_URL` is the url where flask smorest can find js scripts (if you have a blank page when loading your endpoint that's probably because it cannot find scripts), you either have them locally or online

- `OPENAPI_SWAGGER_UI_VERSION` you also need to set it (just to be sure it has every settings) to the same version of your `OPENAPI_SWAGGER_UI_URL`

Here is an example of configuration

```
app.config["OPENAPI_URL_PREFIX"] = "/api"
app.config["OPENAPI_SWAGGER_UI_PATH"] = "/api_swagger_path"
app.config["OPENAPI_SWAGGER_UI_VERSION"] = "3.24.2"
app.config["OPENAPI_SWAGGER_UI_URL"]="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/3.24.2/"

With these 4 parameters you should obtain swagger at the url : `http://127.0.0.1:5000/api/api_swagger_path`

**Comment by lafrech** [comment]
Thanks. This is correct except you don't need to specify `OPENAPI_SWAGGER_UI_VERSION` if `OPENAPI_SWAGGER_UI_URL` is provided.

Docstring says:

        The Swagger UI scripts base URL can be specified as
        OPENAPI_SWAGGER_UI_URL.
        Otherwise, cdnjs is used. In this case, the Swagger UI version must be
        specified as OPENAPI_SWAGGER_UI_VERSION. Versions older than 3.x branch
        are not supported.
        OPENAPI_SWAGGER_UI_VERSION is ignored when OPENAPI_SWAGGER_UI_URL is
        passed.

When passing only a version, the url defaults to a CDN providing that version.

Maybe this is useless sugar and we should require a URL.

**Comment by Dridou** [comment]
I just tested and I don't need so specify `OPENAPI_SWAGGER_UI_URL` if `OPENAPI_SWAGGER_UI_VERSION` is set, but this is the oposite of what you just said ``` This is correct except you don't need to specify OPENAPI_SWAGGER_UI_VERSION if OPENAPI_SWAGGER_UI_URL is provided.```

So the doc is right, but, in my opinion, a clearer sentence like 'you either choose to set at least a `OPENAPI_SWAGGER_UI_VERSION` corresponding to your scripts versioning or you choose to also set `OPENAPI_SWAGGER_UI_URL` which will overwrite `OPENAPI_SWAGGER_UI_VERSION` in this case.' or something like that.

Moreover, docstring says this, but I read severals times OPENAPI doc and I simply would like to have an example as I did above to clearly undestand what parameter is esential to set or not.
But maybe that's only me who had troubles to handle how to make it works !

**Comment by lafrech** [comment]
Yes, you should pass only one of them. URL overrides VERSION.

We could clarify the docs. Or perhaps remove VERSION which defaults on a CDN and only keep URL, which requires the user to pass a local or CDN URL.

**Comment by Dridou** [comment]
That could be a good idea to clarify the docs.

Thank you for the explanations !

**Comment by lafrech** [comment]
See #134 and #135 for hardcoded CDN removal, doc update and examples.

**Comment by lafrech** [comment]
I removed `_VERSION` parameters and updated the docs to provide CDN examples and a config example.

Please comment if things are still blurry.

**Comment by azzamsa** [comment]
with the MWE below, swagger-ui is created at: `http://127.0.0.1:5000/api/api_swagger_path#/`. but still redoc can't be accessed at: `http://127.0.0.1:5000/api/redoc`. *any solution*?

```python
import marshmallow as ma
from flask import Flask
from flask.views import MethodView
from flask_smorest import Api, Blueprint


class Config:
    OPENAPI_VERSION = "3.0.2"
    OPENAPI_URL_PREFIX = "/api"
    OPENAPI_SWAGGER_UI_PATH = "/api_swagger_path"
    OPENAPI_SWAGGER_UI_VERSION = "3.24.2"
    OPENAPI_SWAGGER_UI_URL = "https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/3.24.2/"
    OPENAPI_REDOC_PATH = "redoc"


app = Flask("My API")
app.config.from_object(Config)
api = Api(app)


# @api.definition("Pet")
class PetSchema(ma.Schema):
    class Meta:
        strict = True
        ordered = True

    id = ma.fields.Int(dump_only=True)
    name = ma.fields.String()


blp = Blueprint("pets", "pets", url_prefix="/pets", description="Operations on pets")


@blp.route("/")
class Pets(MethodView):
    @blp.response(PetSchema(many=True))
    def get(self):
        """List pets"""
        # TODO
        # return Pet.select()


api.register_blueprint(blp)

if __name__ == "__main__":
    app.run()

```

**Comment by lafrech** [comment]
@azzamsa 
- missing REDOC_URL
- SWAGGER_UI_VERSION is useless

See https://flask-smorest.readthedocs.io/en/latest/openapi.html.

**Comment by azzamsa** [comment]
Thank you. Work like a charm.

``` python
    OPENAPI_VERSION = "3.0.2"
    OPENAPI_URL_PREFIX = "/api"
    OPENAPI_SWAGGER_UI_PATH = "/swagger"
    OPENAPI_SWAGGER_UI_URL = "https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/3.24.2/"
    OPENAPI_REDOC_PATH = "/redoc"
    OPENAPI_REDOC_URL = (
        "https://cdn.jsdelivr.net/npm/redoc@2.0.0-rc.30/bundles/redoc.standalone.js"
    )
```

**Comment by falk-stefan** [comment]
If I am running the following and try to access 

```python
from flask import Flask
from flask_restful import Api
from controller.ticker import Tickers


class Config:
    OPENAPI_VERSION = "3.0.2"
    OPENAPI_URL_PREFIX = "/api"
    OPENAPI_SWAGGER_UI_PATH = "/swagger"
    OPENAPI_SWAGGER_UI_VERSION = "3.24.2"
    OPENAPI_SWAGGER_UI_URL = "https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/3.24.2/"
    OPENAPI_REDOC_PATH = "redoc"


app = Flask(__name__)
app.config.from_object(Config)
api = Api(app)
api.add_resource(Tickers, '/api/tickers')


@app.route('/')
def hello_world():
    return 'Hello World!'


if __name__ == '__main__':
    app.run()
```

I am not seeing any of the endpoints:


```
$ PYTHONPATH=banal/ FLASK_APP=banal/ flask routes
Endpoint     Methods  Rule
-----------  -------  -----------------------
hello_world  GET      /
static       GET      /static/<path:filename>
tickers      GET      /api/tickers
``` 

What am I missing here?

**Comment by lafrech** [comment]
> What am I missing here?

flask-smorest, I guess.

You're using flask_restful.

**Comment by Ambro17** [comment]
After reading the docs, navigating the examples and finding this issue i solved my problem.
I was registering the blueprint with my Flask object instead of `flask_smorest.Api` object. After changing that detail, docs are now generated.
Before 
```python
from some_blueprint import my_blueprint

app = Flask(__name__)
app.register_blueprint(my_blueprint)
```

After:
```python
from some_blueprint import my_blueprint
from flask_smorest import Api

app = Flask(__name__)
api = Api(App)
api.register_blueprint(my_blueprint)
```

In retrospective, it's obvious, but in my opinion it's not so clear on the dedicated docs section: https://flask-smorest.readthedocs.io/en/latest/openapi.html

Would you accept PRs with a minimal working example?

**Comment by lafrech** [comment]
It is written at the end of the Quickstart, which is some sort of minimal example.

> Finally, register the Blueprint in the Api.
> 
>     api.register_blueprint(blp)

**Comment by Ambro17** [comment]
You are right! I never saw that. Perhaps it would be helpful to add all fragments into a copy-pasteable example to try and run, do you think it would be worth it? Some of us only read the docs when we get stuck and having a minimal working example is really helpful!

Regardless of your answer thank you very much for this awesome lib!! I found it really helpful to document my api in a code-first approach as i do with my graphql apis
