### ISSUE TITLE
Open-Api docs generation does not support nested blueprints

### ISSUE THREAD

**Issue by sergioisidoro** [marshmallow-code/flask-smorest#261]
I have the following nested blueprint setup, that allows me to do specific authorisation to all API endpoints

```py
from app.api.resources.users import users_api_blueprint
from flask_jwt_extended import jwt_required
from flask_smorest import Blueprint

root_api_blueprint = Blueprint(
    'api', 'api', url_prefix='/api/v1',
    description='RootApi'
)

@root_api_blueprint.before_request
@jwt_required(optional=True)
def before_request():
    """
    All routes are optionally required to provide JWT.
    This means current user is available (or None) on all
    api routes.
    """
    pass


def register_api_blueprints(api):
    root_api_blueprint.register_blueprint(users_api_blueprint)
    api.register_blueprint(root_api_blueprint)
```

When generating the open api specs, this is what I get:
```
{
  "paths": {},
  "info": {
    "title": "lightning API",
    "version": "v1"
  },
  "tags": [
    {
      "name": "api",
      "description": "RootApi"
    }
  ],
  "openapi": "3.0.2"
}
```

**Comment by sergioisidoro** [comment]
This is tangentially related to #152 because nested blueprints helps to register a set of blueprints with a basepath.

**Comment by lafrech** [comment]
AFAIK, nested blueprints is a feature that was introduced in Flask 2. There was no work yet in flask-smorest to support it.

I haven't even taken the time to check what it does and how it works. I'd be happy to support this, of course, but it is not on top of my priority list so if anyone is willing to investigate, their are more than welcome to share their findings here.

**Comment by sergioisidoro** [comment]
> AFAIK, nested blueprints is a feature that was introduced in Flask 2

Ah! Good point. I started a new project and realised that I could do this, although remembering it wasn't previously possible. If you give me one or two pointers I might dig into this myself and try to create a pull request :)

**Comment by Cnoor0171** [comment]
@lafrech Sorry for the dup. Is this something that's already being worked on? If not, I can try taking a stab at it. On the surface, it doesn't seem like it would be a lot of work, but I can take a closer look if its not already on someone's plate.

**Comment by lafrech** [comment]
No one is working on this AFAIK. Help very welcome. Thanks!
