### ISSUE TITLE
required=False does not validate fields.

### ISSUE THREAD

**Issue by Amitg1** [marshmallow-code/flask-smorest#285]
Hi,
I created the following schema:

```py
class WorkflowQueryArgsSchema(mar.Schema):
    class Meta:  # pylint: disable=too-few-public-methods
        unknown = EXCLUDE
    name = mar.fields.Str(required=True)
    cwl = mar.fields.Dict(required=True)
    schedule = mar.fields.Nested(ScheduleSchema, required=False)
```

ScheduleSchema is not a most for the user, but if the user supplies it, fields should go through validation.
Do I have an option for required=False & if supplied - validate?

Thanks.

**Comment by lafrech** [comment]
Non-required fields should be validated. There must be another problem but we can't tell with just this piece of code.

Do you have a reproducible example exhibiting what you describe (non-required field not being validated)?

FWIW, most of the fields in my schemas are not required and yet they are validated.

**Comment by lafrech** [comment]
Error must be on your side. Feel free to comment if you need help on this.

**Comment by Amitg1** [comment]
My bad, thank you and sorry.
