### ISSUE TITLE
Two tests failing on FreeBSD

### ISSUE THREAD

**Issue by mekanix** [marshmallow-code/flask-smorest#290]
The failures start at [line 520 in the log](https://pastebin.com/x1VMBnk1), but I think the cause of those errors is the same. Can you help me identify what's causing it, please? Thank you!

**Comment by lafrech** [comment]
Can't really tell from the logs but the jinja warning smells like dependency versions issue.

Please double-check the dependencies versions (flask, etc.).

**Comment by mekanix** [comment]
Ah, flask is still 1.1.2. I guess that's going to take a while to upgrade with all dependencies. I'm closing as it's not flask-smorest issue.
