### ISSUE TITLE
Hide required=False fields from request body

### ISSUE THREAD

**Issue by jcunhafonte** [marshmallow-code/flask-smorest#294]
I would like to understand if I can use marshmallow **required** parameter to customize whether a field is displayed by default on the request body or not.

I have the following schema:

```
from marshmallow import Schema, fields, validate

class PaymentSchema(Schema):
    currencies = fields.List(
        fields.String(
            required=True,
            validate=[
                validate.OneOf(["USD", "EUR", "AUS", "GBP"]),
                validate.Length(min=1, max=4)
            ]
        )
    )
    value = fields.Integer(required=False)
```

This is the generated **swagger-ui**:
<img width="948" alt="Screenshot 2021-10-26 at 13 04 35" src="https://user-images.githubusercontent.com/17337794/138873804-94b46fcb-f481-48f4-92b1-851de7325175.png">

Is there any possibility to guarantee that value doesn't show up in **swagger-ui**?

Thanks!

**Comment by lafrech** [comment]
There is no way to hide parameters. The whole schema is always displayed. `required` just means what it says: the field is required for the request to be valid.

Hiding parameters would happen in apispec. This sounds quite like a corner-case feature, not something I'd be willing to add there unless someone convinces me of the usefulness of the use case. However, it might be possible to hack something in apispec to add a "hide" field metadata parameter.
