### ISSUE TITLE
@pre_load based in POST/PUT

### ISSUE THREAD

**Issue by kettenbach-it** [marshmallow-code/flask-smorest#295]
Can I somehow distinguish in the "@pre_load" whether the data comes from a POST or a PUT?
The reason is that I want my clients to be able to upload objects they have loaded with GET simply again with POST and PUT. However, to do this I need to remove two fields completely and also the primary key for POST, but this must not be in PUT.
I don't want to create two schemas, but would handle the whole thing in pre_load.
Is that possible?

**Comment by lafrech** [comment]
I suppose you could use the request context.

```py
from flask import request

# In post_load method:
method = request.method
```

**Comment by kettenbach-it** [comment]
🤦
