### ISSUE TITLE
Handling invalid JSON input…

### ISSUE THREAD

**Issue by zedrdave** [marshmallow-code/flask-smorest#30]
I *think* this is more of a webargs issue than specific to `flask-rest-api`, but I also suspect that the most efficient way to address it, would be inside the API…

In case an invalid JSON input is provided (to a `POST` or `PUT` call), it is treated as an empty dict `{}`, no error is thrown, and, depending on the value of `model_build_obj`, it is either:
- passed as is to the function's payload
- passed to Marshmallow, which fails to generate an object (but doesn't give the most useful reason why)

From what I understand, this is due to webargs' flask parser loading the JSON silently:
```
        # Fail silently so that the webargs parser can handle the error
        if hasattr(req, "get_json"):
            # Flask >= 0.10.x
            json_data = req.get_json(force=force, silent=True)
        else:
            # Flask <= 0.9.x
            json_data = req.json
        if json_data is None:
            return core.missing
```

… from the comment in webarg's code, it *seems* the user is supposed to implement error handling to catch this case, although I don't quite see how it would be possible to know retrospectively that the `core.missing` being returned was the reason of an invalid JSON, rather than actually missing…

Do you have any idea how I could go about ensuring my API returns a proper 400 error?

**Comment by lafrech** [comment]
@zedrdave, I think this can be closed thanks to https://github.com/marshmallow-code/webargs/issues/329, right?

**Comment by zedrdave** [comment]
@lafrech Yes, I think this is now handled correctly on webargs' side!
