### ISSUE TITLE
Unexpected behaviour for webargs.fields.DelimitedList

### ISSUE THREAD

**Issue by BorjaEst** [marshmallow-code/flask-smorest#302]
Taking the following schema:
```python
from marshmallow import Schema
from webargs import fields

class MyScghema(Schema):
    a = fields.String()
    b = fields.String()

    sort_by = fields.DelimitedList(fields.String())
```

According to [Webargs](https://webargs.readthedocs.io/en/latest/quickstart.html#parsing-lists-in-query-strings) and [webargs/issues/406](https://github.com/marshmallow-code/webargs/issues/406), I would expect the OpenAPI specification to design something like this:
```bash
curl 'http://localhost:5000/benchmarks?sort_by=a,b'
```

However, when I use the swagger interface, it produces something like this:
```bash
curl 'http://localhost:5000/benchmarks?sort_by=a&sort_by=b'
```

To use a correct OpenAPI serialization I would recommend:
[Swagger, serialization](https://swagger.io/docs/specification/serialization/) -> Query Parameters (style='form' + explode=false)

**Comment by lafrech** [comment]
Looks like https://github.com/marshmallow-code/apispec/issues/500.

Known issue. Needs a rework in apispec. I just didn't get the time to do it. Not on top of my priorities. Anyone stuck on this is welcome to take a stab at it.

**Comment by jcunhafonte** [comment]
@lafrech Do you have any suggestions on where to start?

**Comment by jcunhafonte** [comment]
@BorjaEst @lafrech We can override `marshmallow_plugin.Converter_field2parameter` to support **DelimitedList** by overriding **MarshmallowPlugin** and pass it to _spec_kwargs_.

```py
from flask_smorest import Api
from apispec.ext.marshmallow import MarshmallowPlugin
from marshmallow.utils import is_collection
from webargs.fields import DelimitedList
from marshmallow.utils import is_collection
from marshmallow.fields import List


def _field2parameter(self, field, *, name, location):
    """Return an OpenAPI parameter as a `dict`, given a marshmallow
    :class:`Field <marshmallow.Field>`.
    https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#parameterObject
    """
    ret = {"in": location, "name": name}

    partial = getattr(field.parent, "partial", False)
    ret["required"] = field.required and (
        not partial or (is_collection(partial) and field.name not in partial)
    )

    prop = self.field2property(field)
    multiple = isinstance(field, List)

    if self.openapi_version.major < 3:
        if multiple:
            ret["collectionFormat"] = "multi"
        ret.update(prop)
    else:
        if multiple:
            ret["explode"] = False if isinstance(field, DelimitedList) else True # Added this configuration
            ret["style"] = "form"
        if prop.get("description", None):
            ret["description"] = prop.pop("description")
        ret["schema"] = prop
    return ret


marshmallow_plugin = MarshmallowPlugin()
marshmallow_plugin.Converter._field2parameter = _field2parameter

api = Api(app, spec_kwargs=dict(marshmallow_plugin=marshmallow_plugin))
```

**Comment by lafrech** [comment]
Sure, one can monkey-patch the `Converter`. This was proposed in https://github.com/marshmallow-code/apispec/issues/500#issuecomment-604987485.

An ideal solution would be to make `_field2parameter` more generic in apispec.
