### ISSUE TITLE
Multi-File Upload?

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [marshmallow-code/flask-smorest#321]
I'm currently using `flask_smorest.fields.Upload` to handle file uploads, but this only allows selecting a single file. Is it possible to upload many files?

**Comment by lafrech** [comment]
You can have multiple `Upload` fields in the argument schema.

See related discussion: https://github.com/marshmallow-code/flask-smorest/issues/46.

**Comment by Anti-Distinctlyminty** [comment]
This is probably impractical for my purposes as I'm dealing with image sequences which can be thousands of files. Perhaps a zip archive is more practical.

**Comment by kettenbach-it** [comment]
Can I have a list of Uploads, too?

`flask_smorest.fields.List(flask_smorest.fields.Upload)`

**Comment by kettenbach-it** [comment]
I think I meant this:

` @MyBlp.arguments(MultipartSchema(many=True), location="files")`
