### ISSUE TITLE
Automatically fill `message` field for HTTPException, when it is present in api_docs…

### ISSUE THREAD

**Issue by zedrdave** [marshmallow-code/flask-smorest#33]
Ideally, when an endpoint call `abort` with an HTTP error, we would like the message to be filled according to the endpoint's documentation (e.g. "Resource missing", rather than Flask's default "The requested URL was not found on the server" for a 404).

This seems like something that could be done in the `abort` method? I have had a look at the Blueprint class, but still unsure where it should look, to get the list of responses for that particular call…

**Comment by lafrech** [comment]
I won't spend much time on this myself, as I don't think it is critical. But if someone comes up with a satisfying solution, I'm happy to merge it.

I'm not sure I understand the feature description correctly, but from what I graps, it could be challenging.

First, we'd need to sort of single-source the error messages. I mean at the end, they are in the docs, but before that, they must be structured somewhere in the code. This could be in several places (path description, response component definition).

Then, `abort` can be called from anywhere before even entering a resource. The 404 error is the best example. It does not belong to a resource. Arguably, `/pets/wrong_id` is a "Pet not found" issue, but `/pest/pet_id` just does not relate to any resource. Maybe there are other similar cases.

Let's say you get an authentication error in an auth decorator. Then abort. You're not in the resource function yet. You could get the path from the request object. Then you'd need to go all the way from the path to the function to access the error message. I does not seem straightforward.

I could be missing something.

If you're still interested in this, you may want to elaborate on a use case description. But frankly, I don't think I'll be of much help.

**Comment by zedrdave** [comment]
I'll need to go and have a look again (it's not even that fresh in my memory any more), but even if not using the Resource's doc to provide the error (although that would be even nicer), at least honouring the second arg in the `abort` function (currently, it gets overwritten by default HTTP error messages) would be helpful…

**Comment by lafrech** [comment]
This should work:

```py
abort(400, message='What a bad request')
```

The custom error message should appear in the response payload.

Or am I misunderstanding your point?

**Comment by lafrech** [comment]
@zedrdave I don't think flask-rest-api can do much more than pass the message in the call to `abort` as shown in my comment above.

May I close this? Or do you think you can be more specific about what you're thinking about, perhaps with use case examples?

**Comment by zedrdave** [comment]
@lafrech I think `abort(400, message='something')` is fine. Wondering if it might be possible to make `message` the second positional argument without too much breakage (as I think that would increase compatibility with other versions of `abort`).
