### ISSUE TITLE
List of Dicts for location=query?

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [marshmallow-code/flask-smorest#332]
I am trying to utilize a list of dicts, something like this:

```python 

class MySchema(Schema):
    jsonData = fields.List(
        fields.Dict,
        load_default=[{"k": "v"}]
    )

@bp.route("/output")
class SomeResource(MethodView):
    @bp.response(HTTPStatus.CREATED)
    @bp.arguments(FarmSubmitOutputSchema, location="query", as_kwargs=True)
    def put(self, **kwargs):
        pass
```

I just end up with a Unprocessable Entity, but if I remove the `location="query" then it all seems to work just fine. I'm not sure if this is the 'proper' way to do this.

**Comment by lafrech** [comment]
Unclear to me. What is the location of the argumentm? Do you pass them as query args or in the body?

Passing a list of dicts as query args is not well defined, so don't expect this to work out of the box. You'd need to define how to write dicts, and lists, in a query argument.

**Comment by Anti-Distinctlyminty** [comment]
> Do you pass them as query args or in the body?
Query args.

> Passing a list of dicts as query args is not well defined

What I'm currently doing is using `dumps` and `loads` to convert to and from strings, which seems to work perfectly fine. I just wanted to confirm that I'm not doing this in a daft way, which you confirmed.  Thank you.
