### ISSUE TITLE
description for route

### ISSUE THREAD

**Issue by arabnejad** [marshmallow-code/flask-smorest#336]
Hi 
how can I have `description` at route level ?

something like
```yaml
...
paths:
  /api/adduser:
    post:
      description: |
        test 1 \
        test 2 :
        * check 1
          1. check 1\
            1.1 check2
        * *check 1*
        * **check 1**
      responses:
        '201':
          description: User created
...
```

I could not find any input argument to add to the generated json file  
```yml
      description: |
        test 1 \
        test 2 :
        * check 1
          1. check 1\
            1.1 check2
        * *check 1*
        * **check 1**
```
![Screenshot 2022-03-16 at 15-54-07 Swagger Editor](https://user-images.githubusercontent.com/7812608/158632244-b981c5b6-c678-4905-ba10-8b5150337255.png)

**Comment by arabnejad** [comment]
sorry, my bad
I found the solution

**Comment by arabnejad** [comment]
OK, I found the solution (`@blueprint.doc`) 
is that possible to pass a markdown format or having multiline description ?

**Comment by lafrech** [comment]
See https://flask-smorest.readthedocs.io/en/latest/openapi.html#add-summary-and-description.
