### ISSUE TITLE
Examples of smorest & webargs

### ISSUE THREAD

**Issue by cmabastar** [marshmallow-code/flask-smorest#340]
Hi devs,

Would like to know if this is compatible or possible to use smorest with using flask webargs?

Or should I just remove flask webargs and use smorest alone with marshmallow ? 

Any examples would be helpful!

**Comment by lafrech** [comment]
I don't understand the question. flask-smorest does use webargs internally. More info in the docs.

**Comment by cmabastar** [comment]
thanks! Forgot that webargs has a marshmallow docs example!
