### ISSUE TITLE
Question: How to use Smorest with Large Apps

### ISSUE THREAD

**Issue by diloreto** [marshmallow-code/flask-smorest#348]
I'm looking to build a large application that will have dozens, if not hundreds, of routes, as well as 40-80 different entities/objects/tables in our models.py and dozens of blueprints. How do you recommend structuring the app.py so none of the models, routes, schemas are found inline of app.py but rather separate modules we could load? What is making things difficult is the order of invocation/loading each of the modules (flask/sqlalchemy db/marshmallow) as well as needing to create the marshmallow object (`ma`) inside the main app but also requiring its presence in each schema.py file.

Thanks!

**Comment by lafrech** [comment]
The question is quite broad. You may want to have a look at

- This tiny demo app, slightly outdated: https://github.com/lafrech/flask-smorest-sqlalchemy-example
- This real-life app, divided in two repos, one for the core (SQLAlchemy) and one for the API (flask-smorest): https://github.com/BEMServer/bemserver-core, https://github.com/BEMServer/bemserver-api
