### ISSUE TITLE
[openapi] interoperability issue due to vague `Integer` type

### ISSUE THREAD

**Issue by tigerinus** [marshmallow-code/flask-smorest#349]
I have

1) a Python based service built using smorest with openapi doc enabled
2) a Java based client which rely on generated code from the openapi spec (tooling: https://openapi-generator.tech/docs/generators/java) 

Somewhere in the schema definition I have a `timestamp` field of `Integer` type:

```python
class Request(Schema):
    """
    Schema for Request
    """
    # other fields omitted
    timestamp = Integer(required=True, validate=lambda n: n > 100000000000)
```

Problem: 

The `timestamp` field is actually a `int64` or `long` type.

Due to that there is no `Long` type in marshmallow, I had to use `Integer` in the schema.

However openapi generated by smorest does not specify its `format` to be `int64`. (See https://spec.openapis.org/oas/latest.html#data-types).

Because of this, any OpenAPI code gen would have no way to tell whether this `timestamp` field is a `int32` or a `int64`.

This causes issue in generated Java code based on the the openapi spec from smorest, that the OpenAPI code gen for Java simply assumes it's `int32`, which cannot be used for any epoch timestamp value in millisecond.

```java
@JsonTypeName("Request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-08T01:20:20.510Z[GMT]")
public class Request implements Serializable {
  private static final long serialVersionUID = 1L;

  // other fields omitted.

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  private Integer timestamp;  // <-- this should be Long type.
```

Expected Behavior:

When smorest generates openapi, it should specify `format: int64` for any `Integer`, so downstream consumer of this openapi spec does not mistaken it with `int32`.

**Comment by lafrech** [comment]
This was discussed in https://github.com/marshmallow-code/apispec/pull/595.

As suggested there, you may override the default field mapping. I should like like this:

```py
api.ma_plugin.Converter.field_mapping[ma.fields.Integer] = ("integer", "int64")
```

**Comment by tigerinus** [comment]
@lafrech thank for the snippet.

I need some more understanding of this workaround. Can you elaborate on what's `ma_plugin` and `ma`?

---
UPDATE: nevermind - I figured out that `ma` is an alias of `marshmallow`

**Comment by lafrech** [comment]
Sorry.

`ma` as in

    import marshmallow as ma

`ma_plugin` is an attribute of the `Api` class in flask-smorest.

**Comment by tigerinus** [comment]
Works now. Thanks.
