### ISSUE TITLE
Flask commands to generate OpenAPI schema in yaml 

### ISSUE THREAD

**Issue by derlikh-smart** [marshmallow-code/flask-smorest#365]
Currently there are two Flask command:

1. `flask openapi print` to print OpenAPI schema to output
2. `flask openapi write <file>` to write OpenAPI schema to file

Both of them serialize OpenAPI schema to json.
It would be great to have an option to generate it to yaml as well.

**Comment by lafrech** [comment]
I'm reluctant to introduce a dependency to yaml but if it was optional like in apispec, I guess I wouldn't object.

I won't do it myself, but people interested in this may discuss it here and propose an implementation.

**Comment by derlikh-smart** [comment]
I wanted to implement it myself. But first of all it makes sense to create an issue to discuss it.
If it's OK, I'll work on PR.

**Comment by lafrech** [comment]
Achieved in #367.
