### ISSUE TITLE
How to POST file and json payload at the same time?

### ISSUE THREAD

**Issue by kettenbach-it** [marshmallow-code/flask-smorest#380]
This does not work:
```
    @HelperBlp.arguments(CodescannerDataSchema, location="json")
    @HelperBlp.arguments(MultipartFileSchema, location='files')
```

and I don't want to send the json-data as query-parameter (ugly).
How can this be done?

**Comment by reederz** [comment]
You can stack multiple locations https://webargs.readthedocs.io/en/latest/advanced.html#mixing-locations :

```python
@HelperBlp.arguments(CodescannerDataSchema, location="json")
@HelperBlp.arguments(MultipartFileSchema, location='files')
def route(json_args, files_args):
    pass
```

**Comment by kettenbach-it** [comment]
I think this is covered in https://github.com/marshmallow-code/flask-smorest/issues/46
