### ISSUE TITLE
[RFC] Change module name

### ISSUE THREAD

**Issue by zedrdave** [marshmallow-code/flask-smorest#42]
This might sound silly, but the API's current name ('flask-rest-api') makes it practically impossible to Google.

Not only is it slightly frustrating when trying to recall the github or readthedocs URL in a bind, but in some possible future, it will make it all but impossible to try and find related posts on Stackoverflow or elsewhere.

I would strongly recommend picking a name (any name) that is somewhat unique and easy to search. I know it's going to be a bit of a mess updating, but probably still easier now, than another year down the road.

**Comment by qcho** [comment]
I think this is a legit issue. It's almost impossible to find this repo right now. Maybe it's just temporary until it indexes better

**Comment by lafrech** [comment]
I did search for a cooler name before releasing as flask-rest-api. I just couldn't find any, so I defaulted to something simple but descriptive.

I wouldn't be totally opposed to a name change if we came up with something great. My colleague has been searching for words containing "rest" or "spec", or in the semantic field of "marshmallow", the other day. Yet, to no avail.

Hopefully, the search engine ranking will improve with time (and GH stars, perhaps...).

**Comment by DavidM42** [comment]
I also think this is an issue. Don't know how I found this module but it really is much more ready to go than the other Flask Api frameworks I tried. I've got a silly name suggestion: **Flasabi** or similiar. It's kind of a wordplay on flask+api. It's short, seo optimized (can't find anything relevant on google) and there is an implied idea for a simplistic logo. A minimalistic bowl of wasabi could be an easily recognizable icon for the module.

**Comment by zedrdave** [comment]
@lafrech I think something in the semantic field of Marshmallow would be a good idea too (it doesn't have to be overly original or witty: as long as it can be made sufficiently unique and easy to google).

How about a variation around S'more: https://en.wikipedia.org/wiki/S%27more

RES'more, RESmore, SmoREST…

**Comment by lafrech** [comment]
@zedrdave, sounds like you're onto something. Apparently, someone already had a similar idea: https://pypi.org/project/Flask-Smores/. It doesn't prevent us to use a variant along the lines of your suggestions.

**Comment by zedrdave** [comment]
How about SmoresT or smoREST?

**Comment by lafrech** [comment]
Thanks @zedrdave. SmoREST and variants is the best we've come up with so far.

What about flask-smorest ?

Meanwhile, I've been discussing this @sloria (marshmallow lead).

He doesn't object to moving flask-rest-api to [marshmallow-code organization](https://github.com/marshmallow-code). This could provide more visibility.

He also thinks that the good thing about the name flask-rest-api is that by being so plain and descriptive, it makes it look like the one, canonical, solution to do the job (a REST API based on Flask).

I agree with that. OTOH, I also like the idea of a nice, catchy and punny name. It might also make it easier to find a logo idea...

Keeping this open for now. Feedbacks welcome.

**Comment by zedrdave** [comment]
flask-smorest/SmoREST seems fine by me.

I really don't think the current name is sustainable: a google search for the exact string `flask-rest-api` doesn't show this repo or the doc's page in the first 5 results… 😕

I understand wanting to be the 'canonical' solution to do the job, but considering there are already 2 well-established APIs that do REST on Flask, this seems maybe a little overambitious (being "one of the solution, with an emphasis on simplicity and interfacing with existing tools" isn't bad either).

**Comment by lafrech** [comment]
Sure, I'm not claiming flask-rest-api is actually the only working solution. Canonical also mean it is not tied to a specific database, etc. Well, it is tied to Flask, which makes it synchronous. But that's pretty much it.

Out of curiosity, what are the two libs you're thinking about? I guess flask-restplus but what is the other one?

I like flask-smorest. We could use the marshmallow logo and add two crackers on top and bottom...

**Comment by zedrdave** [comment]
I understand the desire to present it as a tool that relies on existing "standards". Then again, I don't think the other ones are really tied to a specific DB etc, their main downside would be in requiring a lot of redundant definitions and rewrites…

The other lib I was thinking. of would be flask-restful, which I think might even be more popular than flask-restplus nowadays (if I'm not mistaken, however, it's a fork, and fairly similar overall).

> I like flask-smorest. We could use the marshmallow logo and add two crackers on top and bottom...

Sounds perfect!

**Comment by lafrech** [comment]
AFAIK the fork is the other way around: https://github.com/noirbizarre/flask-restplus/issues/9#issuecomment-385182472.

Interesting read about flask-restful and marshmallow stack: https://github.com/flask-restful/flask-restful/issues/335.

**Comment by zedrdave** [comment]
Very possible. And yes, I'm aware of their efforts to standardise with marshmallow/api-spec… I was previously using a [heavily-patched] fork that provided just this. But still think starting from scratch with flask-smorest, is a bit more promising.

**Comment by lafrech** [comment]
OK, so flask-smorest it shall be.

## flask-smorest - 'cause everybody wants s'more

Next steps : 
- [x] Prepare a branch with the renaming (code, docs, new repo URL,...)
- [x] Transfer repo to marshmallow-code organization
- [x] Fork back here
- [x] Rename new repo to flask-smorest
- [x] Merge renaming branch in new flask-smorest repo
- [x] Activate test hooks in new repo
- [x] Publish new flask-smorest (minor) version
- [x] Add note on README in flask-rest-api fork to mention the rename / repo move
- [x] Publish a new (patch) flask-rest-api version with a deprecation warning about the rename

@sloria, I'll be knocking on your door when the time comes if I lack privileges for the transfer.

**Comment by lafrech** [comment]
To all watchers, the transfer / rename has begun.

New repo is https://github.com/marshmallow-code/flask-smorest/.

Hopefully, the lib will gain visibility.

Still a few things to polish before a release.

**Comment by fbergroth** [comment]
@lafrech the repo description still says
> DB agnostic framework to build auto-documented REST APIs with Flask and marshmallow https://flask-rest-api.readthedocs.io

**Comment by lafrech** [comment]
Fixed. Thanks.
