### ISSUE TITLE
form-data schema only reserves file fields

### ISSUE THREAD

**Issue by duanyukai** [marshmallow-code/flask-smorest#426]
Using the following code, I defined a `form-data` schema with both normal string/int fields and file upload fields.

```python
class AssetUploadZipQueryArgsSchema(ma.Schema):
    project_id = ma.fields.Integer()
    zip = Upload()


@bp_asset.route('/upload-zip')
class AssetUploadZip(MethodView):
    @bp_asset.arguments(AssetUploadZipQueryArgsSchema, location='files')
    @jwt_required()
    def post(self, files):
        try:
            print(files)
        except Exception as e:
            traceback.print_exc()
            abort(500, message=str(e))
```

Using the SwaggerUI, I could select files and input an string parameter, but there's no `project_id` field in `files` argument.

![](https://user-images.githubusercontent.com/3761023/205456075-83a425b0-e715-4d44-8c65-b99d761fa96e.png)

```shell
{'zip': <FileStorage: 'test.zip' ('application/x-zip-compressed')>}
```

**Comment by duanyukai** [comment]
While the swagger is generated correctly, I'm using the raw `flask.request.form` to get the raw string parameter currently.

**Comment by lafrech** [comment]
I guess `project_id` should not be in `files` but in `form` or something. I mean I'm wondering if perhaps what you're trying to do should not be done and Swagger UI is being too permissive about it. Not sure but it seems strange to pass an integer.

In any case, this happens in webargs or more likely flask. You may want to have a look at what happens in pure flask. Well, apparently, the parameter is found in `flask.request.form` so using a separate schema with `location="form"` should work.

**Comment by lafrech** [comment]
Closing this. You may comment here if case is not solved.
