### ISSUE TITLE
Blueprint definitions

### ISSUE THREAD

**Issue by qcho** [marshmallow-code/flask-smorest#43]
Hi,

I'm creating an app with many blueprints for different sections of the API. It seems there should be a way to define definitions inside the blueprint. Something like:

```python
blp = Blueprint(
    'pets', 'pets', url_prefix='/pets',
    description='Operations on pets'
)

@blp.definition('Pet')
class PetSchema(ma.Schema):

    class Meta:
        strict = True
        ordered = True

    id = ma.fields.Int(dump_only=True)
    name = ma.fields.String()
```

It's not suitable to create a circular dependency where the API is defined so it seems you need to do something like:
```python
api=Api()
@api.definition('Pet')
```

Any recommendations on workarounds? thanks!

**Comment by lafrech** [comment]
Don't import the blueprint in the file that instantiates the Api.

`my_app/api.py`

```py
api = Api()
```

`my_app/some_section/schemas.py`

```py
from my_app.api import api

@api.definition('Pet')
class MySchema():
    ...
```

`my_app/some_section/resources.py`

```py
from .schemas import MySchema

blp = Blueprint()

@blp.route(...)
def ...
    ...
...
```

`my_app/__init__.py`

```py
from my_app.api import api
from my_app.some_section.resources import blp as some_section_blp
from my_app.some_other_section.resources import blp as some_other_section_blp

def create_app():
    app = Flask('myApp')
    api.init_app(app)
    api.register_blueprint(some_section_blp)
    api.register_blueprint(some_other_section_blp)
    ...
```

**Comment by qcho** [comment]
Did something like that in the end. I suppose you don't see any good in having `blp.definition` available

Thanks for the reply!

**Comment by ghost** [comment]
@lafrech @qcho 
I just made a simple hack for flask-rest-api to make it to definite schmea by blueprint.
It just lazy loads schema_cls and arguments in blueprint, when blueprint is register by api, it register all schemas under the blueprint to main api class.
I think it needs tests and could be more flexible, do you guys give some advice?
https://github.com/ssfdust/flask-rest-api/commit/49346fe938b563541efdbe6e68015581704021d5

If you think it is ok, I will give a pr.

**Comment by lafrech** [comment]
@ssfdust your change seems reasonable.

Note that in master, I changed definition into schema to adhere to OAS3 terminology, like apispec.

Also if you manage the case where the blueprint is instantiated with an app, you need to modify your `blp.definition` decorator to call `api.definition` if `app` is initialized already, kinda like what I did in [`Api.schema`](https://github.com/Nobatek/flask-rest-api/blob/master/flask_rest_api/spec/__init__.py#L212).

Yet, I'm a bit reluctant to support many ways to achieve the same thing (useless code complexity). I really need to provide a real world example (https://github.com/Nobatek/flask-rest-api/issues/38). Is there anything blocking with the structure I presented in [my comment above](https://github.com/Nobatek/flask-rest-api/issues/43#issuecomment-471116311)?

**Comment by ghost** [comment]
I just manage a simple example, it looks like flask-restplus with api.blueprint.

`app.py`

```py
from modules.auth import api as auth_api
from modules.users import api as usr_api

def create_app(config=''):
    app = Flask("Authorization")
    app.config.from_object(DevConfig)

    spec_kwargs = {
        'components': {
            'securitySchemes': {
                'api_key': {
                    'type': 'http',
                    'scheme': 'bearer',
                    'bearerFormat': 'JWT'
                }
            }
        }
    }
    auth_api.init_app(app)
	usr_api.init_app(app, spec_kwargs=spec_kwargs)
```
`modules/user/__init__.py`
```py
from flask_rest_api import Api

api = Api("usr")
usr_blp = api.blueprint("users", "users",
                        url_prefix="/api/v1/users",
                        description="User Resources")

from . import resources # NOQA
```
project: https://github.com/ssfdust/flask-rest-api-example
patched version: https://github.com/ssfdust/flask-rest-api/tree/blp_from_api

**Comment by lafrech** [comment]
@ssfdust, your example instantiates several `Api`. It is not the way it is meant to be used.

**Comment by ghost** [comment]
How about this version?

`app.py`

```py
from flask import Flask
from config import DevConfig
from extensions import api

def create_app(config=''):
    app = Flask("Authorization")
    app.config.from_object(DevConfig)

    spec_kwargs = {
        'components': {
            'securitySchemes': {
                'api_key': {
                    'type': 'http',
                    'scheme': 'bearer',
                    'bearerFormat': 'JWT'
                }
            }
        }
    }
    api.init_app(app, spec_kwargs=spec_kwargs)
    register_blp(api)

    return app

def register_blp(api):
    from modules.auth import auth_blp
    from modules.users import usr_blp

    api.register_blueprint(auth_blp)
	api.register_blueprint(usr_blp)
```
`modules/user/__init__.py`
```py

from extensions import api

usr_blp = api.blueprint("users", "users",
                        url_prefix="/api/v1/users",
                        description="User Resources")

from . import resources # NOQA
```
project: https://github.com/ssfdust/flask-rest-api-example
patched diff: https://github.com/Nobatek/flask-rest-api/compare/master...ssfdust:blp_from_api_v1

**Comment by lafrech** [comment]
We realized today that thanks to the schema auto-registration feature introduced in apispec 1.0, there is actually no need to register the schema manually.

In other words, you can remove the call to `definition` everywhere

```py
@api.definition('Pet')
```

and the schemas will be registered automatically anyway.

The default behaviour in apispec is to register `PetSchema` as `Schema`. This is based on the assumption that people call their schemas with the name of the model suffixed with `"Schema"`. This behaviour can be changed for specific needs but I think it is a reasonable convention.

@qcho, can you please try to remove all calls to the `definition` decorator and tell me if it works?

**Comment by lafrech** [comment]
Closing this. I think this is not an issue anymore thanks to apispec auto-registration feature.

Feel free to comment if it is still an issue.
