### ISSUE TITLE
Facing issue in loading GET param with `SmorestBlueprint` arguments

### ISSUE THREAD

**Issue by indiVar0508** [marshmallow-code/flask-smorest#435]
Hi,

I am facing issue in parsing a list encolosed JSONparameter coming to my app via GET call, in which i am getting this error

```py
marshmallow.exceptions.ValidationError: {'sort': ['Invalid type.']}
```
input payload to my flask app is 
```py
ImmutableMultiDict([('sort', '[{"selector":"createdDate","desc":true}]'), ('param3000', 'val3000'), ('paramn', 'valn'), ('param1', 'val1')])
```
i defined my route like this
```py
@blueprint.arguments(MySchema, location='query', as_kwargs=True)
def get(xyz):
   ...
```

and mySchema is defined like this,
```py
class InternalSchema(Schema):

    selector = fields.Str()
    desc = fields.Boolean()

class MySchema(Schema):

    sort = fields.Nested(InternalSchema, many=True)
```

initally i thought this is some issue in Marhsmallow Nested field but it seems to work with using `loads` method but doesn't work with `load` method. being discussed [here](https://github.com/marshmallow-code/marshmallow/issues/2082#issuecomment-1365618807)

can you help me resolve this issue

**Comment by indiVar0508** [comment]
I tried to debug this what i see is in webargs `core.Parser` is using load is there a way to use `loads` in [load](https://github.com/marshmallow-code/webargs/blob/dev/src/webargs/core.py#L362)?

**Comment by deckar01** [comment]
The problem is that the data is double encoded. The `sort` object is encoded as a JSON string, then the key value pairs are encoded as query arguments. `location='query'` decodes the query string format, but there is no builtin way to declare that the value is JSON encoded.

A custom field would allow you to extend `Nested` to parse the JSON when it is loaded.

https://marshmallow.readthedocs.io/en/stable/custom_fields.html

```py
class NestedJSON(fields.Nested):
    def _deserialize(self, value, *args, **kwargs):
        value = json.loads(value)
        return super()._deserialize(value, *args, **kwargs)
```

```py
class MySchema(Schema):
    sort = NestedJSON(InternalSchema, many=True)
```

**Comment by indiVar0508** [comment]
Thanks @deckar01 for confirming,
yeah this solved my issue!
