### ISSUE TITLE
Setting ETag for empty JSON list

### ISSUE THREAD

**Issue by sergeyklay** [marshmallow-code/flask-smorest#471]
If API server returns empty JSON list, it should not return ETag header because there is no resource that can be cached and compared using ETag. The ETag is used to determine if the resource has changed since the last request, so that the client can use the cached resource if it has not changed and request a new resource only if it has.

Currently, the decorator sets the ETag header even if the response contains an empty list `[]`. I'm not sure that this is the correct behavior, or at least that this is the behavior expected by API clients. 

Please consider this issue and provide the option of not generating an ETag header for blank responses that cannot be identified.

**Comment by lafrech** [comment]
I'm open to discussion about this but my understanding is that an empty list is a response with the information that there is no item and the ETag allows the client to record this. Next request, a 304 status code indicates that there is still no item.

I see no reason to make a special case, here. Anyway, what's wrong with adding this header? The client is free to ignore it.

More or less related discussion: https://stackoverflow.com/questions/70838264/computing-an-etag-for-a-rest-api

**Comment by sergeyklay** [comment]
After some thought and more detailed research, I'm leaning more in your direction, although I have to admit that I still don't think it's obvious behavior. Thank you for considering this topic and leading me to some interesting thoughts. And of course thank you for your input and this project!
