### ISSUE TITLE
No PDF download option for Docs

### ISSUE THREAD

**Issue by falloutphil** [marshmallow-code/flask-smorest#479]
Hi,

The readthedocs page only has HTML download option:
https://flask-smorest.readthedocs.io/en/latest/

![image](https://user-images.githubusercontent.com/15717136/227709967-357efcf2-1bb1-4efb-a1f1-4050f7414f58.png)

Any chance you could enable the PDF download option too - should look like this:
![image](https://user-images.githubusercontent.com/15717136/227710060-e70f2ab3-30b8-45c1-b158-2496f95e5e40.png)

Thanks!

**Comment by lafrech** [comment]
Why not?

I just enabled pdf and epub compilation.
