### ISSUE TITLE
Customizable docstring ignore tag

### ISSUE THREAD

**Issue by dougthor42** [marshmallow-code/flask-smorest#49]
# Summary

The string that stops docstring parsing (`---`) should be customizable.

# Details

According to [the docs](https://flask-rest-api.readthedocs.io/en/stable/openapi.html#add-documentation-information-to-the-view-functions), "the part of the docstring following the `'---`` line is ignored."

This is normally great, but can cause issues when using some docstring styles such as [NumPyDoc](https://numpydoc.readthedocs.io/en/latest/format.html#sections).

The separator value should be user-customizable via flask config value, perhaps `OPENAPI_DOCSTRING_SEP` or something like that.

## Current Behavior

```python
def get(...):
    """
    Find pets by ID.

    Return pets based on ID.

    Parameters
    ----------
    pet_id : int
        The PK for the pet to query

    Returns
    -------
    dict : :class:`orm.Pet`
        A dict representation of the pet instance. When returned via flask, is
        passed through :func:`flask.jsonify`.
    """
```

will be mangled to:

```python
{
    'get': {
        'summary': 'Find pets by ID.',
        'description': 'Return pets based on ID.\n\nParameters',
    }
}
```

Note the "Parameters" string in the description.

## Expected Behavior

```python
app = Flask('My API')
app.config['OPENAPI_VERSION'] = '3.0.2'
app.config['OPENAPI_DOCSTRING_SEP'] = "Parameters"
api = Api(app)
```

```python
def get(...):
    """
    Find pets by ID.

    Return pets based on ID.

    Parameters
    ----------
    pet_id : int
        The PK for the pet to query

    Returns
    -------
    dict : :class:`orm.Pet`
        A dict representation of the pet instance. When returned via flask, is
        passed through :func:`flask.jsonify`.
    """
```

```python
{
    'get': {
        'summary': 'Find pets by ID.',
        'description': 'Return pets based on ID.',
    }
}
```

# Implementation Notes

Any string should be acceptable as a separator. In addition, the `None` value should also be accepted. If the separator is `None`, then the entire docstring is included in the swagger details.

It looks like this docstring parsing is done in [utils.load_info_from_docstring](https://github.com/Nobatek/flask-rest-api/blob/master/flask_rest_api/utils.py#L35). I haven't investigated much further than that, but it looks like it might be pretty easy to implement.

**Comment by dougthor42** [comment]
BTW I do plan on submitting a PR for this, so there's not much for you to do.

If you have any tips or requests I'm more than happy to hear them.

**Comment by lafrech** [comment]
I don't have a strong objection to making this customizable, but just to be sure we get this right...

> app.config['OPENAPI_DOCSTRING_SEP'] = "Parameters"

What if the function takes no parameter? Could the docstring look like

```py
def get(...):
    """
    Find random Pet.

    Return pet.

    Returns
    -------
    dict : :class:`orm.Pet`
        A dict representation of the pet instance. When returned via flask, is
        passed through :func:`flask.jsonify`.
    """
```

We could accept a list of separators ("Parameters", "Responses"), but I'd rather not make things too complicated. Especially since AFAIU, the goal is to adhere to a specific docstring convention but there is no functional impact.

You could add the `---` separator in your code, but I suppose you don't want that because it breaks the convention.

Also beware of 

```py
def get(...):
    """
    Find pets by ID.

    Parameters can be blah blah blah and this line will screw up the parsing.

    Return pets based on ID.

    Parameters
    ----------
    pet_id : int
        The PK for the pet to query

    Returns
    -------
    dict : :class:`orm.Pet`
        A dict representation of the pet instance. When returned via flask, is
        passed through :func:`flask.jsonify`.
    """
```

As per how to do it, I wouldn't make it a flask config value because
- this is not a config parameter for the application, so it can be hardcoded, there's no need to expose it to the end user deploying the application
- the parsing happens in `Blueprint` before the flask app is instantiated

It could be a `Blueprint` class attribute, passed to the utils func. (flask-rest-api already offers a few customization possibilities using class attributes in **`Blueprint` or `Api` (and mixins)).

**Comment by dougthor42** [comment]
> the parsing happens in `Blueprint` before the flask app is instantiated

Ah, very good point. Yes, a flask config value won't work.

You also bring up a good point about not having a "Parameters" section (or in general, not having the separator at all). I agree that setting a list of separators (eg: `["Parameters", "Returns", ...]` will make things too complicated, especially for such little benefit.

What if we simply allow the separator to be nothing? Perhaps something like:

```python
def load_info_from_docstring(docstring, sep="---"):
    """Load summary and description from docstring"""
    split_lines = trim_docstring(docstring).split('\n')

    # Optionally enforce things
    assert sep in ("---", None)

    # Info is separated from rest of docstring by a `sep` string
    for index, line in enumerate(split_lines):
        if sep is not None and line.lstrip().startswith(sep):
            cut_at = index
            break
    else:
        cut_at = index + 1

    split_info_lines = split_lines[:cut_at]
    ...
```

> You could add the `---` separator in your code, but I suppose you don't want that because it breaks the convention.

Correct. I also build docs using Sphinx with reStructuredText, and having `---` cause errors (since that's supposed to be part of section title)

**Comment by lafrech** [comment]
> What if we simply allow the separator to be nothing?

At this point, we might as well make it configurable. Just like in your example, but without the `assert`.

The whole docstring would appear in your spec. Fine with me if that suits you.

Would you like to submit a PR with your change and a test?

I'd check `if sep is not None` outside the loop. Like

```py
if sep is not None:
    for index, line in enumerate(split_lines):
        [...]
    split_lines = split_lines[:cut_at]
```

Then work on `split_lines`.

**Comment by lafrech** [comment]
@dougthor42 are you still interested in implementing this?

**Comment by dougthor42** [comment]
Thanks for the ping. TBH I'd all but forgotten about it.

I'll take another look at it right now.
