### ISSUE TITLE
grafana + Prometheus + smorest integration

### ISSUE THREAD

**Issue by justfortest-sketch** [marshmallow-code/flask-smorest#491]
how could we integrate grafana and Prometheus with smorest? is there easy solution for it? or is there something to monitor smorest? Prometheus is well integrated with flask-restful?!

**Comment by TheBigRoomXXL** [comment]
[Open Telemetry](https://opentelemetry.io/docs/what-is-opentelemetry/) is probably the solution you are looking for as it is the standard for observability. It comes with auto-instrumentation for [Flask](https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/flask/flask.html) and [other library](https://opentelemetry-python-contrib.readthedocs.io/en/latest/index.html) wich allows for an easy integration. It also supports logs and traces if you want more than metric.

Open Telemetry can be a little overwhelming at as it can be used in a lot of different ways and support many features but there are a lot of resources online and if you already have experience with Prometheus it should not be too complicated to setup metrics.

**Comment by lafrech** [comment]
Closing this as not an issue. Feel free to comment to share findings.
