### ISSUE TITLE
Exception after upgrading 0.13.1 -> 0.14.0

### ISSUE THREAD

**Issue by asyncee** [marshmallow-code/flask-smorest#52]
Hello.

Function `flask_rest_api/utils.unpack_tuple_response` checks that result returned is a tuple and tries to unpack it.

This is not working if i'm returning tuple-like object, for example sqlalchemy result object (which can be a tuple subclass) or namedtuple. All this objects pass `isinstance(rv, tuple)`.

**Comment by lafrech** [comment]
Hi.

Thanks for reporting.

I knew this could happen eventually, but I figured since I copied that check from flask's [`make_response`](https://github.com/pallets/flask/blob/master/flask/app.py#L1952) anything that works in Flask works in flask-api-spec.

In other words, AFAIU, returning a tuple doesn't work in vanilla Flask either, does it?

I'm a bit surprised sqlalchemy default return type is not compatible with Flask. But I'd rather stick with Flask for simplicity.

What do you think?

**Comment by asyncee** [comment]
I got your point and it makes sense.

I wrote an example to prove that you are right:

```python
from flask import Flask, jsonify
# instances of this class are returned from some specifically-built sqlalchemy queries
from sqlalchemy.util import KeyedTuple   

app = Flask(__name__)


@app.route('/manual')
def manual_serialization():
    # in vanilla flask you are forced to serialize result manually
    result = KeyedTuple([1, 2, 3], labels=["one", "two", "three"])
    assert isinstance(result, tuple)
    return jsonify({
        'one': result.one,
        'two': result.two
    })

@app.route('/no_serialization')
def no_serialization():
    # returning result of type tuple will not work in flask, giving a TypeError (int is not callable)
    result = KeyedTuple([1, 2, 3], labels=["one", "two", "three"])
    assert isinstance(result, tuple)
    return result

app.run()
```

But my original usecase was using marshmallow schema to serialize response, so this code worked correctly in 0.13.1:

```
@app.route(...)
@blueprint.response(SomeMarshmallowSchema)
def func():
       result = KeyedTuple([1, 2, 3], labels=["one", "two", "three"])
       assert isinstance(result, tuple)
       return result
```

It worked because there was no `isinstance` check. KeyedTuple is a subclass of tuple that allows dotted access and has some pretty string representation.

Right now i have pretty big codebase that is using flask-rest-api and it is broken by 0.14 in some random places where such complex data types is returned.

I understand that 0.X is not stable at all and surely can update my codebase, but i'm not sure if returning subclasses of tuple plays nicely with flask-rest-api's serializer usage pattern.

**Comment by asyncee** [comment]
One more example with named tuple to demonstrate a problem:

```python
from flask import Flask, jsonify
from collections import namedtuple

app = Flask(__name__)

R = namedtuple('R', 'a, b')

@app.route('/named-tuple')
def named_tuple():
    # This will also raise an exception in 0.14 and vanilla flask, but not in 0.13
    return R(1, "test")


app.run()
```

**Comment by asyncee** [comment]
And one more example with flask-rest-api:

```python
from flask import Flask
from flask.views import MethodView
import marshmallow as ma
from flask_rest_api import Api, Blueprint, abort
from collections import namedtuple

app = Flask('My API')
app.config['OPENAPI_VERSION'] = '3.0.2'
api = Api(app)

Pet = namedtuple('R', 'a, b')


blp = Blueprint(
    'pets', 'pets', url_prefix='/pets',
    description='Operations on pets'
)

class PetSchema(ma.Schema):
    a = ma.fields.Integer()
    b = ma.fields.String()

@blp.route('/')
class Pets(MethodView):

    @blp.response(PetSchema)
    def get(self):
        """List pets"""
        return Pet('1', 'test')

api.register_blueprint(blp)

app.run()
```

This gives:

```
http GET http://127.0.0.1:5000/pets/

http: error: ConnectionError: ('Connection aborted.', BadStatusLine('HTTP/1.0 0 test\r\n',)) while doing GET request to URL: http://127.0.0.1:5000/pets/
```

**Comment by lafrech** [comment]
Right. My reasoning was flawed. There are view function outputs that are incompatible with Flask but are acceptable by a marshmallow schema.

I don't see an ideal solution to this. I could revert the "accept result, code, headers tuple" feature but that would suck as I see no elegant alternative.

AFAIK, there can be two kinds of tuples.

- Named tuples act likes objects (attribute access).
- Basic tuples are like immutable lists.

We could 

- Exclude named tuples from the test `(isinstance(rv, tuple) and not isinstance(rv, namedtuple))`.
- Expect users to cast normal tuples to lists `return list(my_tuple)`.

It sounds a bit hackish but, unless we figure out a better way to pass headers, it could be an acceptable compromise.

Do you agree with this?

Would you like to submit a PR?

**Comment by asyncee** [comment]
I think the best way is to remove ability to return flask-acceptable tuple. It can be compensated by using Response class easily and will not break anything.

In the end, i think that flask-rest-api has the right to be incompatible with flask in this specific moment.

What do you think?

I can do a PR on a next holidays :)

**Comment by lafrech** [comment]
Returning a `Response` object adds a bit of boilerplate. Not a deal breaker, but I'd rather offer an alternative. Also, it doesn't work with the pagination decorator.

> In the end, i think that flask-rest-api has the right to be incompatible with flask in this specific moment.

Yes, absolutely. I just didn't find a nice way to achieve the same and I thought doing like flask would be fine.

**Comment by asyncee** [comment]
I'll think about a better way. Also, i'll check how pagination decorator works (did not use it yet).

I suggest you to think what is more useful for end users: have an ability to return a "flask" tuples or an ability to let the view automatically serialize response without boilerplate (for me this is a killer-feature) using a schema.

**Comment by asyncee** [comment]
@lafrech i think we can solve this issue completely by doing straight type check:

```
# File flask_rest_api.utils.py

# Copied from flask
def unpack_tuple_response(rv):
    """Unpack a flask Response tuple"""

    ...

    # unpack tuple returns
    - if isinstance(rv, tuple):
    + if type(rv) == 'tuple':

    ...
```

I think it's okay to check for exact type, because we absolutely sure that it must be tuple.

Let me know what you think.

**Comment by lafrech** [comment]
This is close to what I suggested (exclude `namedtuple`). The difference is how we treat `tuple` children classes that are not `namedtuple` children. I don't expect much of those.

Anyway, I'm fine with the type check approach. At least for a bugfix until maybe someone comes up with a better solution to this.

**Comment by asyncee** [comment]
Cool, i'll do a PR when i'll have a time ;)

**Comment by asyncee** [comment]
By the way it is very convenient to return sqlalchemy query results (some of them can be a tuple subclasses) from view function :) There can be many unnoticed use cases for returning tuples in real projects i think :)

**Comment by lafrech** [comment]
Thanks for investigating this.

You mean tuple subclass but not namedtuple? Interesting. I've been using sqlamchemy once but I'm not familiar with it. Out of curiosity, could you show me a use case returning such a tuple subclass?

**Comment by asyncee** [comment]
You can see examples in my previous messages. Also this is stated in documentation https://docs.sqlalchemy.org/en/latest/orm/query.html#sqlalchemy.util.KeyedTuple

Example query:
```
Using orm:
rows = sess.query(Foo.a, Foo.b, Foo.c).all()
```

Also sqlalchemy core returns lists and tuples too.

**Comment by lafrech** [comment]
OK, this one acts somewhat like a namedtuple but is not a namedtuple. Good. Let's go for direct type check.

**Comment by asyncee** [comment]
Oh, i'm sorry that i forgot about this issue completely due to being very busy at work for a few weeks.

Thank you very much for keeping an eye on it!
