### ISSUE TITLE
Fix base path when script root present

### ISSUE THREAD

**Issue by revmischa** [marshmallow-code/flask-smorest#55]
Same as flask_apispec's issue: https://github.com/jmcarp/flask-apispec/pull/125/files

The application may be deployed under a path, such as when deploying as a serverless lambda. The path needs to be prefixed.

**Comment by lafrech** [comment]
I've been reading about `APPLICATION_ROOT` and `SCRIPT_NAME`

- https://stackoverflow.com/a/18967744/4653485
- https://github.com/pallets/flask/issues/1714
- https://github.com/Larivact/flask/commit/2995366dde63b8acd1f246bcd5a4cf7d61f0c1fa

and the whole thing is still blurry to me.

We mount our applications under a subpath in our WSGI containers (e.g.: domain.tld/api/v0/). We do this in the apache configuration.

```apache
    WSGIDaemonProcess my-app-api-v0 threads=5
    WSGIScriptAlias /api/v0 /path/to/my-app/application.wsgi process-group=my-app-api-v0 application-group=%{GLOBAL}

    <Location /api/v0>
        WSGIProcessGroup my-app-api-v0
        Require all granted
    </Location>
```

IIUC, we don't need to set `SCRIPT_NAME` in this config because WSGI can handle that. Setting `APPLICATION_ROOT` only serves the purpose of restricting cookies to the application subdomain, but I'm not sure about that.

Still IIUC, `SCRIPT_NAME` would be useful if WSGI itself did not know where the application lies.

Should we assume the application is at `SCRIPT_NAME + "/" + APPLICATION_ROOT` or is there a priority of one on the other?

To anyone with a better understanding, clarification welcome.

In #56, it looks like rather than using `APPLICATION_ROOT` and `SCRIPT_NAME` to define the base path, you resolve that at runtime by accessing `request.url_root`. Is this the idea?

Note that when using OAS2, flask-rest-api automatically adds `basePath` to the docs according to `APPLICATION_ROOT` already.

In apispec, we removed all `basePath` related logic. I'm tempted to do the same in flask-rest-api and assume the user should do that manually (using `API_SPEC_OPTIONS`), especially since there's no way to do it automatically for OAS3 in the general (multi-server) case.

**Comment by revmischa** [comment]
My use case is deploying a serverless lambda (using this template: https://github.com/jetbridge/sls-flask) - it gets deployed at /dev/* on AWS lambda. If I try to use swagger UI, all the requests are pointed at /api/v1/foo instead of /dev/api/v1/foo and are incorrect. This patch makes it work. Maybe there is a better way to fix this.

It would be good if the application could specify additional servers.

**Comment by lafrech** [comment]
You can use `API_SPEC_OPTIONS` to pass that manually, for now.

**Comment by revmischa** [comment]
Setting it at configure time isn't so simple. I don't know how to get this value when the application starts up, only during a request context. How would I get the script root when configuring?

**Comment by lafrech** [comment]
I'm sorry, I don't get it. I don't know "Serverless AWS".

You meant it may not be `/dev/api/v1/`? Is it not predictable?

**Comment by revmischa** [comment]
I want the application to configure it automatically. How can I do that without a request context? How would I predict it?

**Comment by lafrech** [comment]
I'm reluctant to do anything until I find answers to https://github.com/Nobatek/flask-rest-api/issues/55#issuecomment-481249349.

I might be misunderstanding, but your use case looks like a corner case that may not fit into the lib. Spec options can also be passed programmatically at `Api` init, so perhaps you could add some code in your app to open a request context, get the base url, then pass it to `Api`. I hope I'm making sense.

**Comment by revmischa** [comment]
Well, I guess that depends if the WSGI environment contains the script root at startup time. I have no idea if it does. Right now I get it from `flask.request.url_root`
Deploying flask to AWS Lambda is not, in my humble opinion, an edge case. 
Basically all web applications since the days of FastCGI have had the option and capability to be deployed "under" a path, not as the root URL. 
I think to make this nicer, we should check and see if the info is available in WSGI environment at startup time... I have no clue right now

**Comment by revmischa** [comment]
Anything I can do to help resolve this?

**Comment by lafrech** [comment]
Sorry, I had no time to look into this.

> I guess that depends if the WSGI environment contains the script root at startup time
> I think to make this nicer, we should check and see if the info is available in WSGI environment at startup time... I have no clue right now

That would be much better than checking on each request.

And you could then set the path at startup when initializing the app.

Do you think you could investigate this?

> Deploying flask to AWS Lambda is not, in my humble opinion, an edge case.

Agreed. I just find it weird to rely on the code itself to know where it is served. I'd assume the environment should be able to provide that information to the app, one way or another. So if it is possible, I'd rather rely on this than add a trick in this lib to get it.

**Comment by lafrech** [comment]
I read the references in https://github.com/Nobatek/flask-rest-api/issues/55#issuecomment-481249349 a few times and I still find the whole thing a bit complicated.

At this point, maybe asking on SO would be an appropriate option.

**Comment by revmischa** [comment]
I checked the environment on lambda startup but there's no relevant info in there. I think lazily setting the current path prefix is the only way to go

**Comment by revmischa** [comment]
Having investigated the info provided at application startup time via WSGI environment I believe my solution is the most appropriate. 
It works, I've been using it for projects in our fork, and I haven't heard any other ideas. The current behavior is broken in any environment where the application is not deployed at the root path. 

I would like to use the upstream/pypi version instead of my fork. If you have no objections then maybe we can merge #56 ?

Thanks! 🐶

**Comment by jcbdev** [comment]
I have this exact same issue and would appreciate @revmischa's code being merged!

**Comment by jcbdev** [comment]
workaround to monkey patch before you create your app/api.

```
"""
-------------------------------------------------------------------------------------------------------------
This is a monkey patch for issue - https://github.com/marshmallow-code/flask-smorest/pull/56 / https://github.com/marshmallow-code/flask-smorest/issues/55

Needed when deployed behind an api gateway which adds a url prefix such as /dev

TODO - Remove when bug is fixed in flask-smorest
"""
import flask
from flask import current_app

def _openapi_json_fix(self):
    """Serve JSON spec file"""
    # We don't use Flask.jsonify here as it would sort the keys
    # alphabetically while we want to preserve the order.
    self._fix_base_path()
    return current_app.response_class(
        json.dumps(self.spec.to_dict(), indent=2),
        mimetype='application/json')

def _fix_base_path(self):
    """Lazily set OpenAPI servers for each request.
    This is to reflect the path root the application is running under.
    c.f. SCRIPT_NAME https://www.python.org/dev/peps/pep-0333/#environ-variables
    """
    if not flask.has_request_context():
        # not in request
        return
    # TODO: allow configuration of more servers.
    servers = [{
        'url': flask.request.url_root,
    }]
    self.spec.options['servers'] = servers

import flask_smorest.spec
flask_smorest.spec.DocBlueprintMixin._openapi_json = _openapi_json_fix
flask_smorest.spec.DocBlueprintMixin._fix_base_path = _fix_base_path
"""
-------------------------------------------------------------------------------------------------------------
"""
```

**NOTE: Does not work if flask-smorest is hosted in a lambda layer**

**Comment by lafrech** [comment]
Thanks.

I still don't understand.

For a given instance on a given server, you know that the URL is prefixed with `/dev`, don't you?

Couldn't you pass this as a config parameter (a new one, if needed) rather than adding this runtime logic here?

**Comment by jcbdev** [comment]
@lafrech In my case I can because I am using terraform to deploy and I can tell where I am deploying it to and set a environment variable.

If i do this, what setting do I need to set when I pull back the env variable in the code?

**Comment by lafrech** [comment]
Well if you can figure out at deployment time what the server address will be, you can use `API_SPEC_OPTIONS` (see [docs](https://flask-smorest.readthedocs.io/en/stable/openapi.html#populate-the-root-document-object)) to pass the correct value.

```py
app.config['API_SPEC_OPTIONS'] = {'server': '/dev/...'}
```

If you could figure it out at init time, you could do


```py
api = Api(app, spec_kwargs={'server': '/dev/...'})
```

**Comment by revmischa** [comment]
> For a given instance on a given server, you know that the URL is prefixed with /dev, don't you?

This is for serverless deployments. There is no webserver, there is only [API gateway](https://aws.amazon.com/api-gateway/). The app can be deployed to various base path mappings and API gateways.

**Comment by jcbdev** [comment]
> ```python
> app.config['API_SPEC_OPTIONS'] = {'server': '/dev/...'}
>
> spec_kwargs={'server': '/dev/...'}
> ```

@lafrech Neither of these work in setting the server property in the specs.

openapi.json is still served without the prefix

Correction: I can see the "server" property is set *inside* openapi.json but openapi.json is not served from /dev/doc/openapi.json and the server dropdown in swagger is not available (which is it with @revmischa's code above

further Correction:  the structure is {'servers': { 'url' : 'http://localhost/dev' } }

So that works

**Comment by lafrech** [comment]
Just noticed my proposal was a bit incorrect. It should be more like

```py
app.config['API_SPEC_OPTIONS'] = {'servers': [{'url': '/dev/...'}]}
```

This is out of my head (and your code sample). I didn't test it. It should put the correct value in the json doc.

Regarding the URL serving the page, I don't see how it could be affected by #56. I guess you could set `OPENAPI_URL_PREFIX` and below parameters in [the docs](https://flask-smorest.readthedocs.io/en/stable/openapi.html#serve-the-openapi-documentation) according to your prefix.

**Comment by jcbdev** [comment]
@revmischa @lafrech 

I managed to solve this properly by doing this outside of flask-smores and it works perfectly

First I changed my lambda_handler by adding a wrapper for aws_lambda_wsgi that sets the headers/environ correctly:

```
def lambda_handler(event, context):
    if event == {}:
        raise Exception(
            'event empty, have you enabled lambda proxy integration? its in api gateway integration request on the resource?')

    event['headers']['X-Forwarded-Prefix'] = "/" + event['requestContext']['stage']

    def wrap_app(environ, sr):
        environ['SCRIPT_NAME'] = "/" + event['requestContext']['stage']
        return app(environ, sr)

    return aws_lambda_wsgi.response(wrap_app, event, context)
```

I also added ProxyFix from Flask (I haven't checked if this is needed but it works:
```
app = Flask("Orchestration Api")
app.wsgi_app = ProxyFix(app.wsgi_app)
```
@revmischa this works for me at any api gateway stage and deployed to any host without config required.

**Comment by lafrech** [comment]
Thanks @jcbdev for sharing this.

I'm not familiar with this kind of deployment, so I don't grasp all the implications. Do you consider this the way to go or does it feel like a workaround to you? Sounds fine to me. Just asking in case there would still be something flask-smorest should do about it.

**Comment by lafrech** [comment]
Slightly related to https://github.com/Redocly/redoc/issues/1172.

**Comment by lafrech** [comment]
I'm removing automatic `basePath` and making it a user parameter (#242).
