### ISSUE TITLE
APIspec error when using two-way schema nesting

### ISSUE THREAD

**Issue by revmischa** [marshmallow-code/flask-smorest#57]
I'm using marshmallow v3-rc5 and using [two-way nesting](https://marshmallow.readthedocs.io/en/latest/nesting.html#two-way-nesting)
Using this technique I get the following error if I attempt to use something like `@blp.response(CreatorSchema(many=True, exclude=('follower_count',)))`:
```
/Users/cyber/.virtualenvs/luve-pim5aQIP/lib/python3.7/site-packages/apispec/ext/marshmallow/common.py:143: 
UserWarning: Multiple schemas resolved to the name Creator. The name has been modified. Either manually add each of the schemas with a different name or provide a custom schema_name_resolver.

```
and see multiple versions of the schema in swagger (Creator, Creator1). 

If I remove the `exclude` arg to my schemas and make new schemas then everything works perfectly. Something about `exclude` causes it to think there are multiple versions of the schema and it all explodes.

**Comment by svidela** [comment]
Hi,

You may want to take a look at #38.

Regards,

**Comment by lafrech** [comment]
> Something about exclude causes it to think there are multiple versions of the schema

Indeed. From an API perspective, excluding a field makes it a different schema, therefore another reference in the spec.

The easiest way around this would be to declare a different schema with an explicit different name.

The autoreference feature is very useful but it has a few shortcomings and this case is one of them. I understand it can be frustrating as excluding fields on-the-fly like you do in your call to `@response` looks neat, but we found no easy way to get the best of both world.

Maybe one could write a complicated `schema_name_resolver` that would manage this case transparently but unless you use schema modifiers (`exclude`,...) extensively and you really want to minimize the boilerplate, you're better off just creating a second schema.

```py
class CreatorNoFollowerCountSchema(CreatorSchema):
    class Meta:
        exclude=('follower_count',)
```

**Comment by lafrech** [comment]
Of maybe you're happy with the way apispec generates different names (Creator, Creator1), and perhaps you could just try to deactivate the warning globally.

Do you think we should make this a custom warning to ease filtering and/or add an opt-in parameter to skip this warning? If so please open an issue in apispec (https://github.com/marshmallow-code/apispec/issues).

**Comment by lafrech** [comment]
Closing this as I don't think it is a flask-rest-api issue.

@revmischa if you're still interested in this, please see my comment above and perhaps post an issue in apispec bugtracker.

**Comment by revmischa** [comment]
I don't really mind the extra names, just the warnings. Will do, thanks!
