### ISSUE TITLE
How can i create pagination for method POST

### ISSUE THREAD

**Issue by garu097** [marshmallow-code/flask-smorest#575]
Because my api too many queries so i want to change method from GET to POST and use it only in request body.
But it seems like @blp.paginate() not support
Any help is appreciate. Thanks!

**Comment by lafrech** [comment]
I'm sorry I don't understand what you are trying to achieve.

**Comment by lafrech** [comment]
Oh, I get it. Your resources involves many query arguments and you want to use `POST` to pass them in body instead.

I don't think there's anything preventing the use of `paginate` on `POST` requests.

Closing this for lack of feedback. Feel free to reopen with details about what exactly fails.
