### ISSUE TITLE
Arguments in header

### ISSUE THREAD

**Issue by mekanix** [marshmallow-code/flask-smorest#62]
I tried using `@blueprint.arguments(PetSchema, location='headers')` and I tried with `location='headers'` in the schema field declaration without result. What is the proper way to use arguments in the headers? Thank you!

**Comment by lafrech** [comment]
This should work.

```py
@blueprint.arguments(PetSchema, location='headers')
```

What's wrong? Parameter not documented? Not injected in view function?

The documentation of the parameter is tested for all possible locations in `test_blueprint_arguments_location`.

I don't see why the parameter wouldn't be injected.

Do you think you could investigate? Provide a minimal test case?

Thanks.

**Comment by mekanix** [comment]
I tested with GET method, which I forgot to mention. I have free time and (I hope) knowledge to at least narrow it down. For now it seams like a swagger problem, but I'll report back when I figure out more.

**Comment by mekanix** [comment]
I have example repo where I experiment with flask-rest-api. Strange thing is that I downloaded swagger files from https://cdnjs.com/libraries/swagger-ui and I have to set `OPENAPI_VERSION = 2.0.0` otherwise swagger complains it doesn't see the version. The whole config is https://github.com/mekanix/backend-startkit/blob/master/common_config.py. Downloaded files are at https://github.com/mekanix/backend-startkit/tree/master/application/static/swaggerui. With that, `location='headers'` works, but the `default` keyword in schema is ignored.
