### ISSUE TITLE
How to allow alternative response schema eg. for 4xx status codes

### ISSUE THREAD

**Issue by koko236** [marshmallow-code/flask-smorest#663]
I have endpoints defined with Marshmallow schemas, eg.:

```python
    @blp.response(200, ProjectSchema)
    def get(self, project_uuid):
        '''
        Get project by uuid
        '''
        project = projects_service.get_project_by_id(project_uuid)
        if project is None:
            return {'message': 'Project not found'}, 404
       # ...rest of the function...

```

The problem is when I return 404 the json is empty because (I assume) 'message' key gets stripped by ProjectSchema. When I comment out `@blp.response` line I can get the message error as intended. I tried creating ErrorSchema:

```python
class ErrorSchema(ma.Schema):
    '''
    Error schema
    '''
    message = ma.fields.String(required=True, metadata={'description': 'The error message'})
```

And alt_response as follows:
```python
@blp.alt_response(404, schema=ErrorSchema(unknown=ma.EXCLUDE))
```
But it doesn't help. What is the correct way of handling such a scenario?

**Comment by lafrech** [comment]
Use `abort`.

This should work:

```py
    from flask_smorest import abort
    from flask_smorest.error_handler import ErrorSchema


    @blp.response(200, ProjectSchema)
    # I woudn't bother documenting the 404 but if you want to do so, uncomment
    # @blp.alt_response(404, schema=ErrorSchema)
    def get(self, project_uuid):
        '''Get project by uuid'''
        project = projects_service.get_project_by_id(project_uuid)
        if project is None:
            abort(404)
            # I'd use the default message but you may override it
            # abort(404, message="Project not found")
       # ...rest of the function...
```

**Comment by koko236** [comment]
Thanks a million! 👍🏿 

So just to clarify, as discussed here: (https://github.com/marshmallow-code/flask-smorest/issues/166) the ONLY way to trigger alt response schema is by using `abort` method and if we `return` response then no matter what HTTP status is set the main response schema will be used, right?

**Comment by koko236** [comment]
For posterity, please note that you should import `abort` from `flask_smorest` and not from `flask` ;-)

**Comment by lafrech** [comment]
The `response` decorator dumps with the schema unless the flow is broken 
(abort, exception, etc.) and the function does not return, or the 
function returns a `Response`.

The `alt_response` decorator does nothing at runtime, it just helps 
documenting responses other than the "normal" one.

**Comment by koko236** [comment]
> The `alt_response` decorator does nothing at runtime, it just helps
documenting responses other than the "normal" one.

That's very good to know as well, thank you! I missed "does nothing at runtime" part and was expecting that if I define `@alt_response` with a different http code, then returning the alt object with alt http code will work the same as `@response` decorator. I think if exactly this quote was added [here](https://flask-smorest.readthedocs.io/en/latest/response.html#:~:text=Those%20alternative%20responses%20can%20be%20documented%20using%20the%20Blueprint.alt_response%20decorator) (which reading now with my new knowledge is technically true :-) ) it would clear that up.    

Ok, so in regular case I return an object and Marshmallow will take care of dumping it into response, but in case of the alt response I have to manually dump with Marshmallow and return a Response? Out of pure curiosity, is there a reason behind it or is just something out of scope?
