### ISSUE TITLE
flask_classful support

### ISSUE THREAD

**Issue by connebs** [marshmallow-code/flask-smorest#7]
I use [flask_classful](https://github.com/teracyhq/flask-classful) in some of my projects, and it would be great if it was supported.

I'll need to dig into the code a bit more, but I'm fairly certain flask_classful's main export, `FlaskView`, is fairly similar in implementation to the now standard `Flask.MethodView` (which is already supported). 

Would this be something that could be integrated into the project?

**Comment by lafrech** [comment]
I'm a bit reluctant to add a dependency to flask_classful, or flask_classy, or such.

Or even this kind of code.

```py
try:
    import flask_classful
    FLASK_CLASSFUL_AVAILABLE = True
except ImportError:
    FLASK_CLASSFUL_AVAILABLE = False
```

This wouldn't add a strict dependency, but I'd rather not scatter references to all sorts of flask extensions in the code.

There could be another way, like adding hooks, or a generic class that a user could use to proxy his some-flask-extension-view-class.

Can you elaborate on the benefits of using flask_classful in this REST API context? Does it remove any more boilerplate than flask-rest-api over Flask `MethodView` already does?

Thanks.

**Comment by connebs** [comment]
> Can you elaborate on the benefits of using flask_classful in this REST API context? 

Sure. Overall, flask_classful's `FlaskView` is just a lot more powerful than `MethodView` out-of-the-box.

More specifically, one of the main things I use it for is so that I can define my own custom routes which are not tied to specific HTTP methods.

As an example, I have a `FlaskView` for my entire user API, called `UserInterface`.
In addition to having the method view functions, which predictably: get a user, create a user, update a user, and delete a user; I have other methods such as `change_email`. This allows for good organizational structure, as my URI base for that part of the api (`user/`) only needs to be specificied once as a class attr of my `FlaskView`:

```
class UserInterface(FlaskView):
    route_base = "user/"
    base_args = ["wargs"]

    @route('/change-email', methods=['POST'])
    @[flask_rest_api.Blueprint].arguments(UserSchema)
    def change_email(self, wargs):
        # do change email
```

The above route is accessed from `/user/change-email`, as expected. This is obviously great for organization/readability, as it allows for *the entirety* of my API sectioned off into self-contained `FlaskView`s, which can contain **all** routes related to that part of the API, not just the bog-standard HTTP method routes.

Another nice part about `FlaskView`s is that they treat the `index()` view function as a 1st class citizen, with the understanding that typically when you make a GET request to `user/`, you want to get back a list of users, while `/user/<ID>/` returns a specific user. So my `index()` function returns a list of users, while the `get()` function of my `FlaskView` takes in a `user_id` as part of the route, and returns that user.

```
class UserInterface(FlaskView):
    route_base = "user/"
    
    @Blueprint().response(UserSchema(many=True))
    def index(self):
        return users

    @Blueprint().response(UserSchema)
    def get(self, user_id : int):
        return users[user_id]
```

There are other things I find convenient about flask_classful's `FlaskView` over `MethodView`, but those are the highlights. Overall, it makes my API code cleaner and more sensible than any other method I've tried.

**Comment by lafrech** [comment]
I didn't give it much thought, but perhaps you could just subclass `Blueprint` and override `_store_endpoint_docs` to support `FlaskView`. I could take `store_method_docs` out if it helps reducing duplication.

```py
class FlaskClassfulBlueprint(flask_rest_api.Blueprint):

    def _store_endpoint_docs(self, endpoint, obj, **kwargs):
        """Store view or function doc info"""

        if isinstance(obj, FlaskView):
            # Do what need to be done: iterate over methods and call store_method_docs
            [...]
        else:
            super()._store_endpoint_docs(endpoint, obj, **kwargs)
```

There may be a tricky part as IIUC, a FlaskView can correspond to multiple paths since for `/pets/` it automatically declares `/pets/<id>` for instance.

You may have to also override `route` and `register_views_in_docs`.

Please tell us how it goes if you give it a try.

**Comment by connebs** [comment]
Thanks for the suggestion! Yes, as both `flask_rest_api` and `flask_classful` are defining their own `route` functions, I'll need to figure out which to use / how I can combine the functionality of both. 

Might need to create a `flask_classful_rest_api` package, haha.

Regardless, I'll keep you updated with any progress I make on this front.

**Comment by connebs** [comment]
Ok, done some work with this, and [here's a Gist of what I've come up with so far](https://gist.github.com/acnebs/d9ab23a29bd149115c25a17023717c55).

Long story short, I subclass `flask_rest_api.Blueprint` and override `Blueprint.add_url_rule` (since this is called by `flask_classful` for every route it creates) and use *that* to add endpoints to the docs, *not* `Blueprint.route`.

It seems to be working alright, my `openapi.json` is generated with actual content now, so that's nice. 

However, I'm no closer to solving the issue I experienced in #6, where `@Blueprint.response` is not playing nicely with my `flask_classful` view functions.

Any ideas for that one? Looking through the respective code, nothing is jumping out at me that would cause this behavior. At least, nothing that would allow `Flask.MethodView` to work but breaks `flask_classful.FlaskView`.

**Comment by lafrech** [comment]
Good. You could override `route` to raise an exception, just in case.

Maybe you other issue is unrelated after all. I have no idea what happens.

Basically,

- `abort(422)` for instance raises an `HTTPError` and the view function is exited and therefore we don't go through the marshaling process.

- webargs abort adds some more info to the raised exception.

- And in flask-rest-api, we set error handlers to catch the exception, potentially enhanced by webarg's abort, and return a response including that useful data formatted as json.

Apparently, something happens in your case that prevents exiting the view function. I can't tell if it is related to Flask-Classful. I don't see why it would, but I don't see any other reason either.

A minified example would help debug this. Maybe also ask on SO if you're stuck there.

**Comment by lafrech** [comment]
@acnebs, did you manage to find a solution to this?

There's been a great deal of changes in flask-rest-api since then. Did it make any difference?

**Comment by lafrech** [comment]
Closing for now. Please comment if you have news about this.

**Comment by connebs** [comment]
I did not find a solution on my own, for a while I just stopped using `@blp.response` for marshalling and did it manually within request bodies. 

However, I've just gone back and ran some samples using `@blp.response` against my tests and it seems to be working, so not sure what changed but it works now!

Thanks again for all the work you've put into this lib.
