### ISSUE TITLE
Document response without specifying schema

### ISSUE THREAD

**Issue by dpmccabe** [marshmallow-code/flask-smorest#70]
I have an endpoint that allows the end user to specify which fields they want returned, which I pass through to the Marshmallow serializer. This is pretty easy to do:

```python
blp = Blueprint('people', 'people', url_prefix='/people',
                description='Operations on people')

class PersonGetArgsSchema(Schema):
    """Query arg schema for people get endpoint"""
    id = fields.String(required=True)
    return_fields = fields.List(fields.String(), required=True)

@api.definition('Person')
class PersonSchema(Schema):
    """Marshmallow schema for serializing a person instance"""
    id = fields.String(required=True, example='3065ac69-6aad-4832-9889-c81ab773424e')
    # other fields

@blp.route('/get')
class PersonResource(MethodView):
    @blp.arguments(PersonGetArgsSchema, location='json')
    @blp.response(None)
    def post(self, body):
        """Get a single person by ID (actually using POST, since REPORT isn't supported)"""

        # get the person from Elasticsearch
        person = PersonDoc.get(id=body['id'], _source=body['return_fields'])

        # serialize and return
        person_schema = PersonSchema(only=body['return_fields'])
        return person_schema.dump(person.to_dict())
```

This works fine, but because I specified `@blp.response(None)`, my API docs don't automatically have an example response like I would if I had `schema=PersonSchema`.

My current solutions is to subclass `Schema`:
```python
class SchemaWithEx(Schema):
    def example_dict(self):
        return {
            k: v.metadata['example'] for k, v in self.fields.items() if 'example' in v.metadata
        }

@api.definition('Person')
class PersonSchema(SchemaWithEx):
    # ...

@blp.response(schema=None, example=PersonSchema(only=['id', 'name']).example_dict())
```

Is my situation really obscure or would it be worth adding a feature like this?

**Comment by lafrech** [comment]
Hi.

I do think this is pretty specific. But I could be proven wrong.

I don't really see what feature flask-rest-api could propose to make this easier. Do you have a more precise idea?

Also, since the `example_dict` method is not specific to this schema but generic to your use case, I'd put it in a `BaseSchema` and let all schemas inherit from it. This sounds like a reasonable compromise. What do you think?

**Comment by lafrech** [comment]
Closing this for now.

Doing it in a `BaseSchema` sounds reasonable to me. If you think there's anything this lib can do to help, please comment.
