### ISSUE TITLE
Swagger UI Env variables being ignroed

### ISSUE THREAD

**Issue by nate3D** [marshmallow-code/flask-smorest#711]
OPENAPI_URL_PREFIX and OPENAPI_SWAGGER_UI_PATH don't seem to be working any more. I have mine set to None and now my swagger-ui is visible at the default /docs/swagger-ui. Nothing I try will remove it and I don't want to have it listed. 

```
class Config:
    # Basic API Information
    API_TITLE = "VelVET Labs API"
    API_VERSION = "v1"
    OPENAPI_VERSION = "3.0.2"
    OPENAPI_URL_PREFIX = None
    OPENAPI_SWAGGER_UI_PATH = None
```

Expected:
No swagger UI accessible via web

Actual:
Swagger UI is accessible at the default /docs/swagger-ui. There doesn't appear to be any other way to disable this option from what I've found.

**Comment by lafrech** [comment]
This is tested explicitly in test_spec.py so it should work as expected.

There might be something in your setup.

Do you think you could try a minimal app in a new environment?

**Comment by nate3D** [comment]
Yeah, I was able to determine the issue with an orphaned container still sitting on an old config. Thanks so much for such a quick turnaround in addressing this!
