### ISSUE TITLE
OpenAPI JSON should use additionalProperties

### ISSUE THREAD

**Issue by jonfreedman** [marshmallow-code/flask-smorest#74]
OpenAPI v3 [supports dictionaries to be specified with a key / value type](https://swagger.io/docs/specification/data-models/dictionaries/).  The following Marshamallow classes produce JSON without that information

```python
@api.schema('Output')
class OutputSchema(ma.Schema):
    class Meta:
        strict = True

    min = ma.fields.Number()
    max = ma.fields.Number()


@api.schema('OutputDict')
class OutputDictSchema(ma.Schema):
    class Meta:
        strict = True

    data = ma.fields.Dict(keys=ma.fields.String(), values=ma.fields.Nested(OutputSchema))
```

Should produce something like this:

```json
      "Output": {
        "type": "object",
        "properties": {
          "min": {
            "type": "number"
          },
          "max": {
            "type": "number"
          }
        }
      },
      "OutputDict": {
        "type": "object",
        "properties": {
          "data": {
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "string"
                },
                "text": {
                "$ref": "#/components/schemas/Output"
                }
              }
            }
          }
        }
```

**Comment by lafrech** [comment]
I think it should work since https://github.com/marshmallow-code/apispec/pull/202.

Looks like you're using Marshmallow 2. The `keys` and `values` arguments in `Dict` were added in Marshmallow 3. In Marshmallow 2, they are just ignored.

In Marshmallow 3, `strict = True` is removed and triggers warnings.

**Comment by jonfreedman** [comment]
Yes I think I was using version 2, I'll try with the latest version 3 pre-release on Tuesday and let you know 


---- On Fri, 24 May 2019 07:12:38 +0000 notifications@github.com wrote ----



I think it should work since marshmallow-code/apispec#202.

Looks like you're using Marshmallow 2. The keys and values arguments in Dict were added in Marshmallow 3. In Marshmallow 2, they are just ignored.

In Marshmallow 3, strict = True is removed and triggers warnings.

**Comment by lafrech** [comment]
Closing this. What you're seeing is normal marshmallow 2 behaviour.

We'll reopen if it doesn't work with marshmallow 3.
