### ISSUE TITLE
Reusable CRUD

### ISSUE THREAD

**Issue by revmischa** [marshmallow-code/flask-smorest#79]
I would like to build a reusable CRUD view class on top of flask-rest-api. I built one previously fairly close to flask-restful's design, and was wondering if anything currently exists or you have tips or suggestions of how to proceed.

The problem I am trying to solve is building the same list/get/update/delete endpoints over and over for various DB models. I want to declare things like access controls, default schema for serialization, what fields are permitted to update, DB model class, relationships to prefetch (i.e. `joinedload`) for list view, and auto-registration of endpoints via `__init_subclass__`.

Anything you'd suggest or like to see? Anything like this exist already on top of flask-rest-api?

**Comment by lafrech** [comment]
Nothing like this exists to my knowledge.

In the applications in which we use flask-rest-api, we do have a large amount of duplication in the views. They look quite like the examples in https://github.com/Nobatek/flask-rest-api/blob/master/tests/test_examples.py.

There seems to be room for factorization, but we never tried that because the duplication is not such an issue, and because there are often subtle differences that make the views not exactly CRUD, so trying to build a meta class could end up being a nigthmare, with patches everywhere to handle specific cases.

This said, if I wanted to address that, I'd probably do it bottom-up: take start from a `MethodView` in my code and make a function that builds it given (as paramters) all the things that differ from one view to another (path, schema and such). Those parameters may differ from one application to another, so this could be application-specific, or at least easier to do in an application, more complicated to achieve in a generic way.

**Comment by revmischa** [comment]
I get what you mean about needing to override details. I've worked with these libraries before in both perl and python, and it's mostly a matter of creating a base class and defining the parameters you mention in class vars, and then having default implementations of the methods list, get, create, update, delete.

**Comment by lafrech** [comment]
Sounds good.

If you come up with something, it is definitely interesting to post it here in a comment.

In fact, now that you raise this, I may be tempted to do something similar in an app of ours.

**Comment by revmischa** [comment]
I'll start working on it and post a link soon.
One thing that would be really helpful: a way to define a "dynamic" arguments/response model by string, that can be evaluated later.

Something like is in Flask-RESTful `Ref` - see https://flask-apispec.readthedocs.io/en/latest/usage.html#inheritance

To allow subclasses to flexibly override parent settings, flask-apispec also provides the Ref helper. Using Ref looks up variables by name on the associated class at runtime. In this example, all methods in the PetResource view class serialize their outputs with PetSchema.

```python
from flask_apispec import Ref

@marshal_with(Ref('schema'))
class BaseResource(MethodResource):

    schema = None

class PetResource(BaseResource):

    schema = PetSchema

    def get(self, pet_id):
        return Pet.query.filter_by(id=pet_id).one()
```

I'll need this to be able to declare schemas in class vars

**Comment by revmischa** [comment]
@lafrech - i sketched out a rough idea of one idea of what it might look something like. want to take a look? if you have ideas, just make a PR 
https://github.com/jetbridge/flask-crud

**Comment by lafrech** [comment]
I had a very quick look. You're onto something.

The code is specific, tied to your database.

Looks like you don't need the `Ref` you're talking about above, do you? I didn't check flask-restful and flask-apispec, so I don't know why they need this, but I see nothing we can't do without it. In fact, I don't see right now what we could add to flask-rest-api to help doing this. AFAIU, the place for this is the application code (or a lib above flask-rest-api if it needs to be shared). Nevertheless, I like the idea.

**Comment by revmischa** [comment]
Can you elaborate on "The code is specific, tied to your database."? The only assumption it makes is that you're using flask-sqlalchemy. It should pick it up automatically

**Comment by revmischa** [comment]
if i could use `Ref`, i could eliminate the need to have the boilerplate `super()` calls. Those calls just apply the decorators in the default case. I would like to apply those decorators without knowing the schema ahead of time.

**Comment by lafrech** [comment]
> The only assumption it makes is that you're using flask-sqlalchemy.

Yes, that's what I meant. It is tied to sql-alchemy (not MongoDB, for instance).

**Comment by revmischa** [comment]
put another way, the app would look more like:
```python

@blp.route("")
class PetCollection(CollectionView):
    model = Pet
    schema = PetSchemaLite
    can_create = True
    can_list = True


@blp.route("/<int:pk>")
class PetResource(ResourceView):
    model = Pet
    schema = PetSchema
    can_update = True
    can_delete = True
```
which i think is a big win.

**Comment by revmischa** [comment]
@lafrech - https://github.com/jetbridge/flask-crud/pull/1
more improvements
trying to figure out how to do access control checks now

**Comment by revmischa** [comment]
https://github.com/jetbridge/flask-crud/pull/2 thoughts?

**Comment by lafrech** [comment]
OK, I understand the use for `Ref`. I don't know how to apply the same mechanism here because it would need to access the `Blueprint` object (where the model and schemas are provided as attributes) rather than the view function that is being decorated.

Here's an example of how I would naively tackle this: https://github.com/lafrech/flask-smorest-sqlalchemy-example/tree/factor_crud.

It uses `Blueprint` methods to create base resource classes bounded to the blueprint. Visually not as nice as the classes in your example above, but it works.

However, as you can see, each modification in a view function requires the whole function to be overridden. This could be fixed by adding other customization arguments to the method creating the resource.

I think this customization is tied to user code, so ultimately this belongs to user code.

There's a tradeoff, here, and in my app, I'm leaning towards keeping the duplication rather than relying on awkward customization and/or overriding a great part of the view functions.

Is there anything you think flask-smorest could provide to help achieving such a feature?

**Comment by lafrech** [comment]
Closing this for now, as it has gone stale. Feel free to re-open if further discussion is needed.

**Comment by zedrdave** [comment]
@lafrech Dunno whether to reopen this or start a new thread.

I ran into something similar a while back and did end up creating my own CRUD blueprint class. Would be happy to try and refactor it into something usable in flask-smorest, if you think this might be of interest.

My approach is similar to @revmischa above (with a few differences)…
- a CRUD class that inherits from flask-smorest's Blueprint
- take a number of class/var names as arguments to define Model, Argument/Response Schema, key etc. With some good default in place (camelcased endpoint name + "Schema" etc) which make it seamless for most cases.
- relying on sqlalchemy for DB operations (I did once implement a variant that handled MongoDB, so both might be possible, but half the code would differ).
- access control is handled separately (I use decorators on classes/endpoints with a permission/rule system) and added to the CRUD class as callbacks.

I think an access-control framework, and a CRUD class, would be two really useful additions to smorest, and decrease cruft/code-repetition hugely. Maybe worth workshopping the needs/implementation details before working on a Pull Request…

**Comment by zedrdave** [comment]
@lafrech What's the status (/interest) on this? I have a bit of free time this week, and would be keen on refactoring our own CRUD class (currently working with flasksmorest in our platform) into a Pull Request…

**Comment by lafrech** [comment]
Hi.

Regarding additional features, I'd rather not add new dependencies or force a specific access control feature/lib on users, especially if it is easy enough to integrate an existing lib in user code (admittedly, it requires a bit of understanding of the internals to get the auto-documentation working, this is addressed in other issues here (e.g. #436)). This deserves a better API and examples with frequently-used libraries.

Regarding CRUD blueprint, as I said I have the feeling, at least in my use cases, that it is not so obvious to provide a nice API, especially if we want it to allow for customization for the cases that are not perfect copy-pastes of a template (which happen to be a lot of cases in practice). But I could be proven wrong, so feel free to provide sample code if only to illustrate your thoughts.

**Comment by zedrdave** [comment]
Indeed, it would be hard to do without adding a layer of ORM to the stack.

And yes: a CRUD blueprint that covers all use-cases would be overkill, but should be fairly easy to provide one that covers a good 90% (that's what we have) of typical SQLAlchemy model + schema + read/write by ID usages… While allowing to simply inherit and override as needed.

I understand your reluctance to adding too many dependencies and becoming too scattered… But I feel that the current generation of Flask REST APIs still requires way too much boilerplate. The vast majority of smorest users are likely already using SQLAlchemy as well, so it would not be a major change (and perhaps would allow  tighter integration with other things, such as authentication).

I guess the alternative would be to separate this class of DB-oriented features in an independent package, but I am not sure how much sense it would make for users (and how doable it might be): as the REST package connecting everything, this seems like a job for flask-smorest.

[edit] I'll clean up a version of my code and post it, so we can discuss it.

It might be useful to have a clear roadmap/guidance list as to where you see the package going, in terms of what it should/shouldn't cover for users.

**Comment by zedrdave** [comment]
@lafrech OK, I have produced a first somewhat-clean version of the code over here, as a standalone package: https://github.com/zedrdave/flask-smorest-sqla/blob/main/flask_smorest_sqla/crud_blueprint.py

Obviously, there are still a lot of possible improvements and extensions that could avoid a lot of boilerplate code. Possibly by integrating a few other standard parts of REST API building (jwt, oauth…).

For now, this seems like it can easily live as a separate package (in the same way we have a dozen packages that are combination of `flask`, `marshmallow`, `sql-alchemy` etc), though I still think it would be nice to have a central go-to package that provides everything one needs to get started with a REST API on Flask, while avoiding the 90% boilerplate…
