### ISSUE TITLE
Add oneOf support

### ISSUE THREAD

**Issue by sjmh** [marshmallow-code/flask-smorest#80]
We have a use case where we need to use the oneOf marshmallow extension, since we have an endpoint that has a general schema and it has a nested field that can be one of many schemas.

We heavily use flask-rest-api for automatically generating our documentation based off our schemas, so I'd like it to be able to support this as well.

**Comment by lafrech** [comment]
I suppose you're talking about https://github.com/marshmallow-code/marshmallow-oneofschema.

This apispec issue has been raised here: https://github.com/marshmallow-code/apispec/pull/182.

Basically, there is no way to achieve polymorphism in marshmallow core. There are at least two libs doing it, with their pros and cons. Until one solution reaches marshmallow core, or apispec decides to pick one of them for this use case, there in no support for this in apispec either.

**Edit**: See [polymorphism](https://github.com/marshmallow-code/marshmallow/issues?q=label%3Apolymorphism) tag in marshmallow bugtracker.

The thread mentioned above links to an apispec extension supporting it, though.

Closing this as I don't think this is a flask-rest-api issue. Please comment if I'm mistaken and I'll reopen.
