### ISSUE TITLE
Generate OpenAPI from command line

### ISSUE THREAD

**Issue by manmat** [marshmallow-code/flask-smorest#87]
Hey guys, I am working on a CI/CD pipeline and I need to publish the openAPI spec to a proxy. Is it possible to generate it from the code with a call or it only gets generated once the app is running and it's only available on the specific URI?

**Comment by lafrech** [comment]
The spec is created at app instantiation so you need an app instantiated. You don't need to run the app and curl the URI, you can call

```py
api.spec.to_dict()
```

or 

```py
json.dumps(api.spec.to_dict())
```

I wouldn't mind adding a feature to create and print the spec from command line. It should be easy to achieve. I've been using click recently and I found it neat. You could use click for this. It wouldn't be an additional dependency since flask already depends on it, and it would be more consistent. If you decide to do this, please let us know.

**Comment by manmat** [comment]
Ok, I just created a file `generate.py`:
```
from main import api
import json

with open('api.json', 'w') as outfile:
    json.dump(api.spec.to_dict(), outfile)
```
This seems to work for the time being.

**Comment by manmat** [comment]
Also, you might consider adding an option to generate the info of the uri that serves the api json as part of that json description?

**Comment by lafrech** [comment]
Glad to see it was easy to achieve. Thanks for copying your file here.

On second thought, I don't see how this lib could provide an entry point for this as it would need the path to the app instance which is in the app code.

> Also, you might consider adding an option to generate the info of the uri that serves the api json as part of that json description?

I don't understand. You want the spec file to contain its own URI? Can you point me to the relevant spec section?

**Comment by manmat** [comment]
So here is my problem. I deploy my app to Google Cloud AppEngine. The app is secured with Identity Aware Proxy and I use cloud endpoints as an API management proxy. So I have to deploy the app then publis the api doc to the endpoints proxy, but the generated api doc doesn't have the definition of the uri that points to the documentation itself. For this reason that endpoint never gets published. Am I explaining myself clear? I am not sure

**Comment by lafrech** [comment]
I think I get it. You would like the doc URI to appear as a path in the API.

I see the doc as something external to the API. The fact that the code serves it as a commodity does not make it part of the API. So I think it is "normal" not to have the doc URI as a path.

Your use case looks like a deployment issue. I can't help much as I'm not familiar with the deployment platform, but IIUC there should be a way outside of this lib.

**Comment by manmat** [comment]
Thanks @lafrech , I did use the previous method to generate the doc, so the problem is already solved. I just suggested it as an optional flag if someone else might need it, but yeah, it's possible to go around it.

**Comment by lafrech** [comment]
I just sent a PR adding a command to print the OpenAPI document.

#154

It uses flask's Click-based command line interface. I had to dig a little to find out how to do it, but once you get it, it allows to add commands with a few lines of code. Nice.

**Comment by lafrech** [comment]
0.22.0 provides command lines to print/write docs.
