### ISSUE TITLE
How to add security description object?

### ISSUE THREAD

**Issue by manmat** [marshmallow-code/flask-smorest#91]
I need to include a security description to my OpenAPI doc that gets generated. Is there a preferred way to do this? if not, how do I add custom structure to the documentation on the top level? I want to achieve something as seen here: https://cloud.google.com/endpoints/docs/openapi/authenticating-users-firebase

**Comment by lafrech** [comment]
Please don't multipost.

The docs lack an example for this.

The security documentation at the top-level of the spec can be passed at instantiation or as a parameter.

This might help:
- https://github.com/Nobatek/flask-rest-api/pull/4
- https://flask-rest-api.readthedocs.io/en/stable/openapi.html#populate-the-root-document-object
- https://github.com/Nobatek/flask-rest-api/issues/36

**Comment by manmat** [comment]
Ok, thanks for the reply. I tried these and they worked fine.
