### ISSUE TITLE
blueprint.arguments(location="view_args") fails with "view_args is not a valid location"

### ISSUE THREAD

**Issue by serebrov** [marshmallow-code/flask-smorest#92]
Besides [standard locations](https://webargs.readthedocs.io/en/latest/quickstart.html#request-locations) (query, json, form, etc), `webargs` also supports Flask-specific `view_args` [option](https://webargs.readthedocs.io/en/latest/framework_support.html#url-matches) to validate the URL path parameters.

Here is the simplified example of my code:

```py
@blueprint.route("/update/<string:item_id>/<string:list>", methods=["POST"])
@blueprint.arguments(ItemInputSchema(), location="view_args")
@blueprint.response(ItemSchema())
def move_item(data: ItemInputArgs, item_id: string, list: string):
    """Move an item to the specified list."""
    return move_item_to_list(data.item, data.list)
```

In this case, I want to validate `item_id` (check that this is a valid ID of the object existing in the database) and `list` (check that this is a string matching per-defined list of values)
The schema looks like this:

```py
class ItemInputArgs:
    """Arguments for the POST /update/<item>/<list>."""

    def __init__(self, item: Item, list: string):
        self.item = item
        self.list = list

class ItemInputSchema(Schema):

    item_id = fields.Str(required=True)
    list = fields.Str(required=True)

    @validates("item_id")
    def validate_item_id(self, value: str) -> None:
        """Check if item exists in the DB."""
        item = Item.query.filter_by(id=value).one_or_none()
        if item is None:
            raise ValidationError("Item with this id does not exist", "item")

    @validates("list")
    def validate_list(self, value: str) -> None:
        if value not in ['value1', 'value2', 'value3']:
            raise ValidationError('Wrong list value')

    @post_load
    def make_object(self, data: JSON, **kwargs: Any) -> ItemInputArgs:
        return ItemInputArgs(
            Item.query.filter_by(item_id=data["item_id"]).one(),
        )
```

This fails with an **error**:

```py
    def arguments(
            self, schema, *, location='json', required=True,
            example=None, examples=None, **kwargs
    ):
        """Decorator specifying the schema used to deserialize parameters
        ...
        """
        try:
            openapi_location = __location_map__[location]
        except KeyError as exc:
            raise InvalidLocationError(
>               "{} is not a valid location".format(location)) from exc
E           flask_rest_api.exceptions.InvalidLocationError: view_args is not a valid location

venv/lib/python3.7/site-packages/flask_rest_api/arguments.py:47: InvalidLocationError
```

The `__location_map__` itself is taken from the `apispec` package: `from apispec.ext.marshmallow.openapi import __location_map__`.

The **workaround** I use is this (just patch the `__location_map__` and add `view_args`):

```py
from apispec.ext.marshmallow.openapi import __location_map__

# The `view_args` location is supported by FlaskParser in webargs, 
# but flask-rest-api looks into the __location_map__ and raises an error, 
# so we patch the map to allow `view_args` as `location` in @blueprint.arguments.
__location_map__["view_args"] = "view_args"
```

Not sure though if that affects the schema generation (I am not generating it yet, although planning to).

**Comment by lafrech** [comment]
Hi. Thanks for reporting.

(Note you can specify ```py before your code blocks to get syntax highlighting.)

I don't use webargs to validate path parameters as flask/werkzeug validation is often enough, so I never investigated this, but I knew it might be a little tricky.

This part of the code is removed in master branch (unreleased). Please give it a try.

You may have to keep your patch. Otherwise, you won't get errors but the doc will be wrong, with the location defaulting to `body`.

Here's what I'd try:

```py
from apispec.ext.marshmallow.openapi import __location_map__
__location_map__["view_args"] = "path"
```

Please tell us how it goes.

We should find a better way to address this.

**Comment by serebrov** [comment]
Thanks, using `__location_map__["view_args"] = "path"` works for me.

The master version (installed via `https://github.com/Nobatek/flask-rest-api/archive/master.zip`) also works without a patch.

**Comment by lafrech** [comment]
Yep, without the patch it won't error, but I'm not sure the parameter is correctly documented, is it?

**Comment by serebrov** [comment]
I've just finished my setup to also generate the docs and actually, it seems to work fine without a patch, just the parameters have `(view_args)` under the type:

![Selection_892](https://user-images.githubusercontent.com/597640/63871633-ea1c3180-c9c4-11e9-9775-7f9c4b4de801.jpg)

Sidenote (sorry to polluting this thread, not sure if this deserves a separate issue): I also feel like there is a documentation issue, as that is not immediately clear how to setup the api docs endpoint. I referred to #26 and both [quickstart](https://flask-rest-api.readthedocs.io/en/stable/quickstart.html) and [open api](https://flask-rest-api.readthedocs.io/en/stable/openapi.html) pages to find the combination of parameters I need to make the documentation work.

Probably extended example on the "quickstart" page could help:

```python
app = Flask('My API')
app.config['OPENAPI_VERSION'] = '3.0.2'

# Api json docs is available under /doc/openapi.json
app.config['OPENAPI_URL_PREFIX'] = "/doc"

# The swagger UI is displayed under /doc/swagger
app.config['OPENAPI_SWAGGER_UI_PATH'] = "/swagger"
# The following is equivalent to OPENAPI_SWAGGER_UI_VERSION = '3.19.5'
app.config['OPENAPI_SWAGGER_UI_URL'] = "https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/3.19.5/"

api = Api(app)
```

**Comment by lafrech** [comment]
> I've just finished my setup to also generate the docs and actually, it seems to work fine without a patch, just the parameters have (view_args) under the type:

Yes. And if you apply the patch, you get path parameters correctly documented, right?

```py
from apispec.ext.marshmallow.openapi import __location_map__
__location_map__["view_args"] = "path"
```

We should do something about that, either in flask-rest-api or in apispec/webargs.

Hey, you know what? I just checked in webargs code

https://github.com/marshmallow-code/webargs/blob/b05a0ff986547944850bbaeba2d3778b947e57a5/src/webargs/flaskparser.py#L50-L53

What if you use `path` instead of `view_args` (nicer anyway IMHO...)? Does it work without the patch?

```py
@blueprint.route("/update/<string:item_id>/<string:list>", methods=["POST"])
@blueprint.arguments(ItemInputSchema(), location="view_args")
...
```

Regarding the docs, I wanted to keep the quickstart minimal. We could add an example or two in the openapi page.

**Comment by serebrov** [comment]
> Yes. And if you apply the patch, you get path parameters correctly documented, right?

Right, with `__location_map__["view_args"] = "path"`, the docs display `(path)` under the field type (although, I don't really mind having `view_args` there as long as nothing is broken).

> What if you use path instead of view_args (nicer anyway IMHO...)? Does it work without the patch?

Good finding! But `path` is not present in the `__location_map__` too and now the error becomes `flask_rest_api.exceptions.InvalidLocationError: path is not a valid location`, here is the list from `apispec.ext.marshmallow.openapi`:

```python
__location_map__ = {
    "query": "query",
    "querystring": "query",
    "json": "body",
    "headers": "header",
    "cookies": "cookie",
    "form": "formData",
    "files": "formData",
}
```

So the patch is still needed, but it now can be 

```python
from apispec.ext.marshmallow.openapi import __location_map__
__location_map__["path"] = "path"
```

And on master, it works without a patch with `location="path"`:

```python
@blueprint.route("/update/<string:item_id>/<string:list>", methods=["POST"])
@blueprint.arguments(ItemInputSchema(), location="path")
...
```

**Comment by lafrech** [comment]
>  I don't really mind having `view_args` there as long as nothing is broken

Yeah, but the doc is then not OAS compliant. I'm not sure what ReDoc does about that, but for instance, it presents path parameters under the "path parameters" section precisely because they have `"in" = "path"`.

> And on master, it works without a patch with `location="path"`:

Exactly. That was my point.

We should add a note in the docs to tell users which location are allowed, and include `path` in there.

**Comment by lafrech** [comment]
Done in 0a70faa115cca26c194a5d8f20f319f4de53f645.

Thanks for the feedback.
