### ISSUE TITLE
Can't figure out how to transmit request data in 'form' location

### ISSUE THREAD

**Issue by max-gartz** [marshmallow-code/flask-smorest#98]
Hi, I'm really new to Flask and flask-rest-api was recommended to me for building an api. 

I am trying to transmit authentication data via form arguments.. but I am not able to make it work. It works fine if I use 'json' or 'query' as argument location but for 'form' arguments I get a 422  "Unprocessable Entity" error.

```
{
  "errors": {
    "identifier": [
      "Missing data for required field."
    ],
    "password": [
      "Missing data for required field."
    ]
  },
  "status": "422 Unprocessable Entity: The request was well-formed but was unable to be followed due to semantic errors."
}
```
I would appreciate any help or advice.

The endpoint looks like this by the way: 

```py
@auth_bp.route('/login')
class Login(MethodView):

    @auth_bp.arguments(AuthSchema, location='form')
    @auth_bp.response(code=200)
    def post(self, data):
        """Login user"""
        return AuthService.login(data=data)
```

**Comment by lafrech** [comment]
Looks like `auth_bp.arguments` doesn't find the data in `request.form`.

It's kinda hard to help without the code that sends the request.

**Comment by max-gartz** [comment]
Sorry I am not sure what you mean with "the code that sends the request".
flask-rest-api generates the swagger ui and with @auth_bp.arguments(AuthSchema, location='form') the form parameters are available in the ui. At what point do I have control over the code that sends the request? What am I missing?

When I use query params or body params everything works fine. 

Thank you for your patience.

**Comment by lafrech** [comment]
Oh, so IIUC you're using swagger-ui to send the request.

Hard to tell where the problem comes from.

Please try with latest version. There are changes in 0.17 that might help.

You may want to post a minimal reproducible example. I can't promise I'll find the time to investigate myself, but someone might be able to help.

Could be useful to catch the exact request (URL, payload, headers) swagger-ui is sending.

**Comment by max-gartz** [comment]
Hi, thank you very much!

I updated to the latest version and it is working now.
