### ISSUE TITLE
Deserialization at point of request handling

### ISSUE THREAD

**Issue by georgesequeira** [marshmallow-code/flask-smorest#99]
Hi!

First off, let me say that this library is the closest thing to what I've been looking for as an API framework in flask. Awesome job pulling in the best practices of API framework tools! I will try to put a few hours a week to helping in any way I can.

My question. As shown in your documentation, even though we validate data with marshmallow schema's, in our handlers, we end up receiving a dictionary with the data. I was curious what the rationale for that is? Why not pass the formed object to the handler.

Today it looks like:
```
@blp.route('/')
class Pets(MethodView):

    @blp.arguments(PetSchema)
    @blp.response(PetSchema, code=201)
    def post(self, new_data):
        """Add a new pet"""
        item = Pet.create(**new_data)
        return item
```

instead of

```
@blp.route('/')
class Pets(MethodView):

    @blp.arguments(PetSchema)
    @blp.response(PetSchema, code=201)
    def post(self, pet):
        """Add a new pet"""
        pet = Pet.create(
          name=pet.name,
          age=pet.age)
        return pet.to_dict()
```

In my mind it clearly separates concerns and creates an explicit object to handle. Having a dictionary actually may influence me (and others) to tie the schemas parameter name directly to my database model parameter names so that I can quickly move through them. That starts getting into the magical land of https://marshmallow-sqlalchemy.readthedocs.io/en/latest/

Cheers!
George

**Comment by lafrech** [comment]
Hi. Thanks for the nice feedback. Much appreciated.

This lib slowly is reaching a level of maturity that makes external contributions possible. There is not much discussion about the roadmap. Just the 1.0 milestone right now. You can check open issues, see if you have ideas.

Of course, enhancements are welcome. You may open issues to check the idea is accepted before doing too much work.

--------------------------------------------------

Regarding your question.

What you're asking for is feasible.

```py
class BaseSchema(ma.Schema):
    OBJ_CLS = None

    @post_load
    def make_obj(self, data):
        return OBJ_CLS(**data)

class UserSchema(BaseSchema):
    OBJ_CLS = models.User
```

I think I do this, or used to do this, in an application.

It's easy to achieve in user code. It requires to use a `BaseSchema` but big apps probably use one already for some reason. Doing this by default in this lib would mean enforcing the `OBJ_CLS` attribute name. It would have to be an opt-in. I don't really see the benefit of adding the feature here.

There may be issues if your model doesn't match your schemas. We have a MongoDB-based app where the model defines documents and is exposed in partial schemas for document subparts. In this case, there is no corresponding object for a subpart of the document. In a PUT request, we must instantiate the model object then use the dict to update it.

**Comment by georgesequeira** [comment]
Ah! I see. I understood the different data layers as:

Outside world - JSON
| API
API Handler - **UserSchema**
Business Logic - **UserSchema**
| DB
Database Logic - UserDBSchema

But it makes sense that for a proper separation of concern, the business logic should have its own model (e.g. UserModel).

Awesome to have a separation of concerns discovery accidentally!

I agree that there isn't a benefit of adding the feature here.

Thank you for clarifying.
